import { ROM_NAMES } from '../dsp/stages/roms'
import type { ControlKey } from '../controls'
import { GRID_ROWS } from './drums'

export interface SliderDef {
  key: ControlKey
  label: string
  min: number
  max: number
  step: number
  unit: string
  help: string
  choices?: string[]
  curve?: 'log'
}

export const STAGE_ORDER = [
  'Sources',
  'Bends',
  'Pedals',
  'Patch',
  'Feedback',
  'Tape',
  'Master',
] as const
export type StagePlace = (typeof STAGE_ORDER)[number]

export interface Group {
  name: string
  place: StagePlace
  sliders: SliderDef[]
  /** Controls a widget of the group's own turns, because a row of sliders is
      the wrong shape for them. */
  editor?: { kind: 'drums'; keys: ControlKey[] }
}

export const GROUPS: Group[] = [
  {
    name: 'Toy keyboard',
    place: 'Sources',
    sliders: [
      {
        key: 'chipLevel',
        label: 'Level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the toy keyboard chip is in the source mix.',
      },
      {
        key: 'chipTune',
        label: 'Tune ROM',
        min: 0,
        max: ROM_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: ROM_NAMES,
        help: 'Which demo song the chip plays from ROM. Each ROM carries its own sequencer rate, so the clock and the starve bend hit them differently.',
      },
      {
        key: 'chipTone',
        label: 'Tone',
        min: 0,
        max: 3,
        step: 1,
        unit: '',
        choices: ['organ 1/2', 'reed 1/4', 'clav 1/8', 'buzz 1/16'],
        help: 'Which width of pulse the tone selector taps off the divider chain. Narrow taps null different harmonics and thin out — the chip never levelled them, so they get quieter as they get reedier.',
      },
      {
        key: 'chipAccomp',
        label: 'Auto bass-chord',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The accompaniment section: bass on the step, chord stab on the offbeat, under whichever demo song is running. It reads the chord off the melody and picks major or minor from the ROM’s own notes. Same divider, same rail — starve the chip and the backing band goes down with it.',
      },
      {
        key: 'chipClockX',
        label: 'Clock',
        min: 0.05,
        max: 16,
        step: 0.01,
        unit: '×',
        curve: 'log',
        help: 'Drags the master clock crystal. Everything the chip does — pitch, tempo, envelopes — slurs together.',
      },
      {
        key: 'chipStarve',
        label: 'Starve',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Sags the shared toy supply rail. Pitch dives, notes collapse, and past the brownout threshold the watchdog reboots the chip — the tune keeps restarting.',
      },
      {
        key: 'chipBendSpot',
        label: 'Bend spot',
        min: 0,
        max: 4,
        step: 1,
        unit: '',
        choices: ['off', 'clock', 'counter', 'bias', 'gate'],
        help: 'Where the virtual pot is soldered onto the die: clock feedback, program counter, DAC bias, or the gate line. Each spot breaks differently.',
      },
      {
        key: 'chipBendPot',
        label: 'Bend pot',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Turns the pot on the chosen bend spot. Zero is an open circuit; up is a harder short.',
      },
    ],
  },
  {
    name: 'Toy drums',
    place: 'Sources',
    editor: { kind: 'drums', keys: GRID_ROWS.map(r => r.key) },
    sliders: [
      {
        key: 'drumLevel',
        label: 'Level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the toy drum machine is in the source mix.',
      },
      {
        key: 'drumBpm',
        label: 'Tempo',
        min: 10,
        max: 3000,
        step: 1,
        unit: 'bpm',
        curve: 'log',
        help: 'Sequencer clock. Musical at the bottom; drag it far past the panel legend and the pattern smears into a buzz.',
      },
      {
        key: 'drumSwing',
        label: 'Swing',
        min: 0,
        max: 0.9,
        step: 0.01,
        unit: '',
        help: 'Holds every offbeat step back and takes the time off the step after, so the pattern shuffles without the tempo moving.',
      },
      {
        key: 'drumTune',
        label: 'Tune',
        min: 0.25,
        max: 4,
        step: 0.01,
        unit: '×',
        curve: 'log',
        help: 'The pitch trimmer inside the kit: every struck voice moves together. It rides on the supply, so starving the toy drags it down again.',
      },
      {
        key: 'drumDecay',
        label: 'Decay',
        min: 0.25,
        max: 4,
        step: 0.01,
        unit: '×',
        curve: 'log',
        help: 'Stretches or chokes every envelope at once. Short is a click track; long lets the kick and toms run into each other.',
      },
      {
        key: 'drumBits',
        label: 'Bit depth',
        min: 2,
        max: 16,
        step: 0.1,
        unit: 'bit',
        help: 'Word length of the one cheap DAC the whole kit shares. Stock is 7 — wind it down and the tails turn to gravel before the hits do.',
      },
      {
        key: 'drumRetrigHz',
        label: 'Retrigger',
        min: 0,
        max: 4000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'Retriggers the current step at this rate. Slow is a machine-gun roll; past ~40 Hz the retrigger period becomes the pitch and the drum screams.',
      },
      {
        key: 'drumCross',
        label: 'Cross-patch',
        min: 0,
        max: 5,
        step: 1,
        unit: '',
        choices: [
          'off',
          'kick/snare',
          'snare/hat',
          'kick/hat',
          'rotate',
          'whole kit',
        ],
        help: 'Bridges two voices’ envelope pins so each amplifier hears the wrong envelope. Rotate passes the original three around the ring; whole kit passes all six, so the cowbell rings on a kick and the clap answers a tom.',
      },
      {
        key: 'drumCrossAmt',
        label: 'Cross bleed',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far each amplifier leans across. All the way over is a full swap — the kick fires on snare steps, the noise swells on kicks, and a hat tick puts a pitch blip through the kick.',
      },
    ],
  },
  {
    name: 'Chaos osc',
    place: 'Sources',
    sliders: [
      {
        key: 'oscLevel',
        label: 'Level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the oscillator pair is in the source mix.',
      },
      {
        key: 'oscAHz',
        label: 'Osc A',
        min: 20,
        max: 4000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'The audible oscillator.',
      },
      {
        key: 'oscBHz',
        label: 'Osc B',
        min: 0.1,
        max: 4000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'The modulator. Sub-audio rates warble and siren; audio rates tear A into sidebands.',
      },
      {
        key: 'oscXmod',
        label: 'Cross-mod',
        min: 0,
        max: 2000,
        step: 1,
        unit: 'Hz',
        curve: 'log',
        help: 'How many Hz of deviation B drags A through. Turn it up and the pair stops being two pitches.',
      },
      {
        key: 'oscShape',
        label: 'Shape',
        min: 0,
        max: 2,
        step: 1,
        unit: '',
        choices: ['square', 'saw', 'pulse'],
        help: 'Waveform of both oscillators.',
      },
      {
        key: 'oscStarve',
        label: 'Starve',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Sags the oscillator supply. Loud output drags pitch and amplitude down until it stalls, recovers, and stalls again — motorboating for free.',
      },
    ],
  },
  {
    name: 'Noise & crackle',
    place: 'Sources',
    sliders: [
      {
        key: 'noiseLevel',
        label: 'Noise',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'White noise level into the chain.',
      },
      {
        key: 'noiseColor',
        label: 'Color',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Tilts the noise dark (rumble) or bright (hiss).',
      },
      {
        key: 'crackleAmp',
        label: 'Crackle',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dirty-pot contact crackle: random spikes rung through a resonant filter.',
      },
      {
        key: 'crackleRate',
        label: 'Crackle rate',
        min: 0,
        max: 200,
        step: 1,
        unit: '/s',
        help: 'How often the contact sparks.',
      },
    ],
  },
  {
    name: 'Mic & sample',
    place: 'Sources',
    sliders: [
      {
        key: 'micLevel',
        label: 'Mic',
        min: 0,
        max: 2,
        step: 0.01,
        unit: '',
        help: 'Microphone gain into the patch point. Watch speaker feedback — or use it.',
      },
      {
        key: 'micPatch',
        label: 'Mic patch',
        min: 0,
        max: 6,
        step: 1,
        unit: '',
        choices: [
          'mix',
          'chip rail',
          'osc FM',
          'delay fb',
          'ring car',
          'drum trig',
          'glitch trig',
        ],
        help: 'Where the mic wire is soldered: the mix bus, the toy supply rail (yell to brown it out), oscillator A’s FM input, the delay feedback path, the ring mod carrier, or the trigger line of the drum machine or glitch buffer — clap at it and the circuit fires.',
      },
      {
        key: 'sampleLevel',
        label: 'Sample',
        min: 0,
        max: 2,
        step: 0.01,
        unit: '',
        help: 'Level of the dropped audio file, looping through the chain.',
      },
      {
        key: 'sampleSpeed',
        label: 'Speed',
        min: -4,
        max: 4,
        step: 0.01,
        unit: '×',
        help: 'Playback speed. Negative runs backwards; zero freezes on the current spot.',
      },
    ],
  },
  {
    name: 'Slot order',
    place: 'Bends',
    sliders: [0, 1, 2, 3, 4, 5].map(i => ({
      key: `bendSlot${i}` as ControlKey,
      label: `Slot ${i + 1}`,
      min: 0,
      max: 7,
      step: 1,
      unit: '',
      choices: [
        '—',
        'ring',
        'crush',
        'dist',
        'comb',
        'glitch',
        'filt',
        'shift',
      ],
      help: 'Which bend runs in this position. The signal walks the slots top to bottom; duplicates run once at their first slot.',
    })),
  },
  {
    name: 'Ring mod',
    place: 'Bends',
    sliders: [
      {
        key: 'ringHz',
        label: 'Carrier',
        min: 0.1,
        max: 8000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'Carrier frequency. Sub-audio is tremolo; audio rates put metallic sidebands everywhere.',
      },
      {
        key: 'ringShape',
        label: 'Carrier shape',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['sine', 'square'],
        help: 'Square carrier chops instead of gliding — harsh AM-radio ghosts.',
      },
      {
        key: 'ringMix',
        label: 'Mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
  {
    name: 'Crusher',
    place: 'Bends',
    sliders: [
      {
        key: 'bits',
        label: 'Bits',
        min: 1,
        max: 16,
        step: 0.1,
        unit: 'bit',
        help: 'Word length of the virtual DAC. Fractional bits sweep the step size continuously into gnarl.',
      },
      {
        key: 'srHz',
        label: 'Rate',
        min: 100,
        max: 48000,
        step: 1,
        unit: 'Hz',
        curve: 'log',
        help: 'Sample-and-hold rate. Everything above half this folds down as aliasing.',
      },
      {
        key: 'srJitter',
        label: 'Jitter',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Re-rolls each hold length. Jittered decimation smears the aliases into inharmonic hash.',
      },
      {
        key: 'crushMix',
        label: 'Mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
  {
    name: 'Shaper',
    place: 'Bends',
    sliders: [
      {
        key: 'driveDb',
        label: 'Drive',
        min: 0,
        max: 60,
        step: 0.5,
        unit: 'dB',
        help: 'Gain into the shaping stage.',
      },
      {
        key: 'distMode',
        label: 'Circuit',
        min: 0,
        max: 4,
        step: 1,
        unit: '',
        choices: ['soft', 'hard', 'fuzz', 'fold', 'rect'],
        help: 'Soft saturation, hard clip, asymmetric fuzz, wavefolder, or full rectifier.',
      },
      {
        key: 'distBias',
        label: 'Bias',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'DC offset into the clipper. Off-center bias gates quiet passages and adds even harmonics.',
      },
      {
        key: 'distToneHz',
        label: 'Tone',
        min: 200,
        max: 20000,
        step: 10,
        unit: 'Hz',
        curve: 'log',
        help: 'Low-pass after the shaping — the tone knob on the pedal.',
      },
      {
        key: 'subLevel',
        label: 'Sub octave',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'A flip-flop divider mixed in before the shaping — an octave down, and it mistracks on complex input like the vintage pedals did. Needs Mix up to hear it.',
      },
      {
        key: 'distMix',
        label: 'Mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
  {
    name: 'Comb',
    place: 'Bends',
    sliders: [
      {
        key: 'combHz',
        label: 'Pitch',
        min: 20,
        max: 2000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'The comb’s resonant pitch — it plays like a string.',
      },
      {
        key: 'combFb',
        label: 'Feedback',
        min: 0,
        max: 1.2,
        step: 0.01,
        unit: '',
        help: 'Past 1.0 it self-oscillates and the saturation holds the scream instead of exploding.',
      },
      {
        key: 'combDampHz',
        label: 'Damping',
        min: 500,
        max: 15000,
        step: 10,
        unit: 'Hz',
        curve: 'log',
        help: 'In-loop low-pass. Low values pluck like a dead string; high values ring metallic.',
      },
      {
        key: 'combMix',
        label: 'Mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
  {
    name: 'Screech filter',
    place: 'Bends',
    sliders: [
      {
        key: 'filtHz',
        label: 'Cutoff',
        min: 30,
        max: 12000,
        step: 1,
        unit: 'Hz',
        curve: 'log',
        help: 'Where the filter bites — and the pitch it screams at when resonance passes 1.',
      },
      {
        key: 'filtRes',
        label: 'Resonance',
        min: 0,
        max: 1.3,
        step: 0.01,
        unit: '',
        help: 'Past 1.0 the filter self-oscillates at the cutoff, held by its own saturation. Ping it with crackle, or park it in the feedback loop and let it pick the squeal.',
      },
      {
        key: 'filtMode',
        label: 'Mode',
        min: 0,
        max: 2,
        step: 1,
        unit: '',
        choices: ['LP', 'BP', 'HP'],
        help: 'Low-pass growls, band-pass hones the scream, high-pass thins to a whistle.',
      },
      {
        key: 'filtDriveDb',
        label: 'Drive',
        min: 0,
        max: 36,
        step: 0.5,
        unit: 'dB',
        help: 'Gain into the filter — overdriving the input fights the resonance.',
      },
      {
        key: 'filtMix',
        label: 'Mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
  {
    name: 'Glitch buffer',
    place: 'Bends',
    sliders: [
      {
        key: 'glitchProb',
        label: 'Chance',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Probability that each slice boundary fires a glitch event.',
      },
      {
        key: 'glitchSliceMs',
        label: 'Slice',
        min: 10,
        max: 1000,
        step: 1,
        unit: 'ms',
        curve: 'log',
        help: 'Slice length. Short is a buzz, long is a broken CD player.',
      },
      {
        key: 'glitchRepeat',
        label: 'Repeats',
        min: 1,
        max: 8,
        step: 1,
        unit: '×',
        help: 'Maximum stutter count per event; each event rolls its own.',
      },
      {
        key: 'glitchRevProb',
        label: 'Reverse',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Chance a stutter plays backwards.',
      },
      {
        key: 'glitchPitch',
        label: 'Pitch',
        min: 0,
        max: 3,
        step: 1,
        unit: '',
        choices: ['norm', 'down', 'up', 'rand'],
        help: 'Replay stutters at pitch, an octave away, or a random pick each event.',
      },
      {
        key: 'glitchFreeze',
        label: 'Freeze',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['off', 'hold'],
        help: 'Holds the current slice forever — the CD stuck on a note.',
      },
      {
        key: 'glitchMix',
        label: 'Mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
  {
    name: 'Freq shifter',
    place: 'Bends',
    sliders: [
      {
        key: 'shiftHz',
        label: 'Shift',
        min: 0.1,
        max: 2000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'Moves every partial by the same number of Hz instead of the same ratio, so harmonics stop being harmonics. Under 5 Hz it is a slow inharmonic drift; up high everything turns to clangour.',
      },
      {
        key: 'shiftDir',
        label: 'Direction',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['up', 'down'],
        help: 'Which sideband survives. Down folds low partials through zero and back up again.',
      },
      {
        key: 'shiftFb',
        label: 'Feedback',
        min: 0,
        max: 1.1,
        step: 0.01,
        unit: '',
        help: 'Each lap shifts again, so partials climb (or fall) forever — the barber pole. Park it in a slot inside the global loop and the squeal can never settle on a pitch.',
      },
      {
        key: 'shiftMix',
        label: 'Mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
  {
    name: 'Stompbox',
    place: 'Pedals',
    sliders: [
      {
        key: 'stompCircuit',
        label: 'Circuit',
        min: 0,
        max: 5,
        step: 1,
        unit: '',
        choices: ['screamer', 'rat', 'muff', 'germanium', 'octave', 'gate'],
        help: 'Which dirt box is on the board. Screamer clips inside the feedback loop so the dry note walks under it; rat clips to ground behind a slew-limited op-amp; muff is two clipping stages and a scooped tone stack that never decays; germanium is the lopsided one whose bias rides down on the signal; octave rectifies into a ringing transformer; gate is misbiased to the edge of cutoff.',
      },
      {
        key: 'stompDrive',
        label: 'Drive',
        min: 0,
        max: 60,
        step: 0.5,
        unit: 'dB',
        help: 'Gain into the clipping stage — and how hard the pedal leans on its own battery.',
      },
      {
        key: 'stompTone',
        label: 'Tone',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Each circuit’s tone control is a different network, so the knob means something different on each: a low-pass on most, the scoop blend on the muff, where the transformer rings on the octave, and what pitch the starved one squeals at.',
      },
      {
        key: 'stompBias',
        label: 'Bias',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Shifts the clipper off centre — the classic starve mod. Quiet passages gate out, loud ones come through one-sided and full of even harmonics. On the gate circuit this is what walks it toward cutoff, so it shuts higher and higher up.',
      },
      {
        key: 'stompSag',
        label: 'Battery',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How dead the 9V is. The rail falls as the pedal works, so notes bloom and collapse; it also shares the board’s supply, so Starve and Brownout drag it down. On the gate circuit a flat battery is what makes it howl on its own.',
      },
      {
        key: 'stompLevel',
        label: 'Level',
        min: -24,
        max: 12,
        step: 0.5,
        unit: 'dB',
        help: 'Makeup gain out of the pedal.',
      },
      {
        key: 'stompMix',
        label: 'Mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet — at zero the pedal is off the board.',
      },
    ],
  },
  {
    name: 'Tape delay',
    place: 'Pedals',
    sliders: [
      {
        key: 'delayMs',
        label: 'Time',
        min: 20,
        max: 2000,
        step: 1,
        unit: 'ms',
        curve: 'log',
        help: 'Delay time. Grabbing it drags the tape — pitch smears while it settles.',
      },
      {
        key: 'dlyFb',
        label: 'Feedback',
        min: 0,
        max: 1.5,
        step: 0.01,
        unit: '',
        help: 'Past 1.0 the repeats grow until the tape saturates — a runaway howl that darkens each lap.',
      },
      {
        key: 'wowDepthMs',
        label: 'Wow',
        min: 0,
        max: 10,
        step: 0.1,
        unit: 'ms',
        help: 'Slow speed wobble of the transport.',
      },
      {
        key: 'wowHz',
        label: 'Wow rate',
        min: 0.1,
        max: 8,
        step: 0.1,
        unit: 'Hz',
        help: 'How fast the wobble cycles.',
      },
      {
        key: 'flutter',
        label: 'Flutter',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Fast random speed jitter — worn pinch roller.',
      },
      {
        key: 'dlyToneHz',
        label: 'Tone',
        min: 500,
        max: 15000,
        step: 10,
        unit: 'Hz',
        curve: 'log',
        help: 'High-frequency loss per repeat — tape generation loss.',
      },
      {
        key: 'tapeBrake',
        label: 'Brake',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Drags the capstan. The transport has weight, so everything already on the tape sags in pitch on the way down and spins back up on release.',
      },
      {
        key: 'tapeMotorRail',
        label: 'Supply drag',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Wires the motor to the same dying supply as the toy: whenever the rail droops — Starve or Brownout Sag — the tape slows with it and the repeats dive.',
      },
      {
        key: 'dlyMix',
        label: 'Mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
  {
    name: 'Spring verb',
    place: 'Pedals',
    sliders: [
      {
        key: 'revDecayS',
        label: 'Decay',
        min: 0.1,
        max: 8,
        step: 0.1,
        unit: 's',
        curve: 'log',
        help: 'How long the springs ring.',
      },
      {
        key: 'revToneHz',
        label: 'Tone',
        min: 500,
        max: 12000,
        step: 10,
        unit: 'Hz',
        curve: 'log',
        help: 'Damping inside the tank.',
      },
      {
        key: 'revBoing',
        label: 'Boing',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Spring dispersion — the drip and chirp on transients.',
      },
      {
        key: 'revMix',
        label: 'Mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
  {
    name: 'Patch bay',
    place: 'Patch',
    sliders: [
      {
        key: 'modLfoHz',
        label: 'LFO rate',
        min: 0.02,
        max: 40,
        step: 0.01,
        unit: 'Hz',
        curve: 'log',
        help: 'The bay’s own oscillator, free-running. Slow is a sweep, fast is a buzz through whatever it is wired to.',
      },
      {
        key: 'modLfoShape',
        label: 'LFO shape',
        min: 0,
        max: 3,
        step: 1,
        unit: '',
        choices: ['sine', 'ramp', 'square', 'S&H'],
        help: 'Sine glides, ramp saws, square jumps, S&H holds a fresh random step each cycle.',
      },
      ...[0, 1].flatMap(i => [
        {
          key: `mod${i}Src` as ControlKey,
          label: `Wire ${i + 1} from`,
          min: 0,
          max: 8,
          step: 1,
          unit: '',
          choices: [
            'off',
            'LFO',
            'supply',
            'envelope',
            'mic',
            'body X',
            'body Y',
            'fb bus',
            'ROM step',
          ],
          help: 'What the wire picks up: the bay LFO, the sag on the dying supply, the output envelope, the mic, either axis of the body pad, the feedback bus itself, or the chip’s sequencer ramping across each ROM step — the one source that stays in time with the tune.',
        },
        {
          key: `mod${i}Dest` as ControlKey,
          label: `Wire ${i + 1} to`,
          min: 0,
          max: 12,
          step: 1,
          unit: '',
          choices: [
            'filt cut',
            'ring car',
            'comb pitch',
            'crush rate',
            'chip clock',
            'retrigger',
            'tape speed',
            'glitch',
            'fb amount',
            'stomp drive',
            'shift Hz',
            'bit depth',
            'drum cross',
          ],
          help: 'Where the other end is soldered. Pitch-like destinations move in octaves; glitch and feedback amount just add.',
        },
        {
          key: `mod${i}Depth` as ControlKey,
          label: `Wire ${i + 1} depth`,
          min: -1,
          max: 1,
          step: 0.01,
          unit: '',
          help: 'How hard the wire pushes. Negative flips it — the supply dying can drag a pitch up as easily as down.',
        },
      ]),
    ],
  },
  {
    name: 'Body contact',
    place: 'Patch',
    sliders: [
      {
        key: 'bodyX',
        label: 'Contact X',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Left–right position on the contact pad. Wire it to something in the bay, then play the pad.',
      },
      {
        key: 'bodyY',
        label: 'Contact Y',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Top–bottom position on the contact pad — how hard you are leaning on the contacts.',
      },
    ],
  },
  {
    name: 'Feedback bus',
    place: 'Feedback',
    sliders: [
      {
        key: 'fbAmt',
        label: 'Amount',
        min: 0,
        max: 1.5,
        step: 0.01,
        unit: '',
        help: 'Output patched back into the source mix. With no input this is the whole no-input-mixer instrument.',
      },
      {
        key: 'fbDelayMs',
        label: 'Loop time',
        min: 0.05,
        max: 500,
        step: 0.05,
        unit: 'ms',
        curve: 'log',
        help: 'The loop’s own comb delay. Tiny values squeal at kHz; long values self-play the chain.',
      },
      {
        key: 'fbTone',
        label: 'Tilt',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Darkens or brightens the loop — decides which register the squeal settles into.',
      },
      {
        key: 'fbDest',
        label: 'Patched into',
        min: 0,
        max: 3,
        step: 1,
        unit: '',
        choices: ['mix', 'osc FM', 'chip rail', 'delay'],
        help: 'Where the return wire is soldered: the source mix, oscillator A’s FM input (the loop plays the pitch), the toy supply rail (the output browns out its own toy), or straight into the tape.',
      },
    ],
  },
  {
    name: 'Tape machine',
    place: 'Tape',
    sliders: [
      {
        key: 'tapeMix',
        label: 'To tape',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How much of the board you hear through the machine rather than straight off the bus. The dry side runs down the same nominal head delay, so this only combs once the transport wobbles.',
      },
      {
        key: 'tapeSpeed',
        label: 'Speed',
        min: 0,
        max: 2,
        step: 1,
        unit: '',
        choices: ['3¾ ips', '7½ ips', '15 ips'],
        help: 'Moves the whole machine at once: head-gap loss, the replay bump, hiss level, wow rate and how long a spool wrap takes to come back round. Slow is dark, noisy and unsteady.',
      },
      {
        key: 'tapeDrive',
        label: 'Level',
        min: -12,
        max: 15,
        step: 0.5,
        unit: 'dB',
        help: 'Record level. Highs hit the oxide through a pre-emphasis curve and come back through its inverse, so they saturate first — transients round off before anything sounds distorted.',
      },
      {
        key: 'tapeBias',
        label: 'Bias',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Underbiased is bright and crunchy; overbiased is dull and squashed. Distortion and top end move against each other.',
      },
      {
        key: 'tapeHiss',
        label: 'Hiss',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Noise laid on the medium, not on the mix — the playback head colours it, the speed sets how loud it is, and it breathes a little with the signal.',
      },
      {
        key: 'tapeWow',
        label: 'Wow',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Capstan eccentricity plus slow drift, so the pitch never sits quite still.',
      },
      {
        key: 'tapeFlutter',
        label: 'Flutter',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The fast wobble, plus scrape flutter — the grain that comes off tape dragging past the head.',
      },
      {
        key: 'tapeDrop',
        label: 'Dropouts',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Shed oxide. Highs go before level does, which is what makes these sound like tape rather than like the power cutting.',
      },
      {
        key: 'tapePrint',
        label: 'Print-through',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The layer wound underneath bleeding into this one — a dull ghost of the signal, one spool wrap behind.',
      },
      {
        key: 'tapeAzimuth',
        label: 'Azimuth',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Head misalignment: the right channel lags and loses top end. Collapses to mono badly, on purpose.',
      },
    ],
  },
  {
    name: 'Brownout',
    place: 'Master',
    sliders: [
      {
        key: 'brownAmt',
        label: 'Sag',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The master supply sags under load: loud passages collapse and pump like a dying battery.',
      },
      {
        key: 'brownRate',
        label: 'Dropouts',
        min: 0,
        max: 50,
        step: 0.5,
        unit: 'Hz',
        help: 'Random full dropouts — a loose power jack.',
      },
      {
        key: 'brownCrackle',
        label: 'Crackle',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Crackle injected in proportion to how hard the supply is working.',
      },
      {
        key: 'humLevel',
        label: 'Ground hum',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'A ground loop: mains fundamental plus rectifier buzz, louder as the supply strains, with the ripple wobbling the rail.',
      },
      {
        key: 'humHz',
        label: 'Mains',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['50 Hz', '60 Hz'],
        help: 'Which grid you’re plugged into.',
      },
    ],
  },
  {
    name: 'Output',
    place: 'Master',
    sliders: [
      {
        key: 'outGain',
        label: 'Gain',
        min: -60,
        max: 12,
        step: 0.5,
        unit: 'dB',
        help: 'Master gain before the safety clipper and limiter.',
      },
    ],
  },
]

export const ALL_SLIDERS: SliderDef[] = GROUPS.flatMap(g => g.sliders)
export const EDITOR_KEYS = new Set<ControlKey>(
  GROUPS.flatMap(g => g.editor?.keys ?? []),
)

/** Every control a group owns, whatever kind of widget turns it. */
export function groupKeys(group: Group): ControlKey[] {
  return [...group.sliders.map(s => s.key), ...(group.editor?.keys ?? [])]
}

// Halfway between two enum choices is no choice at all, and halfway between two
// step masks is a pattern neither side wrote — a morph cuts both at its
// midpoint rather than interpolating them.
export const CUT_KEYS = new Set<ControlKey>([
  ...ALL_SLIDERS.filter(s => s.choices).map(s => s.key),
  ...EDITOR_KEYS,
])

// Yours, not the look's: how loud it comes out, how hot the mic runs and where
// your finger is on the pad. Neither a random roll nor a morph touches them, so
// picking a look never changes your monitoring level and a morph never drags the
// body pad out from under you mid-gesture.
export const HOLD_KEYS = new Set<ControlKey>([
  'outGain',
  'micLevel',
  'bodyX',
  'bodyY',
])
export const SLIDER_BY_KEY = new Map<ControlKey, SliderDef>(
  ALL_SLIDERS.map(s => [s.key, s]),
)

export function sliderFor(key: ControlKey): SliderDef {
  const def = SLIDER_BY_KEY.get(key)
  if (!def) throw new Error(`no slider for ${key}`)
  return def
}

export const GROUP_BY_KEY = new Map<ControlKey, string>(
  GROUPS.flatMap(g => g.sliders.map(s => [s.key, g.name] as const)),
)

export function groupFor(key: ControlKey): string {
  const name = GROUP_BY_KEY.get(key)
  if (!name) throw new Error(`no group for ${key}`)
  return name
}

export function snapToStep(
  def: Pick<SliderDef, 'min' | 'max' | 'step'>,
  value: number,
): number {
  const stepped = def.min + Math.round((value - def.min) / def.step) * def.step
  return Math.min(def.max, Math.max(def.min, Number(stepped.toFixed(6))))
}
