import type { Controls } from '../../controls'
import { DRUM_ROMS } from '../../drums'
import { DEST } from '../../dsp/modbus'
import { FM_EFFECT_NAMES } from '../../dsp/stages/fmEffects'
import { FM_VOICE_NAMES } from '../../dsp/stages/fmVoices'

export interface PresetDef {
  name: string
  blurb: string
  patch: Partial<Controls>
}

const romMasks = (name: string) => DRUM_ROMS.find(r => r.name === name)!.masks

/** By name, so the catalog survives the ROM growing another script. */
const effect = (name: string) => FM_EFFECT_NAMES.indexOf(name)

/** And the same for the patches under the voice buttons. */
const voice = (name: string) => FM_VOICE_NAMES.indexOf(name)

export const PRESETS: PresetDef[] = [
  {
    name: 'dying toy',
    blurb: 'Starved rail, sagging pitch, watchdog reboots mid-tune',
    patch: {
      chipLevel: 0.85,
      chipStarve: 0.85,
      chipClockX: 0.6,
      brownAmt: 0.35,
      dlyMix: 0.3,
      delayMs: 300,
      dlyFb: 0.5,
    },
  },
  {
    name: 'paperclip',
    blurb:
      'Bare metal on the timing pin — every touch dives an octave and snaps back',
    patch: {
      chipLevel: 0.85,
      chipAccomp: 0.5,
      chipStarve: 0.3,
      chipCap: 0.6,
      chipClipHz: 3,
      chipClipClock: 0.45,
      faultCluster: 0.55,
      humLevel: 0.2,
      brownAmt: 0.25,
      drumLevel: 0.25,
    },
  },
  {
    name: 'flat batteries',
    blurb:
      'Cells too far gone to hold the rail — the whole toy runs low and late',
    patch: {
      chipLevel: 0.85,
      chipBattery: 0.75,
      chipAccomp: 0.6,
      drumLevel: 0.55,
      drumBits: 5,
      tapeMix: 0.45,
      tapeHiss: 0.5,
    },
  },
  {
    name: 'melody scrambler',
    blurb: 'Pot soldered on the program counter',
    patch: {
      chipLevel: 0.9,
      chipClockX: 2.5,
      chipBendSpot: 2,
      chipBendPot: 0.8,
      glitchMix: 0.5,
      glitchProb: 0.45,
      glitchSliceMs: 90,
    },
  },
  {
    name: 'wrong song',
    blurb:
      'A data line held high — the tune keeps its rhythm and its rests fill in',
    patch: {
      chipLevel: 0.9,
      chipAccomp: 0.7,
      chipClockX: 1.2,
      chipDataLine: 3,
      chipDataFault: 2,
    },
  },
  {
    name: 'half a tune',
    blurb:
      'An address line on the floor: the song folds into its own first half',
    patch: {
      chipLevel: 0.9,
      chipAccomp: 0.5,
      chipAddrLine: 4,
      chipAddrFault: 1,
      dlyMix: 0.25,
      delayMs: 260,
      dlyFb: 0.4,
    },
  },
  {
    name: 'stuck key',
    blurb: 'The FM chip never told the key came up, so nothing it plays ends',
    patch: {
      chipLevel: 0,
      drumLevel: 0.5,
      fmLevel: 0.8,
      fmVoice: 1,
      fmBright: 0.6,
      fmLength: 0.3,
      fmDataLine: 5,
      fmDataFault: 2,
    },
  },
  {
    name: 'dawn chorus',
    blurb: 'Bird calls off the effect ROM, every write of them arriving wrong',
    patch: {
      chipLevel: 0,
      drumLevel: 0,
      fmLevel: 0.8,
      fmEffect: effect('bird'),
      fmDataLine: 3,
      fmDataFault: 0,
      fmBusCut: 0.55,
    },
  },
  {
    name: 'weather station',
    blurb: 'Wind, with the address latch missing one pulse in seven',
    patch: {
      chipLevel: 0,
      drumLevel: 0,
      fmLevel: 0.8,
      fmEffect: effect('wind'),
      fmStrobe: 0.15,
    },
  },
  {
    name: 'air raid',
    blurb: 'A siren filed under the wrong registers as it climbs',
    patch: {
      chipLevel: 0,
      drumLevel: 0,
      fmLevel: 0.8,
      fmEffect: effect('siren'),
      fmAddrLine: 6,
      fmAddrFault: 0,
      fmBusCut: 0.5,
    },
  },
  {
    name: 'stuck cricket',
    blurb:
      'The key-up lands next door, so the chirps never stop being one note',
    patch: {
      chipLevel: 0,
      drumLevel: 0,
      fmLevel: 0.8,
      fmEffect: effect('crickets'),
      fmStrobe: 0.4,
    },
  },
  {
    name: 'gravel dac',
    blurb: 'The kit’s converter built from resistors nobody measured',
    patch: {
      chipLevel: 0,
      drumLevel: 0.9,
      drumBits: 5,
      drumLadder: 0.9,
      drumDecay: 1.6,
    },
  },
  {
    name: 'machine gun',
    blurb: 'Drum machine retriggered into rolls',
    patch: {
      chipLevel: 0,
      drumLevel: 0.9,
      drumBpm: 170,
      drumRetrigHz: 24,
      distMix: 0.6,
      driveDb: 24,
      distMode: 2,
      dlyMix: 0.2,
      delayMs: 140,
    },
  },
  {
    name: 'drum scream',
    blurb: 'Retrigger past audio rate — the kit becomes a pitch',
    patch: {
      chipLevel: 0,
      drumLevel: 0.95,
      drumBpm: 45,
      drumRetrigHz: 700,
      crushMix: 0.5,
      bits: 6,
      revMix: 0.3,
      revDecayS: 3,
    },
  },
  {
    name: 'crushed chip',
    blurb: 'Overclocked tune through a dying DAC',
    patch: {
      chipLevel: 0.85,
      chipClockX: 2,
      bits: 3,
      srHz: 2600,
      srJitter: 0.6,
      crushMix: 0.9,
    },
  },
  {
    name: 'tape scream',
    blurb: 'Runaway delay feedback, warped transport',
    patch: {
      chipLevel: 0.5,
      dlyMix: 0.7,
      dlyFb: 1.4,
      delayMs: 120,
      dlyToneHz: 3000,
      wowDepthMs: 4,
      wowHz: 2,
      flutter: 0.5,
    },
  },
  {
    name: 'no-input squeal',
    blurb: 'The mixer patched into itself, nothing at the input',
    patch: {
      chipLevel: 0,
      fbAmt: 1.35,
      fbDelayMs: 0.6,
      fbTone: 0.4,
      distMix: 0.4,
      driveDb: 26,
      distMode: 1,
    },
  },
  {
    name: 'haunted spring',
    blurb: 'Slow chip through a huge dispersive tank',
    patch: {
      chipLevel: 0.45,
      chipClockX: 0.5,
      revMix: 0.75,
      revDryCut: 0.75,
      revDecayS: 6,
      revBoing: 0.9,
      ringMix: 0.35,
      ringHz: 3.5,
      noiseLevel: 0.08,
      noiseColor: -0.5,
    },
  },
  {
    name: 'contact crackle',
    blurb: 'Dirty pot sparks ringing a screaming comb',
    patch: {
      chipLevel: 0,
      crackleAmp: 0.9,
      crackleRate: 55,
      combMix: 0.8,
      combFb: 1.15,
      combHz: 220,
      revMix: 0.4,
    },
  },
  {
    name: 'dogfight',
    blurb: 'Cross-modulated oscillators starving themselves',
    patch: {
      chipLevel: 0,
      oscLevel: 0.85,
      oscXmod: 900,
      oscBHz: 2.2,
      oscStarve: 0.5,
      ringMix: 0.3,
      ringHz: 40,
    },
  },
  {
    name: 'ground loop',
    blurb: 'Bad power: hum, sag and a straining supply',
    patch: {
      chipLevel: 0.55,
      chipStarve: 0.5,
      humLevel: 0.8,
      brownAmt: 0.5,
      brownCrackle: 0.4,
      revMix: 0.3,
      revDecayS: 3,
    },
  },
  {
    name: 'fm howl',
    blurb: 'The feedback bus soldered onto the FM input',
    patch: {
      chipLevel: 0,
      oscLevel: 0.7,
      oscAHz: 110,
      fbAmt: 1.2,
      fbDelayMs: 40,
      fbDest: 1,
      dlyMix: 0.4,
      delayMs: 260,
      dlyFb: 0.6,
    },
  },
  {
    name: 'the loop eats itself',
    blurb:
      'Blank tape under the toy, coming round worse every lap — press play and watch the reel',
    patch: {
      chipLevel: 0.7,
      // Named, so it arrives on one press. A fader is yours and a preset keeps
      // what is yours — until it names it, which is the whole of the rule. This
      // one has to: a tape machine whose output is down is a preset that sounds
      // like the board without it, and the blurb used to have to say so.
      sampleLevel: 1,
      loopRec: 1,
      loopErase: 0.12,
      loopSecs: 4,
      tapeMix: 1,
      tapeSpeed: 0,
      tapeHiss: 0.5,
      tapeDrop: 0.45,
      tapeWow: 0.35,
      tapeDrive: 5,
    },
  },
  {
    name: 'the desk lets go',
    blurb:
      'Three cross-fed loops through amps that block — erupts and dies on its own',
    patch: {
      chipLevel: 0,
      crackleAmp: 0.2,
      fbAmt: 1.2,
      fbDelayMs: 5,
      fbTone: 0.3,
      fb2Amt: 1.1,
      fb2Ms: 37,
      fb2Tone: -0.4,
      fb3Amt: 1,
      fb3Ms: 121,
      fb3Tone: 0.1,
      fbCross: 0.55,
      fbRails: 1,
      fbAsym: 0.4,
      fbSlew: 0.35,
      fbBlock: 0.9,
      fbSag: 0.5,
      mixDrive: 8,
    },
  },
  {
    name: 'divider fuzz',
    blurb: 'A flip-flop octave under the tune, clipped along with it',
    patch: {
      chipLevel: 0.75,
      distMix: 0.8,
      subLevel: 0.9,
      driveDb: 18,
      distMode: 2,
      distToneHz: 4000,
    },
  },
  {
    name: 'wall of muff',
    blurb: 'Two clipping stages that never let the note decay',
    patch: {
      chipLevel: 0.7,
      stompCircuit: 2,
      stompDrive: 34,
      stompTone: 0.35,
      stompLevel: -6,
      stompMix: 1,
      revMix: 0.3,
      revDecayS: 3,
    },
  },
  {
    name: 'flat germanium',
    blurb: 'The lopsided circuit on a dead cell, spluttering as each note goes',
    patch: {
      chipLevel: 0.8,
      stompCircuit: 3,
      stompDrive: 30,
      stompTone: 0.4,
      stompBias: -0.25,
      stompSag: 0.85,
      stompMix: 1,
      dlyMix: 0.25,
      delayMs: 280,
      dlyFb: 0.45,
    },
  },
  {
    name: 'octave up',
    blurb:
      'Rectified into a ringing transformer — an octave on one note, gargle on two',
    patch: {
      chipLevel: 0.75,
      stompCircuit: 4,
      stompDrive: 26,
      stompTone: 0.6,
      stompMix: 0.9,
      revMix: 0.35,
      revBoing: 0.7,
    },
  },
  {
    name: 'velcro',
    blurb:
      'Starved to the edge of cutoff: it gates, sputters and howls between notes',
    patch: {
      chipLevel: 0.7,
      stompCircuit: 5,
      stompDrive: 40,
      stompTone: 0.3,
      stompBias: 0.35,
      stompSag: 0.8,
      stompLevel: -6,
      stompMix: 1,
    },
  },
  {
    name: 'squeezed screamer',
    blurb:
      'The bay envelope wired onto the drive, so it digs in as it gets loud',
    patch: {
      chipLevel: 0.8,
      stompCircuit: 0,
      stompDrive: 16,
      stompTone: 0.55,
      stompMix: 1,
      mod0Src: 3,
      mod0Dest: 9,
      mod0Depth: 0.7,
      dlyMix: 0.3,
      delayMs: 320,
    },
  },
  {
    name: 'cold room',
    blurb: 'A soldered DAC bias into a ringing comb, slowed right down',
    patch: {
      chipLevel: 0.7,
      chipClockX: 0.7,
      chipBendSpot: 3,
      chipBendPot: 0.25,
      ringMix: 0.3,
      ringHz: 6,
      combMix: 0.4,
      combHz: 180,
      combFb: 0.8,
      dlyMix: 0.3,
      delayMs: 300,
      flutter: 0.3,
      revMix: 0.5,
      revDecayS: 4,
    },
  },
  {
    name: 'dying walkman',
    blurb: 'A chewed tape running into a failing DAC',
    patch: {
      chipLevel: 0.75,
      chipClockX: 0.8,
      bits: 7,
      srHz: 9000,
      crushMix: 0.5,
      dlyMix: 0.5,
      delayMs: 260,
      dlyFb: 0.45,
      wowDepthMs: 5,
      wowHz: 0.8,
      flutter: 0.45,
      dlyToneHz: 3500,
      revMix: 0.35,
    },
  },
  {
    name: 'wrong voices',
    blurb: 'Envelope pins bridged — the kit fires the wrong drums',
    patch: {
      chipLevel: 0,
      drumLevel: 0.9,
      ...romMasks('disco'),
      drumBpm: 128,
      drumCross: 4,
      drumCrossAmt: 0.85,
      distMix: 0.35,
      driveDb: 12,
      revMix: 0.25,
    },
  },
  {
    name: 'yell into it',
    blurb:
      'Mic soldered into the delay feedback path — bring your mic level up',
    patch: {
      chipLevel: 0,
      micPatch: 3,
      dlyMix: 0.7,
      dlyFb: 0.95,
      delayMs: 220,
      distMix: 0.6,
      driveDb: 28,
    },
  },
  {
    name: 'motor sag',
    blurb: 'Tape motor wired to the same failing supply as the toy',
    patch: {
      chipLevel: 0.7,
      dlyMix: 0.6,
      delayMs: 320,
      dlyFb: 0.8,
      dlyToneHz: 3200,
      tapeMotorRail: 1,
      brownAmt: 0.85,
      brownRate: 3,
    },
  },
  {
    name: 'barber pole',
    blurb: 'Every lap through the shifter climbs again, so nothing lands',
    patch: {
      chipLevel: 0.5,
      bendSlot0: 7,
      shiftMix: 0.85,
      shiftHz: 3,
      shiftFb: 0.92,
      revMix: 0.35,
      revDecayS: 4,
    },
  },
  {
    name: 'bell metal',
    blurb: 'Shifted far enough that the harmonics stop being harmonics',
    patch: {
      chipLevel: 0.8,
      bendSlot0: 7,
      shiftMix: 1,
      shiftHz: 380,
      dlyMix: 0.3,
      delayMs: 180,
      dlyFb: 0.45,
    },
  },
  {
    name: 'lean on it',
    blurb:
      'Skin on the pad rides the cutoff, and pressing harder opens the feedback',
    patch: {
      chipLevel: 0,
      crackleAmp: 0.5,
      crackleRate: 30,
      bendSlot0: 6,
      filtMix: 1,
      filtRes: 1.2,
      filtHz: 180,
      mod0Src: 5,
      mod0Dest: 0,
      mod0Depth: 0.9,
      mod1Src: 6,
      mod1Dest: 8,
      mod1Depth: 0.6,
      fbDelayMs: 3,
    },
  },
  {
    name: 'clock wobble',
    blurb: 'The bay LFO dragging the chip crystal around',
    patch: {
      chipLevel: 0.85,
      modLfoHz: 0.5,
      mod0Src: 1,
      mod0Dest: 4,
      mod0Depth: 0.55,
      dlyMix: 0.25,
      delayMs: 240,
    },
  },
  {
    name: 'clap at it',
    blurb:
      'Mic on the drum trigger line: clap and it fires your pattern — bring your mic level up',
    patch: {
      chipLevel: 0,
      drumLevel: 0.9,
      micPatch: 5,
      distMix: 0.45,
      driveDb: 16,
      revMix: 0.3,
    },
  },
  {
    name: 'backbeat',
    blurb: 'Claps on two and four, shuffled hard, through four bits of DAC',
    patch: {
      chipLevel: 0,
      drumLevel: 0.9,
      drumBpm: 104,
      drumSwing: 0.5,
      drumDecay: 1.4,
      drumBits: 4,
      ...romMasks('clap'),
      revMix: 0.3,
      revDecayS: 2.5,
    },
  },
  {
    name: 'found tape',
    blurb:
      'The toy, printed clean to 7½ ips — hiss, a little wow, nothing broken',
    patch: {
      chipLevel: 0.7,
      tapeMix: 1,
      tapeSpeed: 1,
      tapeDrive: 4,
      tapeHiss: 0.55,
      tapeWow: 0.3,
      tapeFlutter: 0.25,
      revMix: 0.18,
      revDecayS: 1.6,
    },
  },
  {
    name: 'shed oxide',
    blurb:
      'Slow tape gone soft: dropouts, print-through, a squeal that comes and goes',
    patch: {
      chipLevel: 0.7,
      tapeMix: 1,
      tapeSpeed: 0,
      tapeDrive: 10,
      tapeBias: 0.55,
      tapeHiss: 0.8,
      tapeWow: 0.8,
      tapeFlutter: 0.7,
      tapeDrop: 0.6,
      tapeSqueal: 0.45,
      tapePrint: 0.7,
      tapeAzimuth: 0.35,
      chipStarve: 0.2,
    },
  },
  {
    name: 'pinned',
    blurb: 'Underbiased and slammed — the machine as the distortion',
    patch: {
      chipLevel: 0.8,
      drumLevel: 0.5,
      drumBpm: 96,
      tapeMix: 1,
      tapeSpeed: 2,
      tapeDrive: 15,
      tapeBias: -0.85,
      tapeHiss: 0.4,
      tapeWow: 0.15,
      tapeFlutter: 0.2,
      dlyMix: 0.25,
      delayMs: 180,
    },
  },
  {
    name: 'kit on keys',
    blurb:
      'Kick soldered onto the keyboard’s gate: one hit, one step of the ROM',
    patch: {
      chipLevel: 0.8,
      chipAccomp: 0.35,
      drumLevel: 0.6,
      drumBpm: 104,
      trigToKeys: 1,
      trigKeysNote: 1,
      dlyMix: 0.22,
      delayMs: 288,
      dlyFb: 0.35,
    },
  },
  {
    name: 'call and answer',
    blurb: 'The snare strikes a chord, and every note it strikes claps back',
    patch: {
      chipLevel: 0.75,
      drumLevel: 0.7,
      drumBpm: 92,
      trigToKeys: 2,
      trigKeysNote: 3,
      trigToDrum: 4,
      revMix: 0.3,
      revDecayS: 2.4,
    },
  },
  {
    name: 'hit gate',
    blurb:
      'A wire off the kit’s trigger line onto the cutoff — shut between hits',
    patch: {
      chipLevel: 0.7,
      drumLevel: 0.8,
      filtMix: 1,
      filtHz: 180,
      filtRes: 0.85,
      mod0Src: 9,
      mod0Dest: 0,
      mod0Depth: 0.85,
    },
  },
  {
    name: 'slapback',
    blurb: 'The plain box, set the plain way — one repeat, close behind',
    patch: {
      chipLevel: 0.8,
      drumLevel: 0.5,
      echoLevel: 0.45,
      echoMs: 110,
      echoFb: 0.15,
      echoToneHz: 6000,
    },
  },
  {
    name: 'bucket brigade',
    blurb: 'Every lap through the chips comes back darker than the last',
    patch: {
      chipLevel: 0.75,
      drumLevel: 0.45,
      echoMode: 1,
      echoLevel: 0.6,
      echoMs: 480,
      echoFb: 0.72,
      echoToneHz: 5000,
    },
  },
  {
    name: 'played backwards',
    blurb: 'Half a second at a time, each one handed back the other way round',
    patch: {
      chipLevel: 0.8,
      echoMode: 2,
      echoLevel: 0.75,
      echoMs: 500,
      echoFb: 0.35,
      revMix: 0.25,
    },
  },
  {
    // The three lanes the bay grew onto the tape, on the one board that needs no
    // file dropped in: the reel threads itself blank, the toy plays onto it, and
    // a wire walks a half-second window over the four seconds it laid down. What
    // it plays back is somewhere the board has been rather than where it is.
    name: 'wandering loop',
    blurb:
      'A blank reel, a short loop walking over what the toy put on it — press play',
    patch: {
      chipLevel: 0.7,
      chipAccomp: 0.45,
      sampleLevel: 1,
      loopRec: 0.7,
      loopErase: 0.3,
      loopSecs: 4,
      loopIn: 0,
      loopOut: 0.14,
      modLfoHz: 0.06,
      mod0Src: 1,
      mod0Dest: DEST.loopSlide,
      mod0Depth: 0.9,
      tapeMix: 0.6,
    },
  },
  {
    name: 'seasick',
    blurb:
      'A wire off the bay onto the pedal’s time — the repeats never settle',
    patch: {
      chipLevel: 0.75,
      echoLevel: 0.6,
      echoMs: 300,
      echoFb: 0.55,
      modLfoHz: 0.35,
      mod0Src: 1,
      mod0Dest: DEST.echoMs,
      mod0Depth: 0.3,
    },
  },
  {
    name: 'two hands',
    blurb: 'Gate jumper cut — the toy on one keybed, the FM chip on the other',
    patch: {
      chipLevel: 0.75,
      fmLevel: 0.7,
      fmKeyGate: 1,
      fmVoice: voice('bass'),
      fmBright: 0.45,
      fmModDecay: 8,
      revDecayS: 2,
      revMix: 0.2,
    },
  },
  {
    name: 'doubled',
    blurb: 'The gate jumper left on: one key, a square and an FM string on it',
    patch: {
      chipLevel: 0.6,
      fmLevel: 0.6,
      fmVoice: voice('strings'),
      fmBright: 0.6,
      fmLength: 1.2,
      revDecayS: 3,
      revMix: 0.3,
    },
  },
]
