import type { ControlKey } from '../../controls'
import type { Group } from './types'

// Which stage each bend slot names, the short name a slot wears when it names
// it, and the dry/wet that decides whether you hear it. The slot choices and
// their range come off this table, in this order — slot value n names entry
// n−1, so the order here is the order the slots count in. The map reads it to
// lay the path out; a roll reads it to put one bend on the board on its own.
export const BENDS = [
  { group: 'Ring mod', label: 'ring', mix: 'ringMix' },
  { group: 'Crusher', label: 'crush', mix: 'crushMix' },
  { group: 'Clipper', label: 'dist', mix: 'distMix' },
  { group: 'Comb', label: 'comb', mix: 'combMix' },
  { group: 'Glitch buffer', label: 'glitch', mix: 'glitchMix' },
  { group: 'Screech filter', label: 'filt', mix: 'filtMix' },
  { group: 'Freq shifter', label: 'shift', mix: 'shiftMix' },
] as const satisfies readonly {
  group: string
  label: string
  mix: ControlKey
}[]

/** The bend a slot value names — nothing, for the empty slot at zero. */
export const bendAt = (slot: number) => BENDS[Math.round(slot) - 1]

export const BEND_SLOT_KEYS = [0, 1, 2, 3, 4, 5].map(
  i => `bendSlot${i}` as ControlKey,
)

export const BEND_GROUPS: Group[] = [
  {
    name: 'Slot order',
    place: 'Bends',
    sliders: BEND_SLOT_KEYS.map((key, i) => ({
      key,
      label: `Slot ${i + 1}`,
      min: 0,
      max: BENDS.length,
      step: 1,
      unit: '',
      choices: ['—', ...BENDS.map(b => b.label)],
      help: 'Which bend runs in this position. The signal walks the slots top to bottom; duplicates run once at their first slot.',
    })),
  },
  {
    name: 'Ring mod',
    place: 'Bends',
    sliders: [
      {
        key: 'ringHz',
        label: 'Carrier',
        min: 0.1,
        max: 8000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'Carrier frequency. Sub-audio is tremolo; audio rates put metallic sidebands everywhere.',
      },
      {
        key: 'ringShape',
        label: 'Carrier shape',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['sine', 'square'],
        help: 'Square carrier chops instead of gliding — harsh AM-radio ghosts.',
      },
      {
        key: 'ringMix',
        label: 'Mix',
        role: 'mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
  {
    name: 'Crusher',
    place: 'Bends',
    sliders: [
      {
        key: 'bits',
        label: 'Bits',
        min: 1,
        max: 16,
        step: 0.1,
        unit: 'bit',
        help: 'Word length of the virtual DAC. Fractional bits sweep the step size continuously into gnarl.',
      },
      {
        key: 'srHz',
        label: 'Rate',
        min: 100,
        max: 48000,
        step: 1,
        unit: 'Hz',
        curve: 'log',
        help: 'Sample-and-hold rate. Everything above half this folds down as aliasing.',
      },
      {
        key: 'srJitter',
        label: 'Jitter',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Re-rolls each hold length. Jittered decimation smears the aliases into inharmonic hash.',
      },
      {
        key: 'crushMix',
        label: 'Mix',
        role: 'mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
  {
    name: 'Clipper',
    place: 'Bends',
    sliders: [
      {
        key: 'driveDb',
        label: 'Drive',
        min: 0,
        max: 60,
        step: 0.5,
        unit: 'dB',
        help: 'Gain into the shaping stage.',
      },
      {
        key: 'distMode',
        label: 'Circuit',
        min: 0,
        max: 4,
        step: 1,
        unit: '',
        choices: ['soft', 'hard', 'fuzz', 'fold', 'rect'],
        help: 'Soft saturation, hard clip, asymmetric fuzz, wavefolder, or full rectifier.',
      },
      {
        key: 'distBias',
        label: 'Bias',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        split: { at: 0 },
        help: 'DC offset into the clipper. Off-center bias gates quiet passages and adds even harmonics.',
      },
      {
        key: 'distToneHz',
        label: 'Tone',
        min: 200,
        max: 20000,
        step: 10,
        unit: 'Hz',
        curve: 'log',
        help: 'Low-pass after the shaping — the tone knob on the pedal.',
      },
      {
        key: 'subLevel',
        label: 'Sub octave',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'A flip-flop divider mixed in before the shaping — an octave down, and it mistracks on complex input like the vintage pedals did. Needs Mix up to hear it.',
      },
      {
        key: 'distMix',
        label: 'Mix',
        role: 'mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
  {
    name: 'Comb',
    place: 'Bends',
    sliders: [
      {
        key: 'combHz',
        label: 'Pitch',
        min: 20,
        max: 4000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'The comb’s resonant pitch — it plays like a string.',
      },
      {
        key: 'combFb',
        label: 'Feedback',
        min: 0,
        max: 1.2,
        step: 0.01,
        unit: '',
        help: 'Past 1.0 it self-oscillates and the saturation holds the scream instead of exploding.',
      },
      {
        key: 'combDampHz',
        label: 'Damping',
        min: 500,
        max: 15000,
        step: 10,
        unit: 'Hz',
        curve: 'log',
        help: 'In-loop low-pass. Low values pluck like a dead string; high values ring metallic.',
      },
      {
        key: 'combMix',
        label: 'Mix',
        role: 'mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
  {
    name: 'Screech filter',
    place: 'Bends',
    sliders: [
      {
        key: 'filtHz',
        label: 'Cutoff',
        min: 30,
        max: 12000,
        step: 1,
        unit: 'Hz',
        curve: 'log',
        help: 'Where the filter bites — and the pitch it screams at when resonance passes 1.',
      },
      {
        key: 'filtRes',
        label: 'Resonance',
        min: 0,
        max: 1.3,
        step: 0.01,
        unit: '',
        help: 'Past 1.0 the filter self-oscillates at the cutoff, held by its own saturation. Ping it with crackle, or park it in the feedback loop and let it pick the squeal.',
      },
      {
        key: 'filtMode',
        label: 'Mode',
        min: 0,
        max: 2,
        step: 1,
        unit: '',
        choices: ['LP', 'BP', 'HP'],
        help: 'Low-pass growls, band-pass hones the scream, high-pass thins to a whistle.',
      },
      {
        key: 'filtDriveDb',
        label: 'Drive',
        min: 0,
        max: 36,
        step: 0.5,
        unit: 'dB',
        help: 'Gain into the filter — overdriving the input fights the resonance.',
      },
      {
        key: 'filtMix',
        label: 'Mix',
        role: 'mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
  {
    name: 'Glitch buffer',
    place: 'Bends',
    sliders: [
      {
        key: 'glitchProb',
        label: 'Chance',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Probability that each slice boundary fires a glitch event.',
      },
      {
        key: 'glitchSliceMs',
        label: 'Slice',
        min: 10,
        max: 1000,
        step: 1,
        unit: 'ms',
        curve: 'log',
        help: 'Slice length. Short is a buzz, long is a broken CD player.',
      },
      {
        key: 'glitchRepeat',
        label: 'Repeats',
        min: 1,
        max: 8,
        step: 1,
        unit: '×',
        help: 'Maximum stutter count per event; each event rolls its own.',
      },
      {
        key: 'glitchRevProb',
        label: 'Reverse',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Chance a stutter plays backwards.',
      },
      {
        key: 'glitchPitch',
        label: 'Pitch',
        min: 0,
        max: 3,
        step: 1,
        unit: '',
        choices: ['norm', 'down', 'up', 'rand'],
        help: 'Replay stutters at pitch, an octave away, or a random pick each event.',
      },
      {
        key: 'glitchFreeze',
        label: 'Freeze',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['off', 'hold'],
        help: 'Holds the current slice forever — the CD stuck on a note.',
      },
      {
        key: 'glitchMix',
        label: 'Mix',
        role: 'mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
  {
    name: 'Freq shifter',
    place: 'Bends',
    sliders: [
      {
        key: 'shiftHz',
        label: 'Shift',
        min: 0.1,
        max: 2000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'Moves every partial by the same number of Hz instead of the same ratio, so harmonics stop being harmonics. Under 5 Hz it is a slow inharmonic drift; up high everything turns to clangour.',
      },
      {
        key: 'shiftDir',
        label: 'Direction',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['up', 'down'],
        help: 'Which sideband survives. Down folds low partials through zero and back up again.',
      },
      {
        key: 'shiftFb',
        label: 'Feedback',
        min: 0,
        max: 1.1,
        step: 0.01,
        unit: '',
        help: 'Each lap shifts again, so partials climb (or fall) forever — the barber pole. Park it in a slot inside the global loop and the squeal can never settle on a pitch.',
      },
      {
        key: 'shiftMix',
        label: 'Mix',
        role: 'mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet.',
      },
    ],
  },
]
