import type { Group } from './types'

export const FEEDBACK_GROUPS: Group[] = [
  {
    name: 'Feedback bus',
    place: 'Feedback',
    folded: ['strips 2 and 3', 'the return amps'],
    sliders: [
      {
        key: 'fbAmt',
        label: 'Amount',
        min: 0,
        max: 1.5,
        step: 0.01,
        unit: '',
        help: 'Output patched back into the source mix. With no input this is the whole no-input-mixer instrument.',
      },
      {
        key: 'fbDelayMs',
        label: 'Loop time',
        min: 0.05,
        max: 500,
        step: 0.05,
        unit: 'ms',
        curve: 'log',
        help: 'The loop’s own comb delay. Tiny values squeal at kHz; long values self-play the chain.',
      },
      {
        key: 'fbTone',
        label: 'Tilt',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        split: { at: 0 },
        reads: v =>
          v === 0
            ? 'flat'
            : `${Math.abs(v).toFixed(2)} ${v < 0 ? 'dark' : 'bright'}`,
        help: 'Darkens or brightens the loop — decides which register the squeal settles into.',
      },
      {
        key: 'fbDest',
        label: 'Patched into',
        min: 0,
        max: 3,
        step: 1,
        unit: '',
        choices: ['mix', 'osc FM', 'chip rail', 'delay'],
        help: 'Where the return wire is soldered: the source mix, oscillator A’s FM input (the loop plays the pitch), the toy supply rail (the output browns out its own toy), or straight into the tape.',
      },
      {
        key: 'fbCross',
        label: 'Cross',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        needs: c => c.fb2Amt > 0 || c.fb3Amt > 0,
        help: 'Sends each strip round the next one’s delay instead of its own. At rest the strips are three separate loops that happen to share a bus, and each finds a squeal and holds it. Wound up they are a ring, and a ring of saturating delays has nothing to settle on: it climbs into a mode, holds for a few seconds, and falls out of it into another one with nobody touching anything. This is the knob the rest of the desk is here for. With one strip up it does nothing, because there is no second channel to cross to.',
      },
      {
        key: 'fb2Amt',
        label: 'Strip 2',
        part: 'strips 2 and 3',
        min: 0,
        max: 1.5,
        step: 0.01,
        unit: '',
        help: 'A second send and return, on its own fader. Two loops of different lengths on one bus beat against each other rather than agreeing, so the squeal gets a slow throb the single loop could never have.',
      },
      {
        key: 'fb2Ms',
        label: 'Strip 2 time',
        part: 'strips 2 and 3',
        min: 0.05,
        max: 500,
        step: 0.05,
        unit: 'ms',
        curve: 'log',
        help: 'How long strip 2’s cord and its circuit take. The stock times are deliberately not multiples of each other: set two strips to the same number and they lock into one loud loop, and everything interesting here is the two of them refusing to.',
      },
      {
        key: 'fb2Tone',
        label: 'Strip 2 tilt',
        part: 'strips 2 and 3',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        split: { at: 0 },
        reads: v =>
          v === 0
            ? 'flat'
            : `${Math.abs(v).toFixed(2)} ${v < 0 ? 'dark' : 'bright'}`,
        help: 'Strip 2’s own tilt. Tilt the strips apart and they scream in different registers — a top-end shriek over a bottom-end growl, off one bus.',
      },
      {
        key: 'fb3Amt',
        label: 'Strip 3',
        part: 'strips 2 and 3',
        min: 0,
        max: 1.5,
        step: 0.01,
        unit: '',
        help: 'The third send and return. Two loops beat; three cross-fed loops stop being predictable at all, which is what Cross is for.',
      },
      {
        key: 'fb3Ms',
        label: 'Strip 3 time',
        part: 'strips 2 and 3',
        min: 0.05,
        max: 500,
        step: 0.05,
        unit: 'ms',
        curve: 'log',
        help: 'How long strip 3’s cord takes. Stock it is the long one — a squeal, a flutter and an echo on the same bus.',
      },
      {
        key: 'fb3Tone',
        label: 'Strip 3 tilt',
        part: 'strips 2 and 3',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        split: { at: 0 },
        reads: v =>
          v === 0
            ? 'flat'
            : `${Math.abs(v).toFixed(2)} ${v < 0 ? 'dark' : 'bright'}`,
        help: 'Strip 3’s own tilt.',
      },
      {
        key: 'fbRails',
        label: 'Rails',
        part: 'the return amps',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How hard the return amps hit their supply. At rest they saturate the way everything else on this board does — a tanh, which rolls off into its ceiling and is the sound of something being driven warmly. Wound up they stop instead: the wave meets the rail and squares off flat, which is the difference between a loop that howls and a loop that buzzsaws.',
      },
      {
        key: 'fbAsym',
        label: 'Rail balance',
        part: 'the return amps',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        split: { at: 0 },
        reads: v =>
          v === 0
            ? 'matched'
            : `${Math.abs(v).toFixed(2)} ${v < 0 ? 'low rail' : 'high rail'}`,
        help: 'How far apart the two supplies are. Real ones never match, and a wave that squares off on one half before the other puts out even harmonics as well as odd — an octave under the squeal rather than more of it. It also leaves dc behind, which walks the operating point of everything downstream until the safety tail takes it back off.',
      },
      {
        key: 'fbSlew',
        label: 'Slew',
        part: 'the return amps',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How slow the return amps are. Asked for an edge faster than it can swing, an amp puts out a ramp instead. On one tone that is a dull sort of distortion. On two it is neither tone’s harmonics, because what a slew limiter does to a sum is not what it does to either part — so a bus with three squeals on it fills up with hash that has no harmonic structure to fall back on. The one thing here that is not a note.',
      },
      {
        key: 'fbSag',
        label: 'Supply',
        part: 'the return amps',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far the return amps pull their own rail down. At rest they have all the headroom in the world, which no amplifier has ever had. Wound up they draw on the supply by how hard they are working: the current goes in milliseconds and comes back over a third of a second, and below about two thirds of the rail the stages start losing their bias rather than merely their headroom, so what the desk can put out falls away faster than the volts do. Bringing the strips up against it is a fight — the desk screams, takes its own supply out, and has to find a quieter place to run from, which is a long way from the level it would have sat at with the rail held up. It is the same rail the toy is on, so Starve and Brownout pull it out from under the desk as well, and it is Blocking rather than this that makes the loop let go outright.',
      },
      {
        key: 'fbBlock',
        label: 'Blocking',
        part: 'the return amps',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The coupling cap into the return amp, and what happens when it is driven past its rails. Current flows where the cap can only leak it back slowly, the charge walks the bias down to cutoff, and the stage stops conducting — so the loop goes dead. With nothing getting through there is nothing left to hold the charge, so it drains, the stage comes back, and it blocks again. The loop dies, rebuilds out of whatever is on the bus, and dies again, at a rate set by how hard it is being driven and by nothing with a rate control on it.',
      },
    ],
  },
]
