import type { Group } from './types'

export const FEEDBACK_GROUPS: Group[] = [
  {
    name: 'Feedback bus',
    place: 'Feedback',
    editor: { kind: 'feedback' },
    folded: ['strips 2 and 3', 'the return amps'],
    sliders: [
      {
        key: 'fbAmt',
        label: 'Amount',
        min: 0,
        max: 1.5,
        step: 0.01,
        unit: '',
        help: 'Output patched back into the source mix. With no input this is the whole no-input-mixer instrument.',
      },
      {
        key: 'fbDelayMs',
        label: 'Loop time',
        min: 0.05,
        max: 500,
        step: 0.05,
        unit: 'ms',
        curve: 'log',
        help: 'The loop’s own comb delay. Tiny values squeal at kHz; long values self-play the chain.',
      },
      {
        key: 'fbTone',
        label: 'Tilt',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        split: { at: 0 },
        reads: v =>
          v === 0
            ? 'flat'
            : `${Math.abs(v).toFixed(2)} ${v < 0 ? 'dark' : 'bright'}`,
        help: 'Darkens or brightens the loop — decides which register the squeal settles into.',
      },
      {
        key: 'fbDest',
        label: 'Patched into',
        min: 0,
        max: 3,
        step: 1,
        unit: '',
        choices: ['mix', 'osc FM', 'chip rail', 'delay'],
        help: 'Where the return wire is soldered: the source mix, oscillator A’s FM input (the loop plays the pitch), the toy supply rail (the output browns out its own toy), or straight into the tape.',
      },
      {
        key: 'fbCross',
        label: 'Cross',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        needs: c => c.fb2Amt > 0 || c.fb3Amt > 0,
        help: 'Sends each strip round the next one’s delay instead of its own. Separate loops each find a squeal and hold it; a ring of them has nothing to settle on, and wanders between modes untouched. Needs two strips up.',
      },
      {
        key: 'fb2Amt',
        label: 'Strip 2',
        part: 'strips 2 and 3',
        min: 0,
        max: 1.5,
        step: 0.01,
        unit: '',
        help: 'A second send and return, on its own fader. Two loops of different lengths on one bus beat against each other rather than agreeing, so the squeal gets a slow throb the single loop could never have.',
      },
      {
        key: 'fb2Ms',
        label: 'Strip 2 time',
        part: 'strips 2 and 3',
        min: 0.05,
        max: 500,
        step: 0.05,
        unit: 'ms',
        curve: 'log',
        help: 'How long strip 2’s cord and its circuit take. The stock times are deliberately not multiples of each other: set two strips to the same number and they lock into one loud loop, and everything interesting here is the two of them refusing to.',
      },
      {
        key: 'fb2Tone',
        label: 'Strip 2 tilt',
        part: 'strips 2 and 3',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        split: { at: 0 },
        reads: v =>
          v === 0
            ? 'flat'
            : `${Math.abs(v).toFixed(2)} ${v < 0 ? 'dark' : 'bright'}`,
        help: 'Strip 2’s own tilt. Tilt the strips apart and they scream in different registers — a top-end shriek over a bottom-end growl, off one bus.',
      },
      {
        key: 'fb3Amt',
        label: 'Strip 3',
        part: 'strips 2 and 3',
        min: 0,
        max: 1.5,
        step: 0.01,
        unit: '',
        help: 'The third send and return. Two loops beat; three cross-fed loops stop being predictable at all, which is what Cross is for.',
      },
      {
        key: 'fb3Ms',
        label: 'Strip 3 time',
        part: 'strips 2 and 3',
        min: 0.05,
        max: 500,
        step: 0.05,
        unit: 'ms',
        curve: 'log',
        help: 'How long strip 3’s cord takes. Stock it is the long one — a squeal, a flutter and an echo on the same bus.',
      },
      {
        key: 'fb3Tone',
        label: 'Strip 3 tilt',
        part: 'strips 2 and 3',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        split: { at: 0 },
        reads: v =>
          v === 0
            ? 'flat'
            : `${Math.abs(v).toFixed(2)} ${v < 0 ? 'dark' : 'bright'}`,
        help: 'Strip 3’s own tilt.',
      },
      {
        key: 'fbRails',
        label: 'Rails',
        part: 'the return amps',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How hard the return amps hit their supply. At rest they saturate warmly; wound up the wave meets the rail and squares off flat — the difference between a loop that howls and one that buzzsaws.',
      },
      {
        key: 'fbAsym',
        label: 'Rail balance',
        part: 'the return amps',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        split: { at: 0 },
        reads: v =>
          v === 0
            ? 'matched'
            : `${Math.abs(v).toFixed(2)} ${v < 0 ? 'low rail' : 'high rail'}`,
        help: 'How far apart the two supplies are. Squaring off on one half before the other puts out even harmonics — an octave under the squeal rather than more of it — and leaves dc behind.',
      },
      {
        key: 'fbSlew',
        label: 'Slew',
        part: 'the return amps',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How slow the return amps are. Asked for an edge faster than they can swing, they put out a ramp. On one tone that is dull distortion; on three squeals it is hash with no harmonic structure at all.',
      },
      {
        key: 'fbSag',
        label: 'Supply',
        part: 'the return amps',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far the return amps pull their own rail down. They scream, take out their own supply, and have to find somewhere quieter to run — current goes in milliseconds, back over a third of a second. Same rail the toy is on.',
      },
      {
        key: 'fbBlock',
        label: 'Blocking',
        part: 'the return amps',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The coupling cap driven past its rails: charge walks the bias to cutoff, the stage stops conducting, and the loop dies. Then the charge drains and it rebuilds — over and over, at a rate nothing here controls.',
      },
    ],
  },
]
