import type { Group } from './types'

export const MASTER_GROUPS: Group[] = [
  {
    name: 'Brownout',
    place: 'Master',
    sliders: [
      {
        key: 'brownAmt',
        label: 'Sag',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The master supply sags under load: loud passages collapse and pump like a dying battery.',
      },
      {
        key: 'brownRate',
        label: 'Dropouts',
        min: 0,
        max: 50,
        step: 0.5,
        unit: 'Hz',
        help: 'Random full dropouts — a loose power jack.',
      },
      {
        key: 'brownCrackle',
        label: 'Crackle',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Crackle injected in proportion to how hard the supply is working.',
      },
      {
        key: 'humLevel',
        label: 'Ground hum',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'A ground loop: mains fundamental plus rectifier buzz, louder as the supply strains, with the ripple wobbling the rail.',
      },
      {
        key: 'humHz',
        label: 'Mains',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['50 Hz', '60 Hz'],
        help: 'Which grid you’re plugged into.',
      },
    ],
  },
  {
    name: 'Output',
    place: 'Master',
    sliders: [
      {
        key: 'outGain',
        label: 'Gain',
        min: -60,
        max: 12,
        step: 0.5,
        unit: 'dB',
        help: 'Master gain before the safety clipper and limiter.',
      },
    ],
  },
  {
    name: 'Ageing',
    place: 'Master',
    sliders: [
      {
        key: 'heatAmt',
        label: 'Heat',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far the board’s own temperature drags its thresholds. Nothing on the panel reads it out: it climbs off whatever you are making it dissipate — a screaming loop, a starved rail, a pedal wound up — over about a minute, and falls back over two. The rail holds less, the watchdog trips sooner, the capstan wanders further and a starving oscillator takes longer to come back. Turned up, the board three minutes in is not the one that booted, and it never settles anywhere, because where it goes depends on what you played on the way.',
      },
      {
        key: 'faultCluster',
        label: 'Fault clustering',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Whether faults arrive on a flat rate or in bursts. At zero every dropout, spark, glitch and counter slip rolls its own dice at a constant rate, which the ear averages into a texture within a second. Wound up, each fault leaves the next one likelier for a couple of seconds — the same number of faults, redistributed into a minute of nothing and then a dozen at once, the way a joint that has started arcing goes on arcing.',
      },
      {
        key: 'jointChatter',
        label: 'Dry joints',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How intermittent the solder is under the bend slots. A cold joint opens and the stage on that slot is simply not in the path for a moment — no dry/wet fade, a click on the way out and another on the way back, and whatever it was ringing left mid-ring. What drops out is whatever you patched there, so the board rewrites its own signal path while it plays.',
      },
      {
        key: 'relayRate',
        label: 'Re-solder',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How often the board re-solders itself: two bend slots swap places, or the feedback return jumps to a different pin. Nothing about the settings changes — every bend keeps the values you gave it, and the order and the routing are what move. The one roll on the board that changes topology rather than numbers, and the only one that does it without your hand on anything.',
      },
      {
        key: 'couple',
        label: 'Cross-coupling',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Wires the loop’s own brightness against its supply. High-frequency energy in the chain opens the screech filter’s resonance and drives the shifter harder — which makes more of it — while the same energy drags the rail down, which shuts it back up. Two couplings of opposite sign on different time constants never find a resting point, so a squeal hunts around a pitch instead of settling on one, with no LFO anywhere near it.',
      },
    ],
  },
]
