import type { Group } from './types'

export const MASTER_GROUPS: Group[] = [
  {
    name: 'Brownout',
    place: 'Master',
    sliders: [
      {
        key: 'brownAmt',
        label: 'Sag',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        shy: true,
        help: 'The master supply sags under load: loud passages collapse and pump like a dying battery.',
      },
      {
        key: 'brownRate',
        label: 'Dropouts',
        min: 0,
        max: 50,
        step: 0.5,
        unit: 'Hz',
        shy: true,
        help: 'Random full dropouts — a loose power jack.',
      },
      {
        key: 'brownCrackle',
        label: 'Crackle',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        shy: true,
        help: 'Crackle injected in proportion to how hard the supply is working.',
      },
      {
        key: 'humLevel',
        label: 'Ground hum',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'A ground loop: mains fundamental plus rectifier buzz, louder as the supply strains, with the ripple wobbling the rail.',
      },
      {
        key: 'humHz',
        label: 'Mains',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['50 Hz', '60 Hz'],
        help: 'Which grid you’re plugged into.',
      },
    ],
  },
  {
    name: 'Output',
    place: 'Master',
    sliders: [
      {
        key: 'outGain',
        label: 'Gain',
        min: -60,
        max: 12,
        step: 0.5,
        unit: 'dB',
        help: 'Master gain before the safety clipper and limiter.',
      },
      {
        key: 'deckSpeed',
        lane: 'deck speed',
        label: 'Varispeed',
        min: 0,
        max: 2,
        step: 0.001,
        unit: '×',
        curve: 'symlog',
        // ×1 is not a number you read, it is the machine not doing anything
        // — and 0 is a stopped tape rather than a very slow one. Both want
        // saying in words where the eye already is.
        reads: v =>
          v === 0
            ? 'stopped'
            : v === 1
              ? '×1'
              : `${v.toFixed(3)}× ${v < 1 ? 'slow' : 'fast'}`,
        split: {
          at: 1,
          names: { below: 'slow', above: 'fast', mid: '×1' },
          detent: true,
          // A capstan trimmer is a ten percent adjustment; the rest of this
          // travel is a transposer wearing its clothes. Marking ×0.9/×1.1 puts
          // half of each side's throw in that ten percent, which is where a
          // hand riding the deck actually works.
          normal: 0.9,
        },
        help: 'The capstan trimmer on the deck the whole instrument comes off. Everything on the board is printed to it — the tape machine and the output limiter included — and this is the speed you are hearing that printing played back at: pitch, tempo, every envelope, every delay time and every reverb tail stretch together, and nothing upstream knows it is running slow. A wire from the bay lands here too, so one LFO wobbles the whole board at once. At the stop the deck stops.',
      },
      {
        key: 'deckInertia',
        label: 'Motor weight',
        min: 0,
        max: 3,
        step: 0.01,
        unit: 's',
        curve: 'log',
        help: 'How much weight the deck’s motor carries. Varispeed says where the trimmer is set; this is how long the platter takes to arrive, so winding the knob to the stop is a tape stop that runs down over that long and letting it back up is a spin-up rather than a cut.',
      },
    ],
  },
  {
    name: 'Board parts',
    place: 'Master',
    sliders: [
      {
        key: 'chipDecouple',
        label: 'Timing pin',
        min: 0.2,
        max: 2000,
        step: 0.1,
        unit: 'ms',
        curve: 'log',
        help: 'The decoupling cap on the oscillator, as the time it averages the rail over. It decides which sags the timebase notices: at the stock 120 ms a chord sags without the beat stumbling. Scrape it off and every note trips the tune.',
      },
      {
        key: 'chipWatchdog',
        label: 'Watchdog',
        min: 0.2,
        max: 0.6,
        step: 0.005,
        unit: 'V',
        help: 'Where the reset chip decides the supply has failed. At the bottom the reboot is the last thing to happen on the way down and you hear the whole dive first; at the top the toy resets while it could still run, so the tune just restarts.',
      },
      {
        key: 'chipLatchHold',
        label: 'Latch hold',
        min: 0.01,
        max: 0.19,
        step: 0.005,
        unit: 'V',
        help: 'Where a jammed die and its supply come to rest against each other — a latch needs some rail left to hold itself in, which is why the note screams instead of stopping. Low is a growl under the floor, high a shriek that nearly makes a note.',
      },
      {
        key: 'chipClipBite',
        label: 'Clip bite',
        min: 0,
        max: 4,
        step: 0.05,
        unit: '',
        shy: true,
        help: 'How hard bare metal chokes the supply when it lands. Low is a lean on the pitch; high is a full brownout on every touch. Crank it and each contact trips the watchdog, so Clip chatter becomes a reboot machine.',
      },
      {
        key: 'chipClipHold',
        label: 'Clip dwell',
        min: 3,
        max: 800,
        step: 1,
        unit: 'ms',
        curve: 'log',
        help: 'How long one touch lasts on average, never twice the same. Short, the rail has not finished leaving before the metal lifts, so you get the top of the dive over and over; long, every touch arrives at the bottom and sits there.',
      },
      {
        key: 'chipClipCharge',
        label: 'Clip charge',
        min: 2,
        max: 400,
        step: 1,
        unit: '/s',
        curve: 'log',
        help: 'How fast the cap the clip found charges through the contact — the rate the clock leaves at while the metal is down. This is the dive itself: slow is a swoop you hear travel, fast is a step you land on. The Reservoir slows it further, so the two multiply.',
      },
      {
        key: 'chipClipRelease',
        label: 'Clip release',
        min: 2,
        max: 2000,
        step: 1,
        unit: '/s',
        curve: 'log',
        help: 'How fast the clock comes back when the metal lifts — a disconnection rather than a discharge, and stock ten times the charge rate. That asymmetry is why the bend reads as a dive; even it up and dives turn into a warble.',
      },
      {
        key: 'chipDragOct',
        label: 'Clock drag',
        min: 0,
        max: 8,
        step: 0.05,
        unit: 'oct',
        help: 'How far the cap on the timing pin can divide the clock — four octaves stock, enough to put the melody under the bottom of its own keyboard. The whole timebase goes with it, so tune, tempo and envelopes dive together.',
      },
      {
        key: 'chipSpread',
        label: 'Part spread',
        min: 0,
        max: 4,
        step: 0.01,
        unit: '×',
        help: 'How far apart the four output stages came out of the bin. At zero a chord on a dying toy dies in lockstep; wound up each voice browns out at its own voltage, so the chord detunes against itself and comes apart a note at a time.',
      },
      {
        key: 'chipMixDrive',
        label: 'Mixer drive',
        min: 0.02,
        max: 3,
        step: 0.01,
        unit: '',
        curve: 'log',
        help: 'The headroom in the one small output stage every key voice runs through — why a chord leans rather than coming out four times louder. High squares off on two notes, so playing harder changes the timbre, not the level.',
      },
    ],
  },
  {
    name: 'Wear',
    place: 'Master',
    sliders: [
      {
        key: 'heatAmt',
        label: 'Heat',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far the board’s own temperature drags its thresholds. It climbs over a minute off whatever you are making it dissipate: the rail holds less, the watchdog trips sooner, the capstan wanders further. Nothing reads it out.',
      },
      {
        key: 'faultCluster',
        label: 'Fault clustering',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Whether faults arrive at a flat rate or in bursts. At zero the ear averages them into a texture; wound up each one leaves the next likelier, so the same number redistribute into a minute of nothing and then a dozen at once.',
      },
      {
        key: 'couple',
        label: 'Cross-coupling',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Wires the loop’s brightness against its supply: brightness opens the resonance and drives the shifter harder, and the same energy drags the rail down and shuts it back up. Two couplings of opposite sign never settle, so a squeal hunts.',
      },
      {
        key: 'jointChatter',
        label: 'Dry joints',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How intermittent the solder is under the bend slots. A cold joint drops its stage out of the path outright — a click on the way out, another on the way back, and whatever was ringing left mid-ring. The board rewrites its own signal path while it plays.',
      },
      {
        key: 'relayRate',
        label: 'Re-solder',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How often the board re-solders itself: two bend slots swap places, or the feedback return jumps to a different pin. Every bend keeps the values you gave it — the order and the routing are what move. The one roll that changes topology rather than numbers.',
      },
    ],
  },
]
