import type { Group } from './types'

export const MASTER_GROUPS: Group[] = [
  {
    name: 'Brownout',
    place: 'Master',
    sliders: [
      {
        key: 'brownAmt',
        label: 'Sag',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The master supply sags under load: loud passages collapse and pump like a dying battery.',
      },
      {
        key: 'brownRate',
        label: 'Dropouts',
        min: 0,
        max: 50,
        step: 0.5,
        unit: 'Hz',
        help: 'Random full dropouts — a loose power jack.',
      },
      {
        key: 'brownCrackle',
        label: 'Crackle',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        shy: true,
        help: 'Crackle injected in proportion to how hard the supply is working.',
      },
      {
        key: 'humLevel',
        label: 'Ground hum',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'A ground loop: mains fundamental plus rectifier buzz, louder as the supply strains, with the ripple wobbling the rail.',
      },
      {
        key: 'humHz',
        label: 'Mains',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['50 Hz', '60 Hz'],
        help: 'Which grid you’re plugged into.',
      },
    ],
  },
  {
    name: 'Output',
    place: 'Master',
    sliders: [
      {
        key: 'outGain',
        label: 'Gain',
        min: -60,
        max: 12,
        step: 0.5,
        unit: 'dB',
        help: 'Master gain before the safety clipper and limiter.',
      },
    ],
  },
  {
    name: 'Board parts',
    place: 'Master',
    sliders: [
      {
        key: 'chipDecouple',
        label: 'Timing pin',
        min: 0.2,
        max: 2000,
        step: 0.1,
        unit: 'ms',
        curve: 'log',
        help: 'The decoupling cap on the oscillator, as the time it averages the rail over. One RC oscillator clocks the whole chip — pitch, tempo and envelopes are all it, divided — so they cannot come apart. What this decides is which sags the timebase notices. At the stock 120 ms a single note’s current is gone before the clock sees it, which is why a chord sags without the beat stumbling, and only a sag that outlasts it takes the tempo down. Scrape the cap off and nothing is averaged: every note in a chord trips the tune. Wind it up and the timebase stops hearing the rail at all, and the pitch dives while the tempo holds — which no chip with one oscillator in it can do, and is the sound of a board somebody has already been at.',
      },
      {
        key: 'chipWatchdog',
        label: 'Watchdog',
        min: 0.2,
        max: 0.6,
        step: 0.005,
        unit: 'V',
        help: 'Where the reset chip decides the supply has failed. It cannot go under the voltage the die stops running at — a watchdog watches for the chip failing, so the bottom of this knob is that point and not a millivolt lower. Sitting there, the reboot is the last thing that happens on the way down and you hear the whole dive first. Up at the top the toy is being reset while it is still perfectly able to run: no sag ever gets going, and the tune simply restarts and restarts.',
      },
      {
        key: 'chipLatchHold',
        label: 'Latch hold',
        min: 0.01,
        max: 0.19,
        step: 0.005,
        unit: 'V',
        help: 'Where a jammed die and its supply come to rest against each other. A latch is a short the chip cannot let go of, and it needs some rail left to hold itself in — so the two settle and sit there, which is why the note screams instead of stopping. Down near nothing that is a growl under the floor; up near the voltage the chip gives up at it is a shriek that nearly resolves into a note. Whether it latches at all is the toy’s own Latch-up knob; this is what it sounds like when it does.',
      },
      {
        key: 'chipClipBite',
        label: 'Clip bite',
        min: 0,
        max: 4,
        step: 0.05,
        unit: '',
        help: 'How hard bare metal chokes the supply when it lands. A paperclip is not a switch and it is not a short: it bounces, it is held in fingers that move, and it lands through skin and oxide. Low, it is a lean on the pitch. High, it is a full brownout on every touch. Crank it and each contact takes the rail past the watchdog, so Clip chatter becomes a reboot machine.',
      },
      {
        key: 'chipClipHold',
        label: 'Clip dwell',
        min: 3,
        max: 800,
        step: 1,
        unit: 'ms',
        curve: 'log',
        help: 'How long one touch lasts on average. Never twice the same — the spread moves with the mean, so it is a hand at every setting rather than a metronome at one end. Short enough and the rail has not finished leaving before the metal lifts, so you get the top of the dive over and over; long enough and every touch arrives all the way at the bottom and sits there.',
      },
      {
        key: 'chipClipCharge',
        label: 'Clip charge',
        min: 2,
        max: 400,
        step: 1,
        unit: '/s',
        curve: 'log',
        help: 'How fast the cap the clip found charges through the contact — the rate the clock leaves at while the metal is down. This is the dive itself: slow is a swoop you hear travel, fast is a step you land on. The Reservoir slows it further, so the two multiply.',
      },
      {
        key: 'chipClipRelease',
        label: 'Clip release',
        min: 2,
        max: 2000,
        step: 1,
        unit: '/s',
        curve: 'log',
        help: 'And how fast the clock comes back when the metal lifts, which is not a discharge but a disconnection — the cap leaves the circuit altogether and the node is left with its own resistor and the picofarads inside the die. Stock, that is ten times the charge rate, and the asymmetry is the whole reason the bend reads as a dive: the falls are what there is time to hear. Bring this down onto Clip charge and the two ends take the same time, and dives turn into a warble.',
      },
      {
        key: 'chipDragOct',
        label: 'Clock drag',
        min: 0,
        max: 8,
        step: 0.05,
        unit: 'oct',
        help: 'How far the cap on the timing pin can divide the clock. Starving the rail is worth a fraction of an octave before the chip stops running at all; hanging a capacitor off the oscillator divides it, and dividing has no such limit. Four octaves is stock — enough to put the melody under the bottom of its own keyboard and turn its squares into something you feel rather than hear. The whole timebase goes with it, so the tune, the tempo and the envelopes dive together. How much of it you get is Clip on clock; this is how deep the part you hung there goes.',
      },
      {
        key: 'chipSpread',
        label: 'Part spread',
        min: 0,
        max: 4,
        step: 0.01,
        unit: '×',
        help: 'How far apart the four output stages came out of the bin. Every voice shares the one supply but has its own amplifier, so on a starving rail each browns out at its own voltage and sags by its own amount — which is why a chord on a dying toy detunes against itself and collapses raggedly, a note at a time. At zero the four parts are identical and a chord dies in lockstep, cleanly, all at once; wound up they scatter, and the chord comes apart over a second with the last voice still going.',
      },
      {
        key: 'chipMixDrive',
        label: 'Mixer drive',
        min: 0.02,
        max: 3,
        step: 0.01,
        unit: '',
        curve: 'log',
        help: 'The headroom in the one small output stage every key voice runs through. It is why a chord leans rather than coming out four times louder. Low is a clean summing amp with room for all four; high is a stage that squares off on two notes, so playing harder changes the timbre instead of the level — and the harmonics that makes are what the rest of the chain has to work with.',
      },
    ],
  },
  {
    name: 'Wear',
    place: 'Master',
    sliders: [
      {
        key: 'heatAmt',
        label: 'Heat',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far the board’s own temperature drags its thresholds. Nothing on the panel reads it out: it climbs off whatever you are making it dissipate — a screaming loop, a starved rail, a pedal wound up — over about a minute, and falls back over two. The rail holds less, the watchdog trips sooner, the capstan wanders further and a starving oscillator takes longer to come back. Turned up, the board three minutes in is not the one that booted, and it never settles anywhere, because where it goes depends on what you played on the way.',
      },
      {
        key: 'faultCluster',
        label: 'Fault clustering',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Whether faults arrive on a flat rate or in bursts. At zero every dropout, spark, glitch and counter slip rolls its own dice at a constant rate, which the ear averages into a texture within a second. Wound up, each fault leaves the next one likelier for a couple of seconds — the same number of faults, redistributed into a minute of nothing and then a dozen at once, the way a joint that has started arcing goes on arcing.',
      },
      {
        key: 'jointChatter',
        label: 'Dry joints',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How intermittent the solder is under the bend slots. A cold joint opens and the stage on that slot is simply not in the path for a moment — no dry/wet fade, a click on the way out and another on the way back, and whatever it was ringing left mid-ring. What drops out is whatever you patched there, so the board rewrites its own signal path while it plays.',
      },
      {
        key: 'relayRate',
        label: 'Re-solder',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How often the board re-solders itself: two bend slots swap places, or the feedback return jumps to a different pin. Nothing about the settings changes — every bend keeps the values you gave it, and the order and the routing are what move. The one roll on the board that changes topology rather than numbers, and the only one that does it without your hand on anything.',
      },
      {
        key: 'couple',
        label: 'Cross-coupling',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Wires the loop’s own brightness against its supply. High-frequency energy in the chain opens the screech filter’s resonance and drives the shifter harder — which makes more of it — while the same energy drags the rail down, which shuts it back up. Two couplings of opposite sign on different time constants never find a resting point, so a squeal hunts around a pitch instead of settling on one, with no LFO anywhere near it.',
      },
    ],
  },
]
