import type { ControlKey } from '../../controls'
import type { Group } from './types'

export const PATCH_GROUPS: Group[] = [
  {
    name: 'Patch bay',
    place: 'Patch',
    sliders: [
      {
        key: 'modLfoHz',
        label: 'LFO rate',
        min: 0.02,
        max: 40,
        step: 0.01,
        unit: 'Hz',
        curve: 'log',
        help: 'The bay’s own oscillator, free-running. Slow is a sweep, fast is a buzz through whatever it is wired to.',
      },
      {
        key: 'modLfoShape',
        label: 'LFO shape',
        min: 0,
        max: 5,
        step: 1,
        unit: '',
        choices: ['sine', 'ramp', 'square', 'S&H', 'chaos', 'drunk'],
        help: 'Sine glides, ramp saws, square jumps, S&H holds a fresh random step each cycle. The last two never come round again: chaos folds along a Rössler band, passing near where it has been without ever landing there, and drunk is a bounded walk that reflects off the ends of its travel. Rate still sets roughly how fast, but nothing about the next cycle is in the last one.',
      },
      ...[0, 1].flatMap(i => [
        {
          key: `mod${i}Src` as ControlKey,
          label: `Wire ${i + 1} from`,
          min: 0,
          max: 11,
          step: 1,
          unit: '',
          choices: [
            'off',
            'LFO',
            'supply',
            'envelope',
            'mic',
            'body X',
            'body Y',
            'fb bus',
            'ROM step',
            'drum hit',
            'key hit',
            'heat',
          ],
          help: 'What the wire picks up: the bay LFO, the sag on the dying supply, the output envelope, the mic, either axis of the body pad, the feedback bus itself, the chip’s sequencer ramping across each ROM step, either trigger line — a drum hit or a note struck, which fall from the hit rather than sweeping — or how hot the board has got, which is the slowest thing on it and the one that never comes back to where it started.',
        },
        {
          key: `mod${i}Dest` as ControlKey,
          label: `Wire ${i + 1} to`,
          min: 0,
          max: 14,
          step: 1,
          unit: '',
          choices: [
            'filt cut',
            'ring car',
            'comb pitch',
            'crush rate',
            'chip clock',
            'retrigger',
            'tape speed',
            'glitch',
            'fb amount',
            'stomp drive',
            'shift Hz',
            'bit depth',
            'drum cross',
            'wire 1 depth',
            'wire 2 depth',
          ],
          help: 'Where the other end is soldered. Pitch-like destinations move in octaves; glitch and feedback amount just add. The last two land on the other wire’s own depth, so one wire decides how hard the other pushes — two wires that modulate each other stop being two modulations and start being one that neither of them wrote.',
        },
        {
          key: `mod${i}Depth` as ControlKey,
          label: `Wire ${i + 1} depth`,
          min: -1,
          max: 1,
          step: 0.01,
          unit: '',
          help: 'How hard the wire pushes. Negative flips it — the supply dying can drag a pitch up as easily as down.',
        },
      ]),
    ],
  },
  {
    name: 'Trigger patch',
    place: 'Patch',
    sliders: [
      {
        key: 'trigToKeys',
        label: 'Kit fires keys',
        min: 0,
        max: 7,
        step: 1,
        unit: '',
        choices: [
          'off',
          'kick',
          'snare',
          'hat',
          'clap',
          'tom',
          'bell',
          'any hit',
        ],
        help: 'Bridges one of the kit’s trigger lines onto the keyboard’s gate, so a drum hit strikes a note. It strikes a key voice rather than the melody, so it sounds whether or not the demo song is running.',
      },
      {
        key: 'trigKeysNote',
        label: 'and plays',
        min: 0,
        max: 3,
        step: 1,
        unit: '',
        choices: ['the note', 'the next step', 'any step', 'the chord'],
        help: 'What the hit strikes. The next step walks the ROM one place per hit, so the pattern clocks the tune and the kick decides where the melody goes; any step picks off the ROM at random; the chord takes a tone off the accompaniment’s triad.',
      },
      {
        key: 'trigToDrum',
        label: 'Keys fire kit',
        min: 0,
        max: 8,
        step: 1,
        unit: '',
        choices: [
          'off',
          'kick',
          'snare',
          'hat',
          'clap',
          'tom',
          'bell',
          'whole kit',
          'the step',
        ],
        help: 'The wire back: the keyboard’s gate onto the kit’s trigger line, so every note it strikes hits the kit whether the pattern is running or not. The step hands the grid to your hands — a key fires whichever column the sequencer is on. Solder both wires and the two boxes play each other.',
      },
    ],
  },
  {
    name: 'Body contact',
    place: 'Patch',
    sliders: [
      {
        key: 'bodyX',
        label: 'Contact X',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Left–right position on the contact pad. Wire it to something in the bay, then play the pad.',
      },
      {
        key: 'bodyY',
        label: 'Contact Y',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Top–bottom position on the contact pad — how hard you are leaning on the contacts.',
      },
    ],
  },
]
