import type { ControlKey } from '../../controls'
import { VOICE_LABELS } from '../../drums'
import type { Group } from './types'

export const PATCH_GROUPS: Group[] = [
  {
    name: 'Patch bay',
    place: 'Patch',
    // The picture drawn above these rows, in PatchBay: a box-to-box lead per
    // wire, so the four rows of source/destination pairs read as a bay
    // rather than as forty-nine choices to cross-reference by hand.
    editor: { kind: 'patch' },
    sliders: [
      {
        key: 'modLfoHz',
        label: 'LFO rate',
        min: 0.02,
        max: 400,
        step: 0.01,
        unit: 'Hz',
        curve: 'log',
        help: 'The bay’s own oscillator, free-running. Slow is a sweep; fast, wired onto a pitch, is modulation rather than vibrato. Chaos is the exception — it runs out of speed around 160 Hz.',
      },
      {
        key: 'modLfoShape',
        label: 'LFO shape',
        min: 0,
        max: 5,
        step: 1,
        unit: '',
        choices: ['sine', 'ramp', 'square', 'S&H', 'chaos', 'drunk'],
        help: 'Sine glides, ramp saws, square jumps, S&H holds a fresh random step each cycle. Chaos and drunk never come round again — rate sets roughly how fast, but nothing about the next cycle is in the last.',
      },
      ...[0, 1, 2, 3].flatMap(i => [
        {
          key: `mod${i}Src` as ControlKey,
          label: `Wire ${i + 1} from`,
          min: 0,
          max: 11,
          step: 1,
          unit: '',
          choices: [
            'off',
            'LFO',
            'supply',
            'envelope',
            'mic',
            'body X',
            'body Y',
            'fb bus',
            'ROM step',
            'drum hit',
            'key hit',
            'heat',
          ],
          help: 'What the wire picks up: the bay LFO, the sag on the dying supply, the output envelope, the mic, either axis of the body pad, the feedback bus, the chip’s sequencer ramping across each ROM step, either trigger line, or how hot the board has got.',
        },
        {
          key: `mod${i}Dest` as ControlKey,
          label: `Wire ${i + 1} to`,
          min: 0,
          max: 24,
          step: 1,
          unit: '',
          choices: [
            'filt cut',
            'ring car',
            'comb pitch',
            'crush rate',
            'chip clock',
            'retrigger',
            'tape speed',
            'glitch',
            'fb amount',
            'stomp drive',
            'shift Hz',
            'bit depth',
            'drum cross',
            'starve',
            'drum tune',
            'verb decay',
            'delay time',
            'wire 1 depth',
            'wire 2 depth',
            'wire 3 depth',
            'wire 4 depth',
            'echo time',
            'tape speed (sampler)',
            'loop slide',
            'loop span',
          ],
          help: 'Where the other end is soldered. Pitch-like destinations move in octaves; glitch and feedback amount just add. Starve is the supply the toy runs on rather than a stage on it, so a wire there reaches everything at once. Four land on a wire’s own depth, so one wire decides how hard another pushes.',
        },
        {
          key: `mod${i}Depth` as ControlKey,
          label: `Wire ${i + 1} depth`,
          min: -1,
          max: 1,
          step: 0.01,
          unit: '',
          split: { at: 0 },
          reads: (v: number) =>
            v === 0
              ? 'off'
              : `${Math.abs(v).toFixed(2)} ${v < 0 ? 'flipped' : 'straight'}`,
          help: 'How hard the wire pushes. Negative flips it — the supply dying can drag a pitch up as easily as down.',
        },
      ]),
    ],
  },
  {
    name: 'Trigger patch',
    place: 'Patch',
    sliders: [
      {
        key: 'trigToKeys',
        label: 'Kit fires keys',
        min: 0,
        max: VOICE_LABELS.length + 1,
        step: 1,
        unit: '',
        choices: ['off', ...VOICE_LABELS, 'any hit'],
        help: 'Bridges one of the kit’s trigger lines onto the keyboard’s gate, so a drum hit strikes a note. It strikes a key voice rather than the melody, so it sounds whether or not the demo song is running.',
      },
      {
        key: 'trigKeysNote',
        label: 'and plays',
        min: 0,
        max: 3,
        step: 1,
        unit: '',
        choices: ['the note', 'the next step', 'any step', 'the chord'],
        help: 'What the hit strikes. The next step walks the ROM one place per hit, so the pattern clocks the tune and the kick decides where the melody goes; any step picks off the ROM at random; the chord takes a tone off the accompaniment’s triad.',
      },
      {
        key: 'trigToDrum',
        label: 'Keys fire kit',
        min: 0,
        max: VOICE_LABELS.length + 2,
        step: 1,
        unit: '',
        choices: ['off', ...VOICE_LABELS, 'whole kit', 'the step'],
        help: 'The keyboard’s gate onto the kit’s trigger line: every note you strike hits the kit, pattern running or not. Solder both wires and the two boxes play each other.',
      },
    ],
  },
  {
    name: 'Body contact',
    place: 'Patch',
    sliders: [
      {
        key: 'bodyX',
        label: 'Contact X',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Left–right position on the contact pad. Wire it to something in the bay, then play the pad.',
      },
      {
        key: 'bodyY',
        label: 'Contact Y',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Top–bottom position on the contact pad — how hard you are leaning on the contacts.',
      },
    ],
  },
]
