import { ECHO_MODE, ECHO_MODE_NAMES } from '../../dsp/stages/echo'
import type { Group } from './types'

export const PEDAL_GROUPS: Group[] = [
  {
    name: 'Stompbox',
    place: 'Pedals',
    sliders: [
      {
        key: 'stompCircuit',
        label: 'Circuit',
        min: 0,
        max: 5,
        step: 1,
        unit: '',
        choices: ['screamer', 'rat', 'muff', 'germanium', 'octave', 'gate'],
        help: 'Which dirt box is on the board. Screamer clips inside the feedback loop so the dry note walks under it; rat clips to ground behind a slew-limited op-amp; muff is two clipping stages and a scooped tone stack that never decays; germanium is the lopsided one whose bias rides down on the signal; octave rectifies into a ringing transformer; gate is misbiased to the edge of cutoff.',
      },
      {
        key: 'stompDrive',
        label: 'Drive',
        min: 0,
        max: 60,
        step: 0.5,
        unit: 'dB',
        help: 'Gain into the clipping stage — and how hard the pedal leans on its own battery.',
      },
      {
        key: 'stompTone',
        label: 'Tone',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Each circuit’s tone control is a different network, so the knob means something different on each: a low-pass on most, the scoop blend on the muff, where the transformer rings on the octave, and what pitch the starved one squeals at.',
      },
      {
        key: 'stompBias',
        label: 'Bias',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        split: { at: 0 },
        help: 'Shifts the clipper off centre — the classic starve mod. Quiet passages gate out, loud ones come through one-sided and full of even harmonics. On the gate circuit this is what walks it toward cutoff, so it shuts higher and higher up.',
      },
      {
        key: 'stompSag',
        label: 'Battery',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How dead the 9V is. The rail falls as the pedal works, so notes bloom and collapse; it also shares the board’s supply, so Starve and Brownout drag it down. On the gate circuit a flat battery is what makes it howl on its own.',
      },
      {
        key: 'stompLevel',
        label: 'Level',
        role: 'level',
        min: -24,
        max: 12,
        step: 0.5,
        unit: 'dB',
        help: 'Makeup gain out of the pedal.',
      },
      {
        key: 'stompMix',
        label: 'Mix',
        role: 'mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet — at zero the pedal is off the board.',
      },
    ],
  },
  {
    name: 'Tape delay',
    place: 'Pedals',
    sliders: [
      {
        key: 'delayMs',
        label: 'Time',
        min: 20,
        max: 4000,
        step: 1,
        unit: 'ms',
        curve: 'log',
        help: 'Delay time. Grabbing it drags the tape — pitch smears while it settles.',
      },
      {
        key: 'dlyFb',
        label: 'Feedback',
        min: 0,
        max: 1.5,
        step: 0.01,
        unit: '',
        help: 'Past 1.0 the repeats grow until the tape saturates — a runaway howl that darkens each lap.',
      },
      {
        key: 'wowDepthMs',
        label: 'Wow',
        min: 0,
        max: 50,
        step: 0.1,
        unit: 'ms',
        help: 'Slow speed wobble of the transport. A few ms is a tired capstan; fifty is a reel with something caught in it.',
      },
      {
        key: 'wowHz',
        label: 'Wow rate',
        min: 0.1,
        max: 8,
        step: 0.1,
        unit: 'Hz',
        help: 'How fast the wobble cycles.',
      },
      {
        key: 'flutter',
        label: 'Flutter',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Fast random speed jitter — worn pinch roller.',
      },
      {
        key: 'dlyToneHz',
        label: 'Tone',
        min: 500,
        max: 15000,
        step: 10,
        unit: 'Hz',
        curve: 'log',
        help: 'High-frequency loss per repeat — tape generation loss.',
      },
      {
        key: 'tapeBrake',
        label: 'Brake',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Drags the capstan. The transport has weight, so everything already on the tape sags in pitch on the way down and spins back up on release.',
      },
      {
        key: 'tapeMotorRail',
        label: 'Supply drag',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Wires the motor to the same dying supply as the toy: whenever the rail droops — Starve or Brownout Sag — the tape slows with it and the repeats dive.',
      },
      {
        key: 'dlyMix',
        label: 'Return',
        role: 'mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the echo comes back. It returns on its own fader rather than crossfading, so the dry stays where you set it and repeats only ever add — the board keeps its top end however far you push this.',
      },
    ],
  },
  {
    name: 'Delay pedal',
    place: 'Pedals',
    sliders: [
      {
        key: 'echoMode',
        label: 'Mode',
        min: 0,
        max: ECHO_MODE_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: ECHO_MODE_NAMES,
        help: 'Which delay the box is being. Standard is the plain one \u2014 flat repeats, and a time knob that crosses between two read heads rather than dragging one, so what is already in the buffer keeps its pitch while you move it. Analog is a bucket brigade, where the clock that sets the time is also what sets the bandwidth, so every step longer is a step muddier and the noise floor breathes behind the repeats. Reverse plays each window backwards. Modulate is the standard one with the head on an LFO, opposite ways on the two channels.',
      },
      {
        key: 'echoMs',
        label: 'Time',
        min: 20,
        max: 2000,
        step: 1,
        unit: 'ms',
        curve: 'log',
        help: 'Delay time. On standard and modulate the box crosses to the new one over 25 ms and nothing bends; on analog the clock has to walk there, so it smears like a tape would; on reverse the window relocks at the next seam, so it changes on the beat rather than under your hand.',
      },
      {
        key: 'echoFb',
        label: 'Feedback',
        min: 0,
        max: 1.1,
        step: 0.01,
        unit: '',
        help: 'How much of the repeat goes back in. The loop is linear until it runs out of headroom rather than saturating on the way \u2014 past unity it climbs to the wall and squares off there, which is a digital delay running away rather than a tape one.',
      },
      {
        key: 'echoToneHz',
        label: 'Tone',
        min: 800,
        max: 16000,
        step: 10,
        unit: 'Hz',
        curve: 'log',
        help: 'High cut in the loop, so each lap comes back darker than the last. On analog it stacks with whatever bandwidth the clock has left.',
      },
      {
        key: 'echoMod',
        label: 'Mod depth',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        needs: c => Math.round(c.echoMode) === ECHO_MODE.modulate,
        help: 'How far the read head swings, up to six milliseconds at 0.7 Hz. The two channels swing opposite ways, so the repeats widen as well as detune.',
      },
      {
        key: 'echoLevel',
        label: 'E. level',
        role: 'mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the echo comes back, and at zero the pedal is off the board. It returns on its own fader rather than crossfading, so the dry stays where you set it.',
      },
    ],
  },
  {
    name: 'Spring verb',
    place: 'Pedals',
    sliders: [
      {
        key: 'revDecayS',
        label: 'Decay',
        min: 0.1,
        max: 30,
        step: 0.1,
        unit: 's',
        curve: 'log',
        help: 'How long the springs ring. The top of the travel is longer than a tank of this size has any business ringing for — a half-minute tail is the room the springs are in, not the springs.',
      },
      {
        key: 'revToneHz',
        label: 'Tone',
        min: 500,
        max: 12000,
        step: 10,
        unit: 'Hz',
        curve: 'log',
        help: 'Damping inside the tank.',
      },
      {
        key: 'revBoing',
        label: 'Boing',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Spring dispersion — the drip and chirp on transients.',
      },
      {
        key: 'revMix',
        label: 'Return',
        role: 'mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the tank comes back. It returns on its own fader rather than crossfading, so the dry stays where you set it and the springs only ever add — the board keeps its front however far you push this.',
      },
      {
        key: 'revDryCut',
        label: 'Dry cut',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        shy: true,
        help: 'How much of the dry the tank swallows. At zero the springs are pure addition; wind it up and the board recedes into the tank behind them, and at full cut the tail is all that is left.',
      },
    ],
  },
]
