import { ECHO_MODE, ECHO_MODE_NAMES } from '../../dsp/stages/echo'
import { HEAD_CHOICES } from '../../dsp/stages/tapeDelay'

import type { Group } from './types'

export const PEDAL_GROUPS: Group[] = [
  {
    name: 'Stompbox',
    place: 'Pedals',
    sliders: [
      {
        key: 'stompCircuit',
        label: 'Circuit',
        min: 0,
        max: 5,
        step: 1,
        unit: '',
        choices: ['screamer', 'rat', 'muff', 'germanium', 'octave', 'gate'],
        help: 'Which dirt box is on the board. Screamer clips inside the loop, so the dry note walks under it; rat clips to ground behind a slewed op-amp; muff is two stages and a scooped tone stack; germanium is lopsided; octave rectifies; gate is misbiased to cutoff.',
      },
      {
        key: 'stompDrive',
        lane: 'stomp drive',
        label: 'Drive',
        min: 0,
        max: 60,
        step: 0.5,
        unit: 'dB',
        help: 'Gain into the clipping stage — and how hard the pedal leans on its own battery.',
      },
      {
        key: 'stompTone',
        label: 'Tone',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Each circuit’s tone control is a different network, so the knob means something different on each: a low-pass on most, the scoop blend on the muff, where the transformer rings on the octave, and what pitch the starved one squeals at.',
      },
      {
        key: 'stompBias',
        label: 'Bias',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        split: { at: 0 },
        help: 'Shifts the clipper off centre — the classic starve mod. Quiet passages gate out, loud ones come through one-sided and full of even harmonics. On the gate circuit this is what walks it toward cutoff, so it shuts higher and higher up.',
      },
      {
        key: 'stompSag',
        label: 'Battery',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How dead the 9V is. The rail falls as the pedal works, so notes bloom and collapse; it also shares the board’s supply, so Starve and Brownout drag it down. On the gate circuit a flat battery is what makes it howl on its own.',
      },
      {
        key: 'stompLevel',
        label: 'Level',
        role: 'level',
        min: -24,
        max: 12,
        step: 0.5,
        unit: 'dB',
        help: 'Makeup gain out of the pedal.',
      },
      {
        key: 'stompMix',
        label: 'Mix',
        role: 'mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Dry/wet — at zero the pedal is off the board.',
      },
    ],
  },
  {
    name: 'Tape delay',
    place: 'Pedals',
    sliders: [
      {
        key: 'delayMs',
        tap: true,
        lane: 'delay time',
        label: 'Time',
        min: 20,
        max: 4000,
        step: 1,
        unit: 'ms',
        curve: 'log',
        help: 'Delay time. Grabbing it drags the tape — pitch smears while it settles.',
      },
      {
        key: 'dlyHeads',
        label: 'Heads',
        min: 0,
        max: HEAD_CHOICES.length - 1,
        step: 1,
        unit: '',
        choices: [...HEAD_CHOICES],
        help: 'Which play heads are up. Three sit along the tape at one, two and three times the spacing the Time knob sets, so bringing up more than one is a rhythm off a single repeat — and every head goes round the same loop, so the feedback carries all of them.',
      },
      {
        key: 'dlyFb',
        label: 'Feedback',
        min: 0,
        max: 1.5,
        step: 0.01,
        unit: '',
        help: 'Past 1.0 the repeats grow until the tape saturates — a runaway howl that darkens each lap.',
      },
      {
        key: 'wowDepthMs',
        label: 'Wow',
        min: 0,
        max: 50,
        step: 0.1,
        unit: 'ms',
        help: 'Slow speed wobble of the transport. A few ms is a tired capstan; fifty is a reel with something caught in it.',
      },
      {
        key: 'wowHz',
        label: 'Wow rate',
        min: 0.1,
        max: 8,
        step: 0.1,
        unit: 'Hz',
        help: 'How fast the wobble cycles.',
      },
      {
        key: 'flutter',
        label: 'Flutter',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Fast random speed jitter — worn pinch roller.',
      },
      {
        key: 'dlyToneHz',
        label: 'Tone',
        min: 500,
        max: 15000,
        step: 10,
        unit: 'Hz',
        curve: 'log',
        help: 'High-frequency loss per repeat — tape generation loss.',
      },
      {
        key: 'dlyRingHz',
        label: 'Ring',
        min: 0.1,
        max: 8000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'A carrier multiplied into the tape before the repeats go back round, so every lap is shifted again and the tail builds a lattice rather than a copy. At unison with the note it fills in the even harmonics the toy’s square hasn’t got, a lap at a time; an octave under writes a new fundamental into the echoes only, while what you played stays clean; a few hertz puts each repeat a little further out of tune with the last.',
      },
      {
        key: 'dlyRing',
        label: 'Ring depth',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How much of the tap goes through the carrier. At zero the pedal is the plain tape machine; at the top every repeat is the full product, with the level the modulation took out handed back so the tail lasts as long as it did.',
      },
      {
        key: 'tapeBrake',
        lane: 'tape speed',
        label: 'Brake',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Drags the capstan. The transport has weight, so everything already on the tape sags in pitch on the way down and spins back up on release.',
      },
      {
        key: 'tapeMotorRail',
        label: 'Supply drag',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Wires the motor to the same dying supply as the toy: whenever the rail droops — Starve or Brownout Sag — the tape slows with it and the repeats dive.',
      },
      {
        key: 'dlySplice',
        label: 'Splice',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How bad the join in the loop is. The reel is five seconds of tape spliced end to end, and every time the join passes the heads the recording drops out for a moment and the head bumps — a click and a thump that go round the loop like anything else recorded on it. Braking the transport slows how often it comes round.',
      },
      {
        key: 'dlyErase',
        label: 'Erase',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How much the erase head misses. Up from nothing, whatever was on the tape a lap of the reel ago bleeds through under the new recording; at full the head is dead and the reel is sound on sound, every five seconds landing on top of the last until the tape saturates.',
      },
      {
        key: 'dlyMix',
        label: 'Echo level',
        role: 'mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Volume of the repeats on their own fader, added on top of the dry signal rather than crossfaded against it — turning this up never quietens the dry, and repeats only ever add on top of the board.',
      },
    ],
  },
  {
    name: 'Delay pedal',
    place: 'Pedals',
    sliders: [
      {
        key: 'echoMode',
        label: 'Mode',
        min: 0,
        max: ECHO_MODE_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: ECHO_MODE_NAMES,
        help: 'Which delay the box is being. Standard is flat repeats that keep their pitch as you move the time; hold lifts the record head on every hit — a drum, a key or an attack at the input — and goes round the window the time names, each lap the feedback quieter, until the next hit takes another; analog is a bucket brigade, so every step longer is a step muddier, and past a second a step grittier, as the clock folds what it cannot carry back into the band and whistles through; reverse plays each window backwards; modulate puts the head on an LFO.',
      },
      {
        key: 'echoMs',
        tap: true,
        lane: 'echo time',
        label: 'Time',
        min: 20,
        max: 2000,
        step: 1,
        unit: 'ms',
        curve: 'log',
        help: 'Delay time. Standard and modulate cross to the new one over 25 ms and nothing bends; analog has to walk there, so it smears like tape; reverse relocks at the next seam, so it changes on the beat; hold takes the new length at the next hit.',
      },
      {
        key: 'echoFb',
        label: 'Feedback',
        min: 0,
        max: 1.1,
        step: 0.01,
        unit: '',
        help: 'How much of the repeat goes back in. The loop is linear until it runs out of headroom rather than saturating on the way \u2014 past unity it climbs to the wall and squares off there, which is a digital delay running away rather than a tape one.',
      },
      {
        key: 'echoToneHz',
        label: 'Tone',
        min: 800,
        max: 16000,
        step: 10,
        unit: 'Hz',
        curve: 'log',
        help: 'High cut in the loop, so each lap comes back darker than the last. On analog it stacks with whatever bandwidth the clock has left.',
      },
      {
        key: 'echoMod',
        label: 'Mod depth',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        needs: c => Math.round(c.echoMode) === ECHO_MODE.modulate,
        help: 'How far the read head swings, up to six milliseconds at 0.7 Hz. The two channels swing opposite ways, so the repeats widen as well as detune.',
      },
      {
        key: 'echoLevel',
        label: 'E. level',
        role: 'mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Volume of the repeats on their own fader, added on top of the dry signal rather than crossfaded against it — turning this up never quietens the dry. At zero the pedal is off the board entirely.',
      },
    ],
  },
  {
    name: 'Spring verb',
    place: 'Pedals',
    sliders: [
      {
        key: 'revDecayS',
        lane: 'verb decay',
        label: 'Decay',
        min: 0.1,
        max: 30,
        step: 0.1,
        unit: 's',
        curve: 'log',
        help: 'How long the springs ring. The top of the travel is longer than a tank of this size has any business ringing for — a half-minute tail is the room the springs are in, not the springs.',
      },
      {
        key: 'revToneHz',
        label: 'Tone',
        min: 500,
        max: 12000,
        step: 10,
        unit: 'Hz',
        curve: 'log',
        help: 'Damping inside the tank.',
      },
      {
        key: 'revBoing',
        label: 'Boing',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Spring dispersion — the drip and chirp on transients.',
      },
      {
        key: 'revKick',
        label: 'Kick',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How easily the tank crashes — the springs thrown against the housing, the sound of kicking the amp. A hard hit at the input does it, and so does the kit, down its trigger line rather than through the mix. Up the travel every attack sets the springs clattering; low down only an accent gets through.',
      },
      {
        key: 'revMix',
        label: 'Reverb level',
        role: 'mix',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Volume of the spring tank on its own fader, added on top of the dry signal rather than crossfaded against it — turning this up never quietens the dry, so the springs only ever add on top of the board.',
      },
      {
        key: 'revDryCut',
        label: 'Dry cut',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        shy: true,
        help: 'Separately fades out the dry signal, independent of Reverb level above. At zero the dry passes through unchanged and the springs are pure addition; turned up it reduces the dry so the reverb takes over more of the mix; at full, the dry is silent and only the reverb tail remains.',
      },
    ],
  },
]
