import type { Controls } from '../../controls'
import { FAULT, FAULT_NAMES, lineNames } from '../../dsp/bus'
import { FM_EFFECT_NAMES } from '../../dsp/stages/fmEffects'
import {
  fallSecs,
  FM_LFO_NAMES,
  FM_VOICE_NAMES,
  MULT,
} from '../../dsp/stages/fmVoices'
import {
  ROM_ADDR_LINES,
  ROM_DATA_LINES,
  ROMS,
  TUNE_NAMES,
  YOURS,
} from '../../dsp/stages/roms'
import { ARP_MODES, SYNC_MODES } from '../../dsp/stages/toyChip'
import { NOTE_NAMES } from '../../notes'
import { SCALE_NAMES } from '../../scale'
import { ADDR_LINES, GRID_ROWS, N_DRUM_VOICES, VOICE_LABELS } from '../../drums'
import { CHOKE_NAMES } from '../../dsp/stages/toyDrum'
import { TUNE_ALL_STEP_KEYS } from '../../tune'

/** True while the chip is playing the memory rather than one of its own songs. */
const playingYours = (c: Controls) => Math.round(c.chipTune) === YOURS
import type { Group, SliderDef } from './types'

// The toy has no sync input, so locking it to the kit means picking the crystal
// speed at which the ROM's own steps divide into the kit's. Which multiple of
// that speed you want is a pitch decision as much as a timing one — the same
// knob is both — so it lands on the one nearest where the crystal already sits.
const LOCK_MULTIPLES = [
  1 / 8,
  1 / 6,
  1 / 4,
  1 / 3,
  1 / 2,
  2 / 3,
  1,
  3 / 2,
  2,
  3,
]

function lockToKit(c: Controls, def: SliderDef): number {
  const romHz = ROMS[Math.round(c.chipTune)]?.stepHz ?? 8
  const base = ((c.drumBpm / 60) * 4) / romHz
  const off = (v: number) => Math.abs(Math.log(v / c.chipClockX))
  const speeds = LOCK_MULTIPLES.map(m => base * m).filter(
    v => v >= def.min && v <= def.max,
  )
  // Nothing in range is a tempo the crystal cannot reach; the knob stays put.
  if (speeds.length === 0) return c.chipClockX
  return speeds.reduce((best, v) => (off(v) < off(best) ? v : best))
}

// The two panel controls the keyboard never had a button for, named in the
// units the register file counts in: a ratio is an index into the part's own
// multiplier table, and a decay is one of sixteen rates off the same divider
// everything else on the board runs on.
const RATIO_CHOICES = ['as patched', ...MULT.map(m => `${m}×`)]
const DECAY_CHOICES = [
  'as patched',
  ...Array.from({ length: 16 }, (_, i) => {
    const secs = fallSecs(15 - i)
    return secs < 0.1 ? `${Math.round(secs * 1000)} ms` : `${secs.toFixed(2)} s`
  }),
]

// Cut depth is how far through a trace the knife went, and the cut fault is the
// only one of the four that reads it — so the row waits until one of a chip's
// buses has a wire on it with that fault picked. One depth serves every bus on
// a chip, which is why it asks about all of them rather than one.
const cutOn =
  (...buses: [line: keyof Controls, fault: keyof Controls][]) =>
  (c: Controls) =>
    buses.some(([line, fault]) => c[line] > 0 && c[fault] === FAULT.cut)

const fmCutSomewhere = cutOn(
  ['fmDataLine', 'fmDataFault'],
  ['fmAddrLine', 'fmAddrFault'],
  ['fmWaveLine', 'fmWaveFault'],
)
const chipCutSomewhere = cutOn(
  ['chipDataLine', 'chipDataFault'],
  ['chipAddrLine', 'chipAddrFault'],
)
const drumCutSomewhere = cutOn(
  ['drumDataLine', 'drumDataFault'],
  ['drumAddrLine', 'drumAddrFault'],
)

export const SOURCE_GROUPS: Group[] = [
  {
    name: 'Toy keyboard',
    place: 'Sources',
    folded: ['the supply underneath', 'knife on the bus'],
    // The memory, drawn as the piano roll it is. Its steps have no slider
    // anywhere, exactly as the kit's grid has none, so this is where they are
    // named — for the reset that puts them back and the count that says how
    // many of them you have written.
    editor: {
      kind: 'roll',
      keys: [...TUNE_ALL_STEP_KEYS, 'tuneLen'],
    },
    // The rows the roll is about, over it rather than under it: which song the
    // chip is on — the roll is only what you are hearing when this says yours —
    // the rate it plays them back at, and how many of its notes a step it
    // reads. A widget this tall pushes all of them far enough down that you
    // stop finding them.
    lead: ['chipTune', 'tuneRate', 'tunePoly'],
    sliders: [
      {
        key: 'chipLevel',
        label: 'Level',
        role: 'level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the toy keyboard chip is in the source mix.',
      },
      {
        key: 'chipTune',
        label: 'Tune',
        min: 0,
        max: TUNE_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: TUNE_NAMES,
        help: 'Which song the chip plays: one of the eighteen in its ROM, or yours — the melody memory above, which is a tune like any other once it is in there. Each ROM carries its own sequencer rate, so the clock and the starve bend hit them differently; yours runs at the rate under this.',
      },
      {
        key: 'tuneRate',
        label: 'Memory rate',
        min: 0.2,
        max: 24,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        needs: playingYours,
        help: 'How fast the memory plays its steps back, which the ROM songs each carry for themselves. It is a rate rather than a tempo because it is the same clock the envelopes come off — wind it up and the notes shorten with it, exactly as they do on the ROM that runs at nine.',
      },
      {
        key: 'tunePoly',
        label: 'Memory notes',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['mono', 'poly'],
        needs: playingYours,
        help: 'Whether the chip reads the two memory chips stacked on the first one. Mono is the toy as it shipped: one note a step, off the melody oscillator, and the stacked lanes sit there unread. Poly plays all three — the melody where it always was, the other two on the key voices, which is the pin the piggyback’s output was soldered to. Four voices is the whole of the chip, so a three-note chord leaves one for your hands and the next thing that strikes takes the oldest.',
      },
      {
        key: 'chipTone',
        label: 'Tone',
        min: 0,
        max: 3,
        step: 1,
        unit: '',
        choices: ['organ 1/2', 'reed 1/4', 'clav 1/8', 'buzz 1/16'],
        help: 'Which width of pulse the tone selector taps off the divider chain. Narrow taps null different harmonics and thin out — the chip never levelled them, so they get quieter as they get reedier.',
      },
      {
        key: 'chipAccomp',
        label: 'Auto bass-chord',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The accompaniment section: bass on the step, chord stab on the offbeat, under whichever demo song is running. It reads the chord off the melody and picks major or minor from the ROM’s own notes. Same divider, same rail — starve the chip and the backing band goes down with it.',
      },
      {
        key: 'chipArp',
        label: 'Arpeggio',
        min: 0,
        max: ARP_MODES.length - 1,
        step: 1,
        unit: '',
        choices: ARP_MODES,
        help: 'The counter that walks the ROM, walking the keys your hand is holding instead. Hold a chord — the hold switch on the keybed latches one — and it plays it a note at a time. It runs off the chip’s own divider and nothing else, so the clock, a pot on the timing pin and a flat rail all drag the figure along with the tune.',
      },
      {
        key: 'chipArpHz',
        label: 'Arp rate',
        min: 0.5,
        max: 32,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        needs: c => c.chipArp > 0,
        help: 'Notes a second, before the divider gets to it. A nudge lands it on a division of the kit’s tempo, which is the only way the two machines ever line up — the toy runs on its own crystal and nothing pulls it back.',
      },
      {
        key: 'chipArpOct',
        label: 'Arp range',
        min: 1,
        max: 4,
        step: 1,
        unit: 'oct',
        needs: c => c.chipArp > 0,
        help: 'How many octaves the figure climbs before it starts again. The chip has four voices and the keys reach two octaves under its bottom A, so a wide range on a big chord is a chip stealing from itself — which is what it sounded like.',
      },
      {
        key: 'keyScale',
        label: 'Key lock',
        min: 0,
        max: SCALE_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: SCALE_NAMES,
        help: 'A diode matrix across the key contacts: a key off the scale closes the one under it instead, so nothing you play — or that the kit plays through the trigger patch — lands outside the key. It is on the key line, not on the ROM, so the demo songs and your own memory still come out as they were written.',
      },
      {
        key: 'keyRoot',
        label: 'Key',
        min: 0,
        max: 11,
        step: 1,
        unit: '',
        choices: NOTE_NAMES,
        needs: c => c.keyScale > 0,
        help: 'Which note the matrix is wired around. The chip’s own bottom key is an A, so C here is three keys up from it — the toy was never built in C.',
      },
      {
        key: 'chipSync',
        label: 'Kit sync',
        min: 0,
        max: SYNC_MODES.length - 1,
        step: 1,
        unit: '',
        choices: SYNC_MODES,
        help: 'A wire from the drum machine’s step clock to the toy’s timing chain, so the tune counts off the kit’s tempo instead of its own crystal. Pick how much of a beat one step of the tune is worth. It replaces the rate the song was written at and nothing else: Clock, a pot on the timing pin, crystal drift and a rail going flat all still drag the tune, so a locked toy on dying batteries still goes low, late and long — it is a wire on the timing pin, not a phase detector. Off is the crystal, which is what every board made before the wire went in has. The kit’s tempo is a control like any other, so a MIDI clock coming in writes it and the tune follows the room through the same wire.',
      },
      {
        key: 'chipClockX',
        label: 'Clock',
        min: 0.05,
        max: 16,
        step: 0.01,
        unit: '×',
        curve: 'log',
        help: 'Drags the master clock crystal. Everything the chip does — pitch, tempo, envelopes — slurs together.',
        action: {
          label: 'lock',
          title:
            'set the crystal to the nearest speed at which this ROM’s steps divide into the kit’s, so the tune and the pattern line up. It is the same knob as the pitch, so locking moves that too — and nothing holds it there: crystal drift, a starving rail or a wire on the clock will walk it off again, and changing the tempo afterwards leaves it where it stands. Kit sync is the wire that keeps up',
          value: lockToKit,
        },
      },
      {
        key: 'chipBendSpot',
        label: 'Bend spot',
        min: 0,
        max: 4,
        step: 1,
        unit: '',
        choices: ['off', 'clock', 'counter', 'bias', 'gate'],
        help: 'Where the virtual pot is soldered onto the die: clock feedback, program counter, DAC bias, or the gate line. Each spot breaks differently.',
      },
      {
        key: 'chipBendPot',
        needs: c => c.chipBendSpot > 0,
        label: 'Bend pot',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Turns the pot on the chosen bend spot. Zero is an open circuit; up is a harder short.',
      },
      {
        key: 'chipDrift',
        label: 'Crystal drift',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far the chip’s clock wanders off the ratio you set it to. The toy runs on its own crystal, so it drifts against the drum machine and never quite locks — two rates a hair apart, phasing in and out for as long as you leave it.',
      },
      {
        key: 'chipStarve',
        part: 'the supply underneath',
        label: 'Starve',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        shy: true,
        help: 'Sags the shared toy supply rail. Pitch dives, notes collapse, and past the brownout threshold the watchdog reboots the chip. One oscillator clocks the whole chip, so a sag that lasts slurs and slows the tune together, the way a tape does.',
      },
      {
        key: 'chipBattery',
        part: 'the supply underneath',
        label: 'Batteries',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        shy: true,
        help: 'How flat the cells are. The rail never comes back to full, so the toy runs low and slow — pitch, tempo and the drum machine with it — and every note sags it further with nothing starving it. Far enough down and a chord alone browns the chip out.',
      },
      {
        key: 'chipLeadR',
        part: 'the supply underneath',
        label: 'Lead resistance',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'A resistor in series with the cells: the rail still rests where it always rested, but every note has to pull its supply through the resistor to get there. So it sags on the attack and climbs back between hits — a toy that whoops on every note rather than one running out.',
      },
      {
        key: 'chipCap',
        part: 'the supply underneath',
        label: 'Reservoir',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How much of the board’s capacitance sits behind whatever the starve is pulling on. It moves no voltage — it decides how long the rail takes to get there. At zero starve is a step you land on; wound up you hear the whole dive, slowing as it goes.',
      },
      {
        key: 'chipClipHz',
        part: 'the supply underneath',
        label: 'Clip chatter',
        min: 0,
        max: 40,
        step: 0.1,
        unit: 'Hz',
        help: 'Bare metal dragged across the pads, and how often it finds one. Each touch chokes hard for a few tens of milliseconds and lets go at whatever rate the Reservoir allows — the dive that repeats without you doing anything.',
      },
      {
        key: 'chipClipClock',
        needs: c => c.chipClipHz > 0,
        part: 'the supply underneath',
        label: 'Clip on clock',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Whether the clip lands on the timing pin instead of the supply, which is the difference between a sag and a dive. Starving the rail is worth two thirds of an octave; dividing the clock has no such ceiling — four at the top, whole timebase with it. Needs Clip chatter.',
      },
      {
        key: 'chipLatch',
        part: 'the supply underneath',
        label: 'Latch-up',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        shy: true,
        help: 'How often a brownout jams the chip instead of rebooting it. A latched CMOS die holds whatever note was sounding and keeps drawing current, so it screams one note into the floor until the rail gives out under it and the watchdog gets its power cycle.',
      },
      {
        key: 'chipDataLine',
        part: 'knife on the bus',
        label: 'Data line',
        min: 0,
        max: ROM_DATA_LINES,
        step: 1,
        unit: '',
        choices: lineNames('D', ROM_DATA_LINES),
        shy: true,
        help: 'Which wire between the ROM and the divider the knife found. The chip stores a note code rather than a pitch, so low lines are small intervals and high ones octaves. One wire wrong is the same wrong note every time — the song keeps its rhythm and becomes a different song.',
      },
      {
        key: 'chipDataFault',
        needs: c => c.chipDataLine > 0,
        part: 'knife on the bus',
        label: 'Data fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'What happened to the wire. Cut leaves the pin floating, so the bit goes stale and carries the word before. To ground takes it out of every note; to +V puts it into every note, rests included, because a rest is only a code. Bridged brings the melody out in clumps.',
      },
      {
        key: 'chipAddrLine',
        part: 'knife on the bus',
        label: 'Address line',
        min: 0,
        max: ROM_ADDR_LINES,
        step: 1,
        unit: '',
        choices: lineNames('A', ROM_ADDR_LINES),
        shy: true,
        help: 'Which wire between the program counter and the ROM the knife found. The counter still counts and the tempo never moves — the ROM is simply handed the wrong step. A0 plays the tune in swapped pairs; A3 held low locks it into the bottom eight for good.',
      },
      {
        key: 'chipAddrFault',
        needs: c => c.chipAddrLine > 0,
        part: 'knife on the bus',
        label: 'Address fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'The same four things, on the address side. Cut leaves the step stale, so the tune stutters on notes it has already played; ground and +V nail that address bit for every read, which folds the song into half of itself; bridged ties two addresses together and the melody arrives in clumps of two and four.',
      },
      {
        key: 'chipBusCut',
        needs: chipCutSomewhere,
        part: 'knife on the bus',
        label: 'Cut depth',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far through the trace the knife went — only the cut fault reads it. All the way and the pin floats for good, and the song settles into one consistent mangling. Back it off and the trace still carries some of the time, so the melody flickers between two versions of itself.',
      },
    ],
  },
  {
    name: 'Toy drums',
    place: 'Sources',
    folded: [
      'inside the voices',
      'the converter',
      'triggers and cross-patch',
      'knife on the bus',
    ],
    editor: {
      kind: 'drums',
      keys: GRID_ROWS.flatMap(r =>
        r.maybe ? [r.key, r.maybe, r.len] : [r.key, r.len],
      ),
    },
    sliders: [
      {
        key: 'drumLevel',
        label: 'Level',
        role: 'level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the toy drum machine is in the source mix.',
      },
      {
        key: 'drumBpm',
        label: 'Tempo',
        min: 10,
        max: 3000,
        step: 1,
        unit: 'bpm',
        curve: 'log',
        help: 'Sequencer clock. Musical at the bottom; drag it far past the panel legend and the pattern smears into a buzz.',
      },
      {
        key: 'drumSwing',
        label: 'Swing',
        min: 0,
        max: 0.9,
        step: 0.01,
        unit: '',
        help: 'Holds every offbeat step back and takes the time off the step after, so the pattern shuffles without the tempo moving.',
      },
      {
        key: 'drumChance',
        label: 'Chance',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How often a maybe step closes. Click a step twice on the grid and its contact stops going straight to the trigger line and goes through the kit’s dice instead — one knob for the whole kit, rolled fresh every time the counter reaches the step. At nothing those steps are drawn and silent; all the way up they are steps like any other; and anywhere in between is the sixteen-step pattern finally not repeating.',
      },
      {
        key: 'drumTune',
        label: 'Tune',
        // A travel starts a whole number of its own steps from zero, or a
        // packed link and the slider count on different grids and the round
        // trip loses half a step (see packed.ts). An eighth speed is the floor
        // worth having, so the step halves rather than the floor moving — and
        // the bottom of a log travel is where a finer one pays anyway.
        min: 0.125,
        max: 8,
        step: 0.005,
        unit: '×',
        curve: 'log',
        help: 'The pitch trimmer inside the kit: every struck voice moves together. It rides on the supply, so starving the toy drags it down again. At the bottom of the travel the kick is under hearing and arrives as the thump of its own envelope; at the top the whole kit is a handful of tick marks.',
      },
      {
        key: 'drumDecay',
        label: 'Decay',
        min: 0.25,
        max: 16,
        step: 0.01,
        unit: '×',
        curve: 'log',
        help: 'Stretches or chokes every envelope at once. Short is a click track; long lets the kick and toms run into each other. Past about eight the kick stops being a hit and becomes a note held under the pattern — and it leans on the supply for as long as it rings.',
      },
      {
        key: 'drumRing',
        part: 'inside the voices',
        label: 'Ring',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How much of each swing the transistor around the kick, tom and snare hands back. Up the travel the hits stop stopping and start ringing; past nine tenths of it the networks hand back more than they took and never run down at all, so the pitched voices become notes the pattern retunes rather than drums it restrikes. The floor under the trigger holds them there: a network that never drains is a network the sequencer cannot strike again.',
      },
      {
        key: 'drumPulse',
        part: 'inside the voices',
        label: 'Trigger pulse',
        min: 0.05,
        max: 8,
        step: 0.01,
        unit: 'ms',
        curve: 'log',
        help: 'How long the one-shot holds the trigger line down. The charge is the same either way, so this is where it goes rather than how much: short is a tall spike that gets through the coupling cap as a click and shocks the network cleanly, long is a shove spread across most of a cycle, which the cap blocks and the network partly cancels — no click, less body, and least of both on the voices pitched high enough that the pulse outlasts them.',
      },
      {
        key: 'drumSnappy',
        part: 'inside the voices',
        label: 'Snappy',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'What the snare is made of. All the way up is the noise transistor alone, which is the snare this kit used to have; down, the two tuned networks under it come through instead — 185 and 330 Hz, beating against each other. Tune reaches those and does not reach the noise, so a snare with any tone in it moves with the rest of the kit.',
      },
      {
        key: 'drumNoiseBias',
        part: 'inside the voices',
        label: 'Noise bias',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How hard the kit’s one noise transistor is biased. It is a junction run backwards until it avalanches, which is where every bit of hiss on this board comes from — but a junction near the edge of avalanching does not conduct steadily. It latches in and out at random, holding each for anywhere between a third of a millisecond and a tenth of a second, which is what a marginal part does and is called popcorn noise for what it sounds like. The snare, both hats and the clap are all hanging off the one transistor, so they break up together and mid-hit rather than a voice at a time: down the travel the kit’s noise stutters, and near the bottom it only spits. What is left is the half of each voice that isn’t hiss — the snare’s tuned networks and the hats’ metal bank — so the pots beside this decide what a spitting kit still has to say.',
      },
      {
        key: 'drumMetal',
        part: 'inside the voices',
        label: 'Metal',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'What the hat and the open hat are fed from. Down is the noise transistor, which is the hat this kit used to have and which the snare and the clap are still hanging off. Up is the metal bank — six squares the cowbell already taps two of, high-passed until only the edges between them are left. The bank never stops turning, so no two hats catch it in the same place; noise is noise and every hit off it is the same hit.',
      },
      {
        key: 'drumCymTone',
        part: 'inside the voices',
        label: 'Cymbal tone',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Where the bottom of the cymbal’s band sits. Down it keeps the body of the bank and rings like something large and cracked; up it throws the body away and comes back as a splash. The top of the band does not move — above it there is nothing on this board but converter hash.',
      },
      {
        key: 'drumSpread',
        part: 'inside the voices',
        label: 'Bank spread',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'One resistor chain sets all six oscillators, and this leans on it. The ends of the chain move and the middle stays, so the bank widens rather than transposes — which is Tune’s job. Every metal voice moves together because they are the same six parts: wind it up and the cowbell detunes, the cymbal turns to glass, and the hats get grittier.',
      },
      {
        key: 'drumSquare',
        part: 'inside the voices',
        label: 'Squarer bias',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The one resistor that makes the bank a clatter. It wraps a gate from output back to input and parks it at its trip point, where the gain is in the thousands, so the six arrive at the far side as a rail and what comes out is which way they are leaning rather than how far. Back the bias off and the gate stops deciding and starts amplifying: the sum comes through as a sum, and the hat, the open hat and the cymbal turn from a clatter into the six tones they were made of — a metal chord that beats against itself. The cowbell is soldered in ahead of the stage, so it is the one metal voice this never reaches.',
      },
      {
        key: 'drumBits',
        part: 'the converter',
        label: 'Bit depth',
        min: 2,
        max: 16,
        // A DAC has a whole number of bits. The crusher's own word length is
        // fractional on purpose — it is a knob sweeping a step size — but this
        // one is a part the kit was built with.
        step: 1,
        unit: 'bit',
        help: 'Word length of the one cheap DAC the whole kit shares. Stock is 7 — wind it down and the tails turn to gravel before the hits do.',
      },
      {
        key: 'drumSlot',
        part: 'the converter',
        label: 'Voice slot',
        min: 0,
        max: 60,
        step: 0.5,
        unit: 'µs',
        help: 'How long the chip spends on one voice before it moves to the next. There is one converter for the whole kit, so it writes the ladder once it has been round everything that is sounding — which makes the kit’s sample rate the slot times the number of voices up, rather than a constant. A step that stacks the kit comes out coarser than the same voice on its own, and it goes coarser again as the batteries flatten, because a slot is counted off the same oscillator as the tempo. At nothing the chip keeps up and the kit is the kit it shipped as.',
      },
      {
        key: 'drumLadder',
        part: 'the converter',
        label: 'Ladder',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How much of that converter’s error you are hearing. Rungs off an unmeasured reel come out uneven, and the error is one lurch at the code where every bit changes at once — which for a signal is the zero crossing, so it lands hardest on whatever is quietest. Not hiss.',
      },
      {
        key: 'drumLadderTol',
        part: 'the converter',
        label: 'Part grade',
        min: 0,
        max: 0.6,
        step: 0.005,
        unit: '',
        help: 'What the reel those resistors came off was sold as — 15% is the bin this kit was built out of. Which rungs are long is soldered in and does not move; this is how far out they are. Ladder is how much reaches the output, this is how bad the parts were.',
      },
      {
        key: 'drumOverflow',
        part: 'the converter',
        label: 'Overflow',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['off', 'wrap'],
        help: 'What the converter does with a sum too wide for its word. A cheap one rolls over rather than stopping at the top: a step stacking four voices under an accent comes out inside-out, while the quiet steps either side are untouched. Off, the sum leaves the box past full scale.',
      },
      {
        key: 'drumRetrigHz',
        part: 'triggers and cross-patch',
        label: 'Retrigger',
        min: 0,
        max: 4000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'Retriggers the current step at this rate. Slow is a machine-gun roll; past ~40 Hz the retrigger period becomes the pitch and the drum screams.',
      },
      {
        key: 'drumTrigFloor',
        part: 'triggers and cross-patch',
        label: 'Trigger floor',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far a voice has to have drained before the one-shot behind it will answer the trigger line again. At nothing every pulse strikes; wound up, a line hammered faster than a voice can empty comes out divided — a rattle at the rate Decay sets rather than Retrigger.',
      },
      {
        key: 'drumAccentAmt',
        part: 'triggers and cross-patch',
        label: 'Accent',
        min: 1,
        max: 4,
        step: 0.01,
        unit: '×',
        help: 'How far the accent bus swings when it is rested. At 1 the accent row does nothing and the kit has one weight; wound up it is the difference between the pattern and the fill.',
      },
      {
        key: 'drumAccentSag',
        part: 'triggers and cross-patch',
        label: 'Accent sag',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The accent is one cap feeding every voice, and this is how much each accented step takes off it. At nothing the bus is stiff and every accent is the full one. Wound up, a step stacking four voices hands each of them less than a step stacking one, and a second accent before the cap has caught up lands softer than the first — so a roll comes out shaped without a knob moving.',
      },
      {
        key: 'drumChoke',
        part: 'triggers and cross-patch',
        label: 'Choke',
        min: 0,
        max: CHOKE_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: CHOKE_NAMES,
        help: 'Where the board’s one choke resistor is soldered. It sits across the hats’ shared cap to begin with, which is what a hi-hat pedal is: a closed step does not silence a ringing open hat, it drains what is left of it in a hurry. Move the wire and any voice can do that to any other — the hats keep their pedal either way, because that pair is wired in the metal rather than on the panel. It is the trigger line it listens to, so a pad, the mic and a bridged wire all choke as well as the sequencer does.',
      },
      {
        key: 'drumCross',
        part: 'triggers and cross-patch',
        label: 'Cross-patch',
        min: 0,
        max: 5,
        step: 1,
        unit: '',
        choices: [
          'off',
          'kick/snare',
          'snare/hat',
          'kick/hat',
          'rotate',
          'whole kit',
        ],
        help: 'Bridges two voices’ envelope pins so each amplifier hears the wrong envelope. Rotate passes the original three around the ring; whole kit passes every voice, so the cowbell rings on a kick and the clap answers a tom.',
      },
      {
        key: 'drumCrossAmt',
        needs: c => c.drumCross > 0,
        part: 'triggers and cross-patch',
        label: 'Cross bleed',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far each amplifier leans across. All the way over is a full swap — the kick fires on snare steps, the noise swells on kicks, and a hat tick puts a pitch blip through the kick.',
      },
      {
        key: 'drumAddrLine',
        part: 'knife on the bus',
        label: 'Address line',
        min: 0,
        max: ADDR_LINES,
        step: 1,
        unit: '',
        choices: lineNames('A', ADDR_LINES),
        shy: true,
        help: 'Which of the four wires carrying a step number to the pattern memory the knife found. Nothing malfunctions: the counter still counts and a different cell answers. A0 held low plays every step twice; A3 held high hands you the back half of the bar and never the front.',
      },
      {
        key: 'drumAddrFault',
        needs: c => c.drumAddrLine > 0,
        part: 'knife on the bus',
        label: 'Address fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'The same four things a knife does to any trace, on the side that chooses the step. A cut goes stale carrying the fetch before — usually the row above asking for the same step — so it wants to be most of the way through before the pattern moves. Bridged collapses the steps onto a lattice.',
      },
      {
        key: 'drumDataLine',
        part: 'knife on the bus',
        label: 'Data line',
        min: 0,
        max: N_DRUM_VOICES,
        step: 1,
        unit: '',
        choices: lineNames('D', N_DRUM_VOICES),
        shy: true,
        help: 'Which of the wires carrying the word back the knife found — one wire a voice, in the order of the rows. To +V is that voice on every step, which is the machine-gun; to ground is a row you can see and cannot hear. It is the trigger bus, so a bit forced high reaches the sampler, keyboard and FM chip too.',
      },
      {
        key: 'drumDataFault',
        needs: c => c.drumDataLine > 0,
        part: 'knife on the bus',
        label: 'Data fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'The same four, on the side carrying the word. Bridged is the one worth knowing here: two voices soldered to each other come out only where both rows agree, so a busy pattern thins to what the pair have in common.',
      },
      {
        key: 'drumBusCut',
        needs: drumCutSomewhere,
        part: 'knife on the bus',
        label: 'Cut depth',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far through the trace the knife went — only the cut fault reads it. It bites less here than anywhere else on the board: every row fetches its own step through these same wires inside one tick, so a floating bit is mostly holding the value it was about to be handed anyway.',
      },
    ],
  },
  {
    name: 'FM chip',
    place: 'Sources',
    folded: ['inside the patch', 'knife on the bus'],
    sliders: [
      {
        key: 'fmLevel',
        label: 'Level',
        role: 'level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the FM chip is in the source mix. It has no sequencer of its own — somebody soldered its key input onto the toy’s gate line, so out of the box it plays whatever strikes a note over there. Cut that jumper and it answers only its own keybed. Same rail either way, so starving the toy dives its pitch.',
      },
      {
        key: 'fmVoice',
        label: 'Voice',
        min: 0,
        max: FM_VOICE_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FM_VOICE_NAMES,
        help: 'Which of the eight patches under the voice buttons the processor sends the chip. A patch is eight bytes written into the register file, not a mode the chip is put into — so pressing a voice button is a moment where a cut data line can land, and the patch you get is the one the wires let through.',
      },
      {
        key: 'fmBright',
        label: 'Brightness',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the modulator is into the carrier, which on a two-operator chip is the whole of the tone control: down is a sine, up is the harmonics piling on. It rides out with the patch as one of those eight bytes, so moving it is another write for a fault to catch.',
      },
      {
        key: 'fmFeedback',
        label: 'Feedback',
        min: 0,
        max: 7,
        step: 1,
        unit: '',
        help: 'How much of the modulator goes back into itself, three bits of it as the part had. Past about five the operator stops making harmonics and starts making noise, which is where the chip’s own drum sounds came from.',
      },
      {
        key: 'fmLfo',
        label: 'Vibrato',
        min: 0,
        max: FM_LFO_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FM_LFO_NAMES,
        help: 'The one LFO on the die, which has no register anywhere — no rate, no depth, nothing to start or stop it. It has been running since the board came up and all this button does is solder the operators to it, two bits in each of two patch bytes. It counts off the same divider as the pitch, so starving the toy slows the wobble down too. Voices that came with their own keep it whatever the button says.',
      },
      {
        key: 'fmLength',
        label: 'Note length',
        min: 0.02,
        max: 4,
        step: 0.01,
        unit: 's',
        curve: 'log',
        help: 'How long the processor waits before writing the key back up, for a note nothing is holding — the demo song, a drum hit, a kit line clipped on below. Your own hands are the exception: the gate says the key is still down, so the note is held until you let go.',
      },
      {
        key: 'fmStruck',
        label: 'Struck by',
        min: 0,
        max: N_DRUM_VOICES + 1,
        step: 1,
        unit: '',
        choices: ['off', ...VOICE_LABELS, 'any hit'],
        help: 'The kit’s trigger lines, clipped onto this chip’s key input. A trigger carries a strike and nothing else, so the note is decided at this end: one per voice, in row order, a pentatonic apart, which turns a pattern written for drums into a riff. Four channels, so a busy grid steals its own notes.',
      },
      {
        key: 'fmKeyGate',
        label: 'Toy gate',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['soldered', 'cut'],
        help: 'The jumper from the toy’s gate line onto this chip’s key input — the accident of a wiring loom that makes the two boxes play the same part. Cut it and the chip stops following the keyboard next door and answers only its own keys, the kit’s trigger lines and the effect ROM. Its own keybed plays either way.',
      },
      {
        key: 'fmEffect',
        label: 'Effect',
        min: 0,
        max: FM_EFFECT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FM_EFFECT_NAMES,
        shy: true,
        help: 'The effect ROM — a bird, surf, wind, a siren, crickets. None is a sample: each is a little program firing hundreds of register writes a second, far and away the busiest thing the bus ever carries. It borrows the fourth channel, so Voice, Bright and Feedback sit still while one runs.',
      },
      {
        key: 'fmRhythm',
        label: 'Rhythm',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['off', 'kit'],
        help: 'The percussion bank, which is a second thing the die can be: press it and the top two channels stop belonging to the keyboard, re-tapped onto a bass drum and a pair of slots fed by a shift register running since power-on. That register is the only noise on the chip — everything else it makes is a sine. Every note strikes the bass drum; for the snare and the hat, clip the kit’s lines on with Struck by. Costs two voices, and an effect wants the same ones.',
      },
      {
        key: 'fmModRatio',
        part: 'inside the patch',
        label: 'Mod ratio',
        min: 0,
        max: RATIO_CHOICES.length - 1,
        step: 1,
        unit: '',
        choices: RATIO_CHOICES,
        help: 'What the modulator runs at against the note, as a multiple of it. This and Brightness are the whole of two-operator FM: the ratio picks which harmonics can be there, brightness decides how many arrive. 1 fills out the tone, 2 and 3 are reed and brass, 7 upward bells and metal.',
      },
      {
        key: 'fmCarRatio',
        part: 'inside the patch',
        label: 'Car ratio',
        min: 0,
        max: RATIO_CHOICES.length - 1,
        step: 1,
        unit: '',
        choices: RATIO_CHOICES,
        help: 'The same table on the carrier, which moves the note itself rather than its colour — 2 is the same patch an octave up. Set both and what matters is the interval: 1 against 2 is a hollow octave, 2 against 3 a fifth, and anything not a whole multiple clangs.',
      },
      {
        key: 'fmModDecay',
        part: 'inside the patch',
        label: 'Mod decay',
        min: 0,
        max: DECAY_CHOICES.length - 1,
        step: 1,
        unit: '',
        choices: DECAY_CHOICES,
        help: 'How long the modulator takes to fall away, which is what makes an FM note a bell or an organ. Sixteen rates, counted off the same divider as the tempo and the pitch — so starving the rail stretches these along with everything else.',
      },
      {
        key: 'fmDataLine',
        part: 'knife on the bus',
        label: 'Data line',
        min: 0,
        max: 8,
        step: 1,
        unit: '',
        choices: lineNames('D', 8),
        shy: true,
        help: 'Which of the eight wires carrying bytes to the register file the knife found. A register holds what it was last told, so a fault here does not pass — it accumulates. Patches come out wrong and stay wrong, and if the bit carrying the key going up cannot go low, the note never ends.',
      },
      {
        key: 'fmDataFault',
        part: 'knife on the bus',
        needs: c => c.fmDataLine > 0,
        label: 'Data fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'What happened to the wire — the same four things a knife does to any trace. Cut leaves the pin floating and the bit goes stale, carrying whatever the byte before had in it, which on a bus this busy is a different wrong answer every write. To ground and to +V nail the bit for every byte the processor sends.',
      },
      {
        key: 'fmAddrLine',
        part: 'knife on the bus',
        label: 'Address line',
        min: 0,
        max: 6,
        step: 1,
        unit: '',
        choices: lineNames('A', 6),
        shy: true,
        help: 'Which of the six wires choosing the register the knife found. The byte arrives intact and is filed in the wrong place — a frequency into an envelope register, a key-on into a waveform — and whatever should have gone there never did, so the chip plays on with the last value it was told.',
      },
      {
        key: 'fmAddrFault',
        part: 'knife on the bus',
        needs: c => c.fmAddrLine > 0,
        label: 'Address fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'The same four things, on the address side. A0 held low files every odd register on top of the even one below it, so the four channels stop having frequencies of their own; the higher lines throw whole banks on top of each other.',
      },
      {
        key: 'fmWaveLine',
        part: 'knife on the bus',
        label: 'Wave line',
        min: 0,
        max: 10,
        step: 1,
        unit: '',
        choices: lineNames('W', 10),
        shy: true,
        help: 'Which of the ten wires addressing the sine table the knife found. Nothing here computes a sine — it looks one up — so the waveform is an address, and nothing accumulates. W8 runs the quarter wave twice, an octave up with a cliff in it; W9 is the sign, so cutting it leaves all octave and no fundamental.',
      },
      {
        key: 'fmWaveFault',
        part: 'knife on the bus',
        needs: c => c.fmWaveLine > 0,
        label: 'Wave fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        shy: true,
        choices: FAULT_NAMES,
        help: 'The same four things, on the wave ROM’s address. Cut is the strange one: the line holds the last phase bit that reached it and stops being part of the wave at all. Back the cut depth off and the wave flickers between two shapes. Ground and +V nail it — a waveform rather than a fault.',
      },
      {
        key: 'fmBusCut',
        part: 'knife on the bus',
        needs: fmCutSomewhere,
        label: 'Cut depth',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far through the trace the knife went — the cut fault is the only one that reads it. All the way and the bit holds whatever was last on it. Back it off and the line still carries some of the time, so most writes land and the occasional one does not: a patch that is nearly right, a note in ten that hangs.',
      },
      {
        key: 'fmStrobe',
        part: 'knife on the bus',
        label: 'Strobe slip',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        shy: true,
        help: 'The pulse telling the address latch to take what is on the wires, and how often it comes out too narrow to be caught. Nothing is corrupted: both bytes arrive intact and commit to whichever register the last pulse named, one write late. A latch that misses holds rather than skips, so misses stack.',
      },
    ],
  },
  {
    name: 'Chaos osc',
    place: 'Sources',
    sliders: [
      {
        key: 'oscLevel',
        label: 'Level',
        role: 'level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the oscillator pair is in the source mix.',
      },
      {
        key: 'oscAHz',
        label: 'Osc A',
        min: 20,
        max: 12000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'The audible oscillator.',
      },
      {
        key: 'oscBHz',
        label: 'Osc B',
        min: 0.1,
        max: 12000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'The modulator. Sub-audio rates warble and siren; audio rates tear A into sidebands.',
      },
      {
        key: 'oscXmod',
        label: 'Cross-mod',
        min: 0,
        max: 8000,
        step: 1,
        unit: 'Hz',
        curve: 'log',
        help: 'How many Hz of deviation B drags A through. Turn it up and the pair stops being two pitches. Past a few thousand the deviation is wider than the carrier, so what comes out is sidebands with nothing in the middle.',
      },
      {
        key: 'oscShape',
        label: 'Shape',
        min: 0,
        max: 2,
        step: 1,
        unit: '',
        choices: ['square', 'saw', 'pulse'],
        help: 'Waveform of both oscillators.',
      },
      {
        key: 'oscStarve',
        label: 'Starve',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Sags the oscillator supply. Loud output drags pitch and amplitude down until it stalls, recovers, and stalls again — motorboating for free.',
      },
    ],
  },
  {
    name: 'Noise & crackle',
    place: 'Sources',
    sliders: [
      {
        key: 'noiseLevel',
        label: 'Noise',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'White noise level into the chain.',
      },
      {
        key: 'noiseColor',
        label: 'Color',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        split: { at: 0 },
        reads: v =>
          v === 0
            ? 'flat'
            : `${Math.abs(v).toFixed(2)} ${v < 0 ? 'dark' : 'bright'}`,
        help: 'Tilts the noise dark (rumble) or bright (hiss).',
      },
      {
        key: 'crackleAmp',
        label: 'Crackle',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        shy: true,
        help: 'Dirty-pot contact crackle: random spikes rung through a resonant filter.',
      },
      {
        key: 'crackleRate',
        label: 'Crackle rate',
        min: 0,
        max: 2000,
        step: 1,
        unit: '/s',
        help: 'How often the contact sparks. Sparse is a bad joint; wound right up the sparks stop arriving one at a time and the resonance behind them becomes a tone.',
      },
    ],
  },
  {
    name: 'Sampler',
    place: 'Sources',
    // The reel itself lives beside the keys rather than in here, because it is
    // the one thing on this stage you watch rather than set: what is on the
    // tape, where the head is, and the two markers, drawn as a tape and
    // dragged as one.
    sliders: [
      {
        key: 'sampleLevel',
        label: 'Level',
        role: 'level',
        min: 0,
        max: 2,
        step: 0.01,
        unit: '×',
        // ×1 is the file playing back at its own recorded level — the tick on
        // the track marks it. Short of it the knob is turning the file down;
        // past it, there was never that much signal in the recording, and the
        // knob is adding gain rather than restoring volume.
        mark: 1,
        help: 'Level of the dropped audio file, looping through the chain. ×1 is the file at its own recorded level; past that you are adding gain, not turning it up.',
      },
      {
        key: 'sampleSpeed',
        label: 'Speed',
        min: -4,
        max: 4,
        // Thousandths, where every other level on the board takes hundredths.
        // A speed is a ratio, so what a step is worth depends where you are
        // standing: 0.01 is a hundredth of a semitone at ×1 and a whole octave
        // at ×0.01. The slow end is the end you crawl along, so the step is cut
        // to what it is worth down there.
        step: 0.001,
        unit: '×',
        curve: 'symlog',
        // A knob whose middle is a stop and whose left half is reverse reads as
        // a broken one if the readout only prints the number: coming down past
        // zero the tape picks up again, and "−2.400 ×" does not say that where
        // "2.400× reverse" does.
        reads: v =>
          v === 0
            ? 'frozen'
            : `${Math.abs(v).toFixed(3)}× ${v < 0 ? 'reverse' : 'forward'}`,
        split: {
          at: 0,
          names: { below: 'reverse', above: 'forward', mid: 'stop' },
          detent: true,
          // ×0–×1 forward is the tape sounding like a tape; past the red tick
          // you are not playing it faster, you are speeding it up.
          normal: 1,
        },
        action: {
          label: 'stop',
          title:
            'park the tape on the spot the head is standing — the middle of this travel, with reverse below it and forward above',
          value: () => 0,
        },
        help: 'Playback speed, with the stop in the middle of the travel and reverse below it. The left half is not slower, it is backwards: the tape freezes where the head stands and picks up the other way. The red ticks bound ×0–×1, ordinary speed; past that you are speeding the tape up rather than just playing it faster. The arrow on the reel says which way you are going.',
      },
      {
        key: 'sampleTrig',
        label: 'Struck by',
        min: 0,
        max: VOICE_LABELS.length + 3,
        step: 1,
        unit: '',
        choices: ['off', ...VOICE_LABELS, 'any hit', 'key', 'mic'],
        help: 'Which trigger line drops the needle back at the top of the file: one of the kit’s voices, any hit at all, a note off the keyboard, or a shout in the mic. With one-shot beside it the file becomes a seventh drum voice; off, it loops the way it always did.',
      },
      {
        key: 'sampleMode',
        label: 'Ending',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['loop', 'one-shot'],
        help: 'What happens at the end of the file: round again, or stop there and wait to be struck. Backwards, the end is the top of the file.',
      },
      {
        key: 'loopIn',
        label: 'Loop in',
        min: 0,
        max: 1,
        step: 0.001,
        unit: '',
        // A place on the tape rather than an amount of anything, so it reads as
        // how far along it is: 0.350 is a number, 35.0% is a spot on a reel.
        reads: v => `${(v * 100).toFixed(1)}%`,
        help: 'Where the loop starts, as a fraction of the reel. Everything before it is still on the tape and simply never passes the head, so a bar you liked out of a three-minute recording is two markers rather than an edit. Drag them on the reel instead of guessing at the number.',
      },
      {
        key: 'loopOut',
        label: 'Loop out',
        min: 0,
        max: 1,
        step: 0.001,
        unit: '',
        reads: v => `${(v * 100).toFixed(1)}%`,
        help: 'Where the loop ends. Dragged past the in point the two swap rather than collapse. Pinch them together and the window is a handful of frames going round thousands of times a second, which stops being a loop and becomes a pitch — the tape doing it, not an oscillator.',
      },
      {
        key: 'loopRec',
        label: 'Record',
        part: 'the record head',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How much of the board’s own output the record head lays back down, on the spot the play head is reading. Which makes this a tape loop rather than a sampler: what comes round next lap has been through the whole board, and then goes through it again.',
      },
      {
        key: 'loopErase',
        label: 'Erase',
        part: 'the record head',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How much of what is already on the tape the erase head takes off on the way past. All the way up, each lap replaces the last — a delay the length of the reel. All the way down the head is disconnected and the laps pile up until the oxide runs out of room.',
      },
      {
        key: 'loopSecs',
        label: 'Blank tape',
        part: 'the record head',
        min: 0.25,
        max: 20,
        step: 0.25,
        unit: 's',
        help: 'How long a reel to thread when you arm the record head with nothing loaded. Read once, when the tape goes on: a reel you have already recorded on is the length it is, and a knob that resized it would be throwing the take away. Drop a file in and the file is the reel.',
      },
    ],
  },
  // Not a channel. On one of its seven settings the mic reaches the mix, and on
  // the other six it is soldered into the middle of the board — so it gets a
  // group of its own, and the map draws it as the patch wire it actually is.
  {
    name: 'Mic',
    place: 'Sources',
    // The picture drawn above these rows, in MicPatch: the mic against all
    // seven jacks it could be soldered to, not only the one it is.
    editor: { kind: 'mic' },
    sliders: [
      {
        key: 'micLevel',
        label: 'Mic',
        role: 'level',
        min: 0,
        max: 2,
        step: 0.01,
        unit: '',
        help: 'Microphone gain into the patch point. Watch speaker feedback — or use it.',
      },
      {
        key: 'micPatch',
        label: 'Mic patch',
        min: 0,
        max: 6,
        step: 1,
        unit: '',
        choices: [
          'mix',
          'chip rail',
          'osc FM',
          'delay fb',
          'ring car',
          'drum trig',
          'glitch trig',
        ],
        help: 'Where the mic wire is soldered: the mix bus, the toy supply rail (yell to brown it out), oscillator A’s FM input, the delay feedback path, the ring mod carrier, or the trigger line of the drum machine or glitch buffer — clap at it and the circuit fires.',
      },
    ],
  },
]
