import type { Controls } from '../../controls'
import { FAULT_NAMES, lineNames } from '../../dsp/bus'
import { FM_EFFECT_NAMES } from '../../dsp/stages/fmEffects'
import { FM_VOICE_NAMES } from '../../dsp/stages/fmVoices'
import {
  ROM_ADDR_LINES,
  ROM_DATA_LINES,
  ROM_NAMES,
  ROMS,
} from '../../dsp/stages/roms'
import { GRID_ROWS, VOICE_LABELS } from '../../drums'
import type { Group, SliderDef } from './types'

// The toy has no sync input, so locking it to the kit means picking the crystal
// speed at which the ROM's own steps divide into the kit's. Which multiple of
// that speed you want is a pitch decision as much as a timing one — the same
// knob is both — so it lands on the one nearest where the crystal already sits.
const LOCK_MULTIPLES = [
  1 / 8,
  1 / 6,
  1 / 4,
  1 / 3,
  1 / 2,
  2 / 3,
  1,
  3 / 2,
  2,
  3,
]

function lockToKit(c: Controls, def: SliderDef): number {
  const romHz = ROMS[Math.round(c.chipTune)]?.stepHz ?? 8
  const base = ((c.drumBpm / 60) * 4) / romHz
  const off = (v: number) => Math.abs(Math.log(v / c.chipClockX))
  const speeds = LOCK_MULTIPLES.map(m => base * m).filter(
    v => v >= def.min && v <= def.max,
  )
  // Nothing in range is a tempo the crystal cannot reach; the knob stays put.
  if (speeds.length === 0) return c.chipClockX
  return speeds.reduce((best, v) => (off(v) < off(best) ? v : best))
}

export const SOURCE_GROUPS: Group[] = [
  {
    name: 'Toy keyboard',
    place: 'Sources',
    sliders: [
      {
        key: 'chipLevel',
        label: 'Level',
        role: 'level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the toy keyboard chip is in the source mix.',
      },
      {
        key: 'chipTune',
        label: 'Tune ROM',
        min: 0,
        max: ROM_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: ROM_NAMES,
        help: 'Which demo song the chip plays from ROM. Each ROM carries its own sequencer rate, so the clock and the starve bend hit them differently.',
      },
      {
        key: 'chipTone',
        label: 'Tone',
        min: 0,
        max: 3,
        step: 1,
        unit: '',
        choices: ['organ 1/2', 'reed 1/4', 'clav 1/8', 'buzz 1/16'],
        help: 'Which width of pulse the tone selector taps off the divider chain. Narrow taps null different harmonics and thin out — the chip never levelled them, so they get quieter as they get reedier.',
      },
      {
        key: 'chipAccomp',
        label: 'Auto bass-chord',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The accompaniment section: bass on the step, chord stab on the offbeat, under whichever demo song is running. It reads the chord off the melody and picks major or minor from the ROM’s own notes. Same divider, same rail — starve the chip and the backing band goes down with it.',
      },
      {
        key: 'chipClockX',
        label: 'Clock',
        min: 0.05,
        max: 16,
        step: 0.01,
        unit: '×',
        curve: 'log',
        help: 'Drags the master clock crystal. Everything the chip does — pitch, tempo, envelopes — slurs together.',
        action: {
          label: 'lock',
          title:
            'set the crystal to the nearest speed at which this ROM’s steps divide into the kit’s, so the tune and the pattern line up. It is the same knob as the pitch, so locking moves that too — and nothing holds it there: crystal drift, a starving rail or a wire on the clock will walk it off again',
          value: lockToKit,
        },
      },
      {
        key: 'chipStarve',
        label: 'Starve',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Sags the shared toy supply rail. Pitch dives, notes collapse, and past the brownout threshold the watchdog reboots the chip — the tune keeps restarting. One oscillator clocks the whole chip, so a sag that lasts takes the tempo down with the pitch: the tune slurs and slows together, the way a tape does. A dip inside a single note is too quick for the timing pin to notice, which is why a chord sags without the beat stumbling.',
      },
      {
        key: 'chipBattery',
        label: 'Batteries',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How flat the cells are. The rail never comes back to full, so the toy runs low and slow — pitch, tempo and the drum machine with it — and every note sags it further with nothing starving it. Far enough down and a chord alone browns the chip out.',
      },
      {
        key: 'chipCap',
        label: 'Reservoir',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How much of the board’s own capacitance sits behind whatever the starve is pulling on. It moves no voltage — it decides how long the rail takes to get there. At zero the supply settles inside a millisecond and starve is a step you land on; wound up, the same starve takes a third of a second to fall and you hear the whole dive, slowing as it goes. Everything on the rail goes with it: pitch, tempo, envelopes. Far enough up and the reboot stops snapping the rail back at all, so the tune is struck high, dragged down, cut off, and struck high again.',
      },
      {
        key: 'chipClipHz',
        label: 'Clip chatter',
        min: 0,
        max: 40,
        step: 0.1,
        unit: 'Hz',
        help: 'Bare metal dragged across the pads, and how often it finds one. Each touch chokes hard for a few tens of milliseconds and lets go, and what it chokes leaves at whatever rate the Reservoir allows — so this is the dive that repeats without you doing anything. A choke rather than a short: crash the rail to ground instead and the pitch is simply gone and then simply back, two steps with the dive missing. It is a hand holding a paperclip rather than a switch, so the rate is an average and the fault cluster decides how much it bunches.',
      },
      {
        key: 'chipClipClock',
        label: 'Clip on clock',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Whether the clip lands on the timing pin instead of the supply — and it is the difference between a sag and a dive. Starving the rail is worth two thirds of an octave before the chip stops running at all; a capacitor hung on the oscillator divides the clock instead, and division has no such ceiling. Four octaves at the top, travelling at whatever rate the Reservoir charges, with the whole timebase going along: tune, tempo and envelopes together, the melody arriving somewhere under the bottom of its own keyboard. Needs Clip chatter to have something to land with.',
      },
      {
        key: 'chipDataLine',
        label: 'Data line',
        min: 0,
        max: ROM_DATA_LINES,
        step: 1,
        unit: '',
        choices: lineNames('D', ROM_DATA_LINES),
        shy: true,
        help: 'Which wire between the ROM and the divider the knife found. The chip stores a note code rather than a pitch, so the low lines are small intervals and the high ones are octaves — D0 is a semitone, D2 a major third, D5 the better part of three octaves. Nothing about it is random: one wire wrong is the same wrong note every time that step comes round, so the song keeps its rhythm and its shape and becomes a different song.',
      },
      {
        key: 'chipDataFault',
        label: 'Data fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'What happened to the wire. Cut leaves the pin floating, so the bit goes stale and carries whatever the word before had in it. To ground takes that bit out of every note the chip reads. To +V puts it into every note — including the ones that were not notes, because a rest is only a code, and a code with a bit forced into it is a pitch. Bridged solders the line to its neighbour so the two can no longer disagree, and the melody comes out in clumps.',
      },
      {
        key: 'chipAddrLine',
        label: 'Address line',
        min: 0,
        max: ROM_ADDR_LINES,
        step: 1,
        unit: '',
        choices: lineNames('A', ROM_ADDR_LINES),
        shy: true,
        help: 'Which wire between the program counter and the ROM the knife found. The counter still counts and the tempo never moves; the ROM is simply handed the wrong step. A0 plays the tune in swapped pairs, A3 held low locks it into the bottom eight steps for good, and a line this ROM never drives does nothing at all — a sixteen-step song has no A4 for you to find.',
      },
      {
        key: 'chipAddrFault',
        label: 'Address fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'The same four things, on the address side. Cut leaves the step stale, so the tune stutters on notes it has already played; ground and +V nail that address bit for every read, which folds the song into half of itself; bridged ties two addresses together and the melody arrives in clumps of two and four.',
      },
      {
        key: 'chipBusCut',
        label: 'Cut depth',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far through the trace the knife went — the cut fault is the only one that reads it. All the way and the pin floats for good: the bit holds whatever the last word left on it and the song settles into one consistent mangling. Back it off and the trace still carries some of the time, so the bit is right on some reads and a word old on others, and the melody flickers between two versions of itself.',
      },
      {
        key: 'chipBendSpot',
        label: 'Bend spot',
        min: 0,
        max: 4,
        step: 1,
        unit: '',
        choices: ['off', 'clock', 'counter', 'bias', 'gate'],
        help: 'Where the virtual pot is soldered onto the die: clock feedback, program counter, DAC bias, or the gate line. Each spot breaks differently.',
      },
      {
        key: 'chipBendPot',
        label: 'Bend pot',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Turns the pot on the chosen bend spot. Zero is an open circuit; up is a harder short.',
      },
      {
        key: 'chipDrift',
        label: 'Crystal drift',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far the chip’s clock wanders off the ratio you set it to. The toy runs on its own crystal, so it drifts against the drum machine and never quite locks — two rates a hair apart, phasing in and out for as long as you leave it.',
      },
      {
        key: 'chipLatch',
        label: 'Latch-up',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How often a brownout jams the chip instead of rebooting it. A latched CMOS die holds whatever note was sounding and keeps drawing current, so it screams one note into the floor until the rail gives out under it and the watchdog gets its power cycle.',
      },
    ],
  },
  {
    name: 'Toy drums',
    place: 'Sources',
    editor: {
      kind: 'drums',
      keys: GRID_ROWS.flatMap(r => [r.key, r.len]),
    },
    sliders: [
      {
        key: 'drumLevel',
        label: 'Level',
        role: 'level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the toy drum machine is in the source mix.',
      },
      {
        key: 'drumBpm',
        label: 'Tempo',
        min: 10,
        max: 3000,
        step: 1,
        unit: 'bpm',
        curve: 'log',
        help: 'Sequencer clock. Musical at the bottom; drag it far past the panel legend and the pattern smears into a buzz.',
      },
      {
        key: 'drumSwing',
        label: 'Swing',
        min: 0,
        max: 0.9,
        step: 0.01,
        unit: '',
        help: 'Holds every offbeat step back and takes the time off the step after, so the pattern shuffles without the tempo moving.',
      },
      {
        key: 'drumTune',
        label: 'Tune',
        min: 0.25,
        max: 4,
        step: 0.01,
        unit: '×',
        curve: 'log',
        help: 'The pitch trimmer inside the kit: every struck voice moves together. It rides on the supply, so starving the toy drags it down again.',
      },
      {
        key: 'drumDecay',
        label: 'Decay',
        min: 0.25,
        max: 16,
        step: 0.01,
        unit: '×',
        curve: 'log',
        help: 'Stretches or chokes every envelope at once. Short is a click track; long lets the kick and toms run into each other. Past about eight the kick stops being a hit and becomes a note held under the pattern — and it leans on the supply for as long as it rings.',
      },
      {
        key: 'drumBits',
        label: 'Bit depth',
        min: 2,
        max: 16,
        // A DAC has a whole number of bits. The crusher's own word length is
        // fractional on purpose — it is a knob sweeping a step size — but this
        // one is a part the kit was built with.
        step: 1,
        unit: 'bit',
        help: 'Word length of the one cheap DAC the whole kit shares. Stock is 7 — wind it down and the tails turn to gravel before the hits do.',
      },
      {
        key: 'drumLadder',
        label: 'Ladder',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far out the resistors in that converter are. A ladder halves its weight at every rung down the word, and a kit like this got its rungs off a reel nobody measured, so the steps come out uneven — and unevenly, because the error scales with the rung: half the tolerance of the top resistor is an enormous number of counts. That is why a cheap converter is not hiss. It is one lurch, at the code where every bit changes at once, and for a signal that code is the zero crossing — so it lands hardest on whatever is quietest, and a tail on its way out is nothing but zero crossings. Bit depth moves where the word is tapped off the ladder, so it changes the character of the error as well as the size.',
      },
      {
        key: 'drumRetrigHz',
        label: 'Retrigger',
        min: 0,
        max: 4000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'Retriggers the current step at this rate. Slow is a machine-gun roll; past ~40 Hz the retrigger period becomes the pitch and the drum screams.',
      },
      {
        key: 'drumCross',
        label: 'Cross-patch',
        min: 0,
        max: 5,
        step: 1,
        unit: '',
        choices: [
          'off',
          'kick/snare',
          'snare/hat',
          'kick/hat',
          'rotate',
          'whole kit',
        ],
        help: 'Bridges two voices’ envelope pins so each amplifier hears the wrong envelope. Rotate passes the original three around the ring; whole kit passes all six, so the cowbell rings on a kick and the clap answers a tom.',
      },
      {
        key: 'drumCrossAmt',
        label: 'Cross bleed',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far each amplifier leans across. All the way over is a full swap — the kick fires on snare steps, the noise swells on kicks, and a hat tick puts a pitch blip through the kick.',
      },
    ],
  },
  {
    name: 'FM chip',
    place: 'Sources',
    sliders: [
      {
        key: 'fmLevel',
        label: 'Level',
        role: 'level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the FM chip is in the source mix. It has no keyboard and no sequencer of its own — somebody soldered its key input onto the toy’s gate line, so it plays whatever strikes a note over there: the demo song, your hands, a controller, or a drum hit that came back round. It runs off the same rail too, so starving the toy dives its pitch and drags its envelopes out.',
      },
      {
        key: 'fmVoice',
        label: 'Voice',
        min: 0,
        max: FM_VOICE_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FM_VOICE_NAMES,
        help: 'Which of the eight patches under the voice buttons the processor sends the chip. A patch is eight bytes written into the register file, not a mode the chip is put into — so pressing a voice button is a moment where a cut data line can land, and the patch you get is the one the wires let through.',
      },
      {
        key: 'fmBright',
        label: 'Brightness',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the modulator is into the carrier, which on a two-operator chip is the whole of the tone control: down is a sine, up is the harmonics piling on. It rides out with the patch as one of those eight bytes, so moving it is another write for a fault to catch.',
      },
      {
        key: 'fmFeedback',
        label: 'Feedback',
        min: 0,
        max: 7,
        step: 1,
        unit: '',
        help: 'How much of the modulator goes back into itself, three bits of it as the part had. Past about five the operator stops making harmonics and starts making noise, which is where the chip’s own drum sounds came from.',
      },
      {
        key: 'fmLength',
        label: 'Note length',
        min: 0.02,
        max: 4,
        step: 0.01,
        unit: 's',
        curve: 'log',
        help: 'How long the processor waits before writing the key back up. A trigger line carries a strike and nothing else, so the length of the note is a decision something has to make and this is where it is made. Your hand overrides it — letting a key go sends the release early — and a cut data line overrides it the other way, by making sure the write never lands.',
      },
      {
        key: 'fmEffect',
        label: 'Effect',
        min: 0,
        max: FM_EFFECT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FM_EFFECT_NAMES,
        shy: true,
        help: 'The effect ROM: a bird, surf, wind, a siren or crickets, none of which is a sample — there is no sample memory on the board. Each is a little program in the processor firing register writes at the synthesiser, hundreds a second on the weather, which makes an effect far and away the busiest thing the bus ever carries. A note is four writes; a bird call never stops, so a cut line lands on every one of them and the corruption never lets up while the gesture keeps its own time. It borrows the fourth channel and the patch registers to do it, so the keyboard is down to three voices and plays in the effect’s voice — until you let the button go and the processor sends the voice again. Which is also why *Voice*, *Bright* and *Feedback* sit still while a script runs: the driver has one instrument to select and the effect is holding it, so those knobs only land once the button comes up.',
      },
      {
        key: 'fmDataLine',
        label: 'Data line',
        min: 0,
        max: 8,
        step: 1,
        unit: '',
        choices: lineNames('D', 8),
        shy: true,
        help: 'Which of the eight wires carrying bytes to the register file the knife found. This is the bend the FM keyboards are known for, and it is not a malfunction: the chip receives a byte with one bit wrong and executes it perfectly, then goes on executing it, because a register holds what it was last told. So a fault here does not pass — it accumulates. Patches come out wrong and stay wrong, a channel sits at the wrong volume, pitches land on a lattice, and if the bit carrying the key going up cannot go low, the note never ends.',
      },
      {
        key: 'fmDataFault',
        label: 'Data fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'What happened to the wire — the same four things a knife does to any trace. Cut leaves the pin floating and the bit goes stale, carrying whatever the byte before had in it, which on a bus this busy is a different wrong answer every write. To ground and to +V nail the bit for every byte the processor sends.',
      },
      {
        key: 'fmAddrLine',
        label: 'Address line',
        min: 0,
        max: 6,
        step: 1,
        unit: '',
        choices: lineNames('A', 6),
        shy: true,
        help: 'Which of the six wires choosing the register the knife found. The byte arrives intact and is filed in the wrong place, which is the more violent of the two: a frequency written into an envelope register, a key-on written into a waveform. It also means whatever should have gone there never did, so the chip goes on playing the last thing it was told about that register.',
      },
      {
        key: 'fmAddrFault',
        label: 'Address fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'The same four things, on the address side. A0 held low files every odd register on top of the even one below it, so the four channels stop having frequencies of their own; the higher lines throw whole banks on top of each other.',
      },
      {
        key: 'fmBusCut',
        label: 'Cut depth',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far through the trace the knife went — the cut fault is the only one that reads it. All the way and the bit holds whatever was last on it. Back it off and the line still carries some of the time, so most writes land and the occasional one does not: a patch that is nearly right, a note in ten that hangs.',
      },
      {
        key: 'fmStrobe',
        label: 'Strobe slip',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        shy: true,
        help: 'The pulse that tells the address latch to take what is on the wires, and how often it comes out too narrow to be caught. Nothing is corrupted here — both bytes arrive intact and the latch simply does not clock, so a perfectly good value commits to whichever register the last pulse that landed had named. Which is a fault no cut wire can imitate: every byte involved is right, and they are only paired one write late. Turn it up and the latch slips further, because a latch that misses holds rather than skips — two misses running is two writes of lag, and a strobe that never lands is the whole run piling into one register. It bites hardest on the effects, where the processor writes the same short run of registers hundreds of times a second: shift that by one and every frequency byte lands in the register carrying the key.',
      },
    ],
  },
  {
    name: 'Chaos osc',
    place: 'Sources',
    sliders: [
      {
        key: 'oscLevel',
        label: 'Level',
        role: 'level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the oscillator pair is in the source mix.',
      },
      {
        key: 'oscAHz',
        label: 'Osc A',
        min: 20,
        max: 4000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'The audible oscillator.',
      },
      {
        key: 'oscBHz',
        label: 'Osc B',
        min: 0.1,
        max: 4000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'The modulator. Sub-audio rates warble and siren; audio rates tear A into sidebands.',
      },
      {
        key: 'oscXmod',
        label: 'Cross-mod',
        min: 0,
        max: 2000,
        step: 1,
        unit: 'Hz',
        curve: 'log',
        help: 'How many Hz of deviation B drags A through. Turn it up and the pair stops being two pitches.',
      },
      {
        key: 'oscShape',
        label: 'Shape',
        min: 0,
        max: 2,
        step: 1,
        unit: '',
        choices: ['square', 'saw', 'pulse'],
        help: 'Waveform of both oscillators.',
      },
      {
        key: 'oscStarve',
        label: 'Starve',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Sags the oscillator supply. Loud output drags pitch and amplitude down until it stalls, recovers, and stalls again — motorboating for free.',
      },
    ],
  },
  {
    name: 'Noise & crackle',
    place: 'Sources',
    sliders: [
      {
        key: 'noiseLevel',
        label: 'Noise',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'White noise level into the chain.',
      },
      {
        key: 'noiseColor',
        label: 'Color',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Tilts the noise dark (rumble) or bright (hiss).',
      },
      {
        key: 'crackleAmp',
        label: 'Crackle',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        shy: true,
        help: 'Dirty-pot contact crackle: random spikes rung through a resonant filter.',
      },
      {
        key: 'crackleRate',
        label: 'Crackle rate',
        min: 0,
        max: 200,
        step: 1,
        unit: '/s',
        help: 'How often the contact sparks.',
      },
    ],
  },
  {
    name: 'Mic & sample',
    place: 'Sources',
    sliders: [
      {
        key: 'micLevel',
        label: 'Mic',
        min: 0,
        max: 2,
        step: 0.01,
        unit: '',
        help: 'Microphone gain into the patch point. Watch speaker feedback — or use it.',
      },
      {
        key: 'micPatch',
        label: 'Mic patch',
        min: 0,
        max: 6,
        step: 1,
        unit: '',
        choices: [
          'mix',
          'chip rail',
          'osc FM',
          'delay fb',
          'ring car',
          'drum trig',
          'glitch trig',
        ],
        help: 'Where the mic wire is soldered: the mix bus, the toy supply rail (yell to brown it out), oscillator A’s FM input, the delay feedback path, the ring mod carrier, or the trigger line of the drum machine or glitch buffer — clap at it and the circuit fires.',
      },
      {
        key: 'sampleLevel',
        label: 'Sample',
        min: 0,
        max: 2,
        step: 0.01,
        unit: '',
        help: 'Level of the dropped audio file, looping through the chain.',
      },
      {
        key: 'sampleSpeed',
        label: 'Speed',
        min: -4,
        max: 4,
        step: 0.01,
        unit: '×',
        help: 'Playback speed. Negative runs backwards; zero freezes on the current spot.',
      },
      {
        key: 'sampleTrig',
        label: 'Struck by',
        min: 0,
        max: VOICE_LABELS.length + 3,
        step: 1,
        unit: '',
        choices: ['off', ...VOICE_LABELS, 'any hit', 'key', 'mic'],
        help: 'Which trigger line drops the needle back at the top of the file: one of the kit’s voices, any hit at all, a note off the keyboard, or a shout in the mic. With one-shot beside it, the file becomes a seventh drum voice — whatever you dropped, played from the start on every hit. Off, it loops the way it always did.',
      },
      {
        key: 'sampleMode',
        label: 'Ending',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['loop', 'one-shot'],
        help: 'What happens at the end of the file: round again, or stop there and wait to be struck. Backwards, the end is the top of the file.',
      },
    ],
  },
]
