import type { Controls } from '../../controls'
import { FAULT, FAULT_NAMES, lineNames } from '../../dsp/bus'
import { FM_EFFECT_NAMES } from '../../dsp/stages/fmEffects'
import { fallSecs, FM_VOICE_NAMES, MULT } from '../../dsp/stages/fmVoices'
import {
  ROM_ADDR_LINES,
  ROM_DATA_LINES,
  ROM_NAMES,
  ROMS,
} from '../../dsp/stages/roms'
import { ADDR_LINES, GRID_ROWS, N_DRUM_VOICES, VOICE_LABELS } from '../../drums'
import type { Group, SliderDef } from './types'

// The toy has no sync input, so locking it to the kit means picking the crystal
// speed at which the ROM's own steps divide into the kit's. Which multiple of
// that speed you want is a pitch decision as much as a timing one — the same
// knob is both — so it lands on the one nearest where the crystal already sits.
const LOCK_MULTIPLES = [
  1 / 8,
  1 / 6,
  1 / 4,
  1 / 3,
  1 / 2,
  2 / 3,
  1,
  3 / 2,
  2,
  3,
]

function lockToKit(c: Controls, def: SliderDef): number {
  const romHz = ROMS[Math.round(c.chipTune)]?.stepHz ?? 8
  const base = ((c.drumBpm / 60) * 4) / romHz
  const off = (v: number) => Math.abs(Math.log(v / c.chipClockX))
  const speeds = LOCK_MULTIPLES.map(m => base * m).filter(
    v => v >= def.min && v <= def.max,
  )
  // Nothing in range is a tempo the crystal cannot reach; the knob stays put.
  if (speeds.length === 0) return c.chipClockX
  return speeds.reduce((best, v) => (off(v) < off(best) ? v : best))
}

// The two panel controls the keyboard never had a button for, named in the
// units the register file counts in: a ratio is an index into the part's own
// multiplier table, and a decay is one of sixteen rates off the same divider
// everything else on the board runs on.
const RATIO_CHOICES = ['as patched', ...MULT.map(m => `${m}×`)]
const DECAY_CHOICES = [
  'as patched',
  ...Array.from({ length: 16 }, (_, i) => {
    const secs = fallSecs(15 - i)
    return secs < 0.1 ? `${Math.round(secs * 1000)} ms` : `${secs.toFixed(2)} s`
  }),
]

// Cut depth is how far through a trace the knife went, and the cut fault is the
// only one of the four that reads it — so the row waits until one of a chip's
// buses has a wire on it with that fault picked. One depth serves every bus on
// a chip, which is why it asks about all of them rather than one.
const cutOn =
  (...buses: [line: keyof Controls, fault: keyof Controls][]) =>
  (c: Controls) =>
    buses.some(([line, fault]) => c[line] > 0 && c[fault] === FAULT.cut)

const fmCutSomewhere = cutOn(
  ['fmDataLine', 'fmDataFault'],
  ['fmAddrLine', 'fmAddrFault'],
  ['fmWaveLine', 'fmWaveFault'],
)
const chipCutSomewhere = cutOn(
  ['chipDataLine', 'chipDataFault'],
  ['chipAddrLine', 'chipAddrFault'],
)
const drumCutSomewhere = cutOn(
  ['drumDataLine', 'drumDataFault'],
  ['drumAddrLine', 'drumAddrFault'],
)

export const SOURCE_GROUPS: Group[] = [
  {
    name: 'Toy keyboard',
    place: 'Sources',
    folded: ['the supply underneath', 'knife on the bus'],
    sliders: [
      {
        key: 'chipLevel',
        label: 'Level',
        role: 'level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the toy keyboard chip is in the source mix.',
      },
      {
        key: 'chipTune',
        label: 'Tune ROM',
        min: 0,
        max: ROM_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: ROM_NAMES,
        help: 'Which demo song the chip plays from ROM. Each ROM carries its own sequencer rate, so the clock and the starve bend hit them differently.',
      },
      {
        key: 'chipTone',
        label: 'Tone',
        min: 0,
        max: 3,
        step: 1,
        unit: '',
        choices: ['organ 1/2', 'reed 1/4', 'clav 1/8', 'buzz 1/16'],
        help: 'Which width of pulse the tone selector taps off the divider chain. Narrow taps null different harmonics and thin out — the chip never levelled them, so they get quieter as they get reedier.',
      },
      {
        key: 'chipAccomp',
        label: 'Auto bass-chord',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The accompaniment section: bass on the step, chord stab on the offbeat, under whichever demo song is running. It reads the chord off the melody and picks major or minor from the ROM’s own notes. Same divider, same rail — starve the chip and the backing band goes down with it.',
      },
      {
        key: 'chipClockX',
        label: 'Clock',
        min: 0.05,
        max: 16,
        step: 0.01,
        unit: '×',
        curve: 'log',
        help: 'Drags the master clock crystal. Everything the chip does — pitch, tempo, envelopes — slurs together.',
        action: {
          label: 'lock',
          title:
            'set the crystal to the nearest speed at which this ROM’s steps divide into the kit’s, so the tune and the pattern line up. It is the same knob as the pitch, so locking moves that too — and nothing holds it there: crystal drift, a starving rail or a wire on the clock will walk it off again',
          value: lockToKit,
        },
      },
      {
        key: 'chipBendSpot',
        label: 'Bend spot',
        min: 0,
        max: 4,
        step: 1,
        unit: '',
        choices: ['off', 'clock', 'counter', 'bias', 'gate'],
        help: 'Where the virtual pot is soldered onto the die: clock feedback, program counter, DAC bias, or the gate line. Each spot breaks differently.',
      },
      {
        key: 'chipBendPot',
        needs: c => c.chipBendSpot > 0,
        label: 'Bend pot',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Turns the pot on the chosen bend spot. Zero is an open circuit; up is a harder short.',
      },
      {
        key: 'chipDrift',
        label: 'Crystal drift',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far the chip’s clock wanders off the ratio you set it to. The toy runs on its own crystal, so it drifts against the drum machine and never quite locks — two rates a hair apart, phasing in and out for as long as you leave it.',
      },
      {
        key: 'chipStarve',
        part: 'the supply underneath',
        label: 'Starve',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Sags the shared toy supply rail. Pitch dives, notes collapse, and past the brownout threshold the watchdog reboots the chip — the tune keeps restarting. One oscillator clocks the whole chip, so a sag that lasts takes the tempo down with the pitch: the tune slurs and slows together, the way a tape does. A dip inside a single note is too quick for the timing pin to notice, which is why a chord sags without the beat stumbling.',
      },
      {
        key: 'chipBattery',
        part: 'the supply underneath',
        label: 'Batteries',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How flat the cells are. The rail never comes back to full, so the toy runs low and slow — pitch, tempo and the drum machine with it — and every note sags it further with nothing starving it. Far enough down and a chord alone browns the chip out.',
      },
      {
        key: 'chipLeadR',
        part: 'the supply underneath',
        label: 'Lead resistance',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'A resistor in series with the cells. Flat cells are two things at once — a voltage that has dropped and a resistance that has climbed — and this is the second without the first: the rail still rests where it always rested, and every note has to pull its supply through the resistor to get there. So it sags on the attack and climbs back between hits, as far as the Reservoir gives it time to travel. It is the difference between a toy that is running out and a toy that whoops on every note and never runs out at all, and it is the one to reach for over Batteries if what you want is the swoop rather than the decline.',
      },
      {
        key: 'chipCap',
        part: 'the supply underneath',
        label: 'Reservoir',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How much of the board’s own capacitance sits behind whatever the starve is pulling on. It moves no voltage — it decides how long the rail takes to get there. At zero the supply settles inside a millisecond and starve is a step you land on; wound up, the same starve takes a third of a second to fall and you hear the whole dive, slowing as it goes. Everything on the rail goes with it: pitch, tempo, envelopes. Far enough up and the reboot stops snapping the rail back at all, so the tune is struck high, dragged down, cut off, and struck high again.',
      },
      {
        key: 'chipClipHz',
        part: 'the supply underneath',
        label: 'Clip chatter',
        min: 0,
        max: 40,
        step: 0.1,
        unit: 'Hz',
        help: 'Bare metal dragged across the pads, and how often it finds one. Each touch chokes hard for a few tens of milliseconds and lets go, and what it chokes leaves at whatever rate the Reservoir allows — so this is the dive that repeats without you doing anything. A choke rather than a short: crash the rail to ground instead and the pitch is simply gone and then simply back, two steps with the dive missing. It is a hand holding a paperclip rather than a switch, so the rate is an average and the fault cluster decides how much it bunches.',
      },
      {
        key: 'chipClipClock',
        needs: c => c.chipClipHz > 0,
        part: 'the supply underneath',
        label: 'Clip on clock',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Whether the clip lands on the timing pin instead of the supply — and it is the difference between a sag and a dive. Starving the rail is worth two thirds of an octave before the chip stops running at all; a capacitor hung on the oscillator divides the clock instead, and division has no such ceiling. Four octaves at the top, travelling at whatever rate the Reservoir charges, with the whole timebase going along: tune, tempo and envelopes together, the melody arriving somewhere under the bottom of its own keyboard. Needs Clip chatter to have something to land with.',
      },
      {
        key: 'chipLatch',
        part: 'the supply underneath',
        label: 'Latch-up',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How often a brownout jams the chip instead of rebooting it. A latched CMOS die holds whatever note was sounding and keeps drawing current, so it screams one note into the floor until the rail gives out under it and the watchdog gets its power cycle.',
      },
      {
        key: 'chipDataLine',
        part: 'knife on the bus',
        label: 'Data line',
        min: 0,
        max: ROM_DATA_LINES,
        step: 1,
        unit: '',
        choices: lineNames('D', ROM_DATA_LINES),
        shy: true,
        help: 'Which wire between the ROM and the divider the knife found. The chip stores a note code rather than a pitch, so the low lines are small intervals and the high ones are octaves — D0 is a semitone, D2 a major third, D5 the better part of three octaves. Nothing about it is random: one wire wrong is the same wrong note every time that step comes round, so the song keeps its rhythm and its shape and becomes a different song.',
      },
      {
        key: 'chipDataFault',
        needs: c => c.chipDataLine > 0,
        part: 'knife on the bus',
        label: 'Data fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'What happened to the wire. Cut leaves the pin floating, so the bit goes stale and carries whatever the word before had in it. To ground takes that bit out of every note the chip reads. To +V puts it into every note — including the ones that were not notes, because a rest is only a code, and a code with a bit forced into it is a pitch. Bridged solders the line to its neighbour so the two can no longer disagree, and the melody comes out in clumps.',
      },
      {
        key: 'chipAddrLine',
        part: 'knife on the bus',
        label: 'Address line',
        min: 0,
        max: ROM_ADDR_LINES,
        step: 1,
        unit: '',
        choices: lineNames('A', ROM_ADDR_LINES),
        shy: true,
        help: 'Which wire between the program counter and the ROM the knife found. The counter still counts and the tempo never moves; the ROM is simply handed the wrong step. A0 plays the tune in swapped pairs, A3 held low locks it into the bottom eight steps for good, and a line this ROM never drives does nothing at all — a sixteen-step song has no A4 for you to find.',
      },
      {
        key: 'chipAddrFault',
        needs: c => c.chipAddrLine > 0,
        part: 'knife on the bus',
        label: 'Address fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'The same four things, on the address side. Cut leaves the step stale, so the tune stutters on notes it has already played; ground and +V nail that address bit for every read, which folds the song into half of itself; bridged ties two addresses together and the melody arrives in clumps of two and four.',
      },
      {
        key: 'chipBusCut',
        needs: chipCutSomewhere,
        part: 'knife on the bus',
        label: 'Cut depth',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far through the trace the knife went — the cut fault is the only one that reads it. All the way and the pin floats for good: the bit holds whatever the last word left on it and the song settles into one consistent mangling. Back it off and the trace still carries some of the time, so the bit is right on some reads and a word old on others, and the melody flickers between two versions of itself.',
      },
    ],
  },
  {
    name: 'Toy drums',
    place: 'Sources',
    folded: ['the converter', 'triggers and cross-patch', 'knife on the bus'],
    editor: {
      kind: 'drums',
      keys: GRID_ROWS.flatMap(r => [r.key, r.len]),
    },
    sliders: [
      {
        key: 'drumLevel',
        label: 'Level',
        role: 'level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the toy drum machine is in the source mix.',
      },
      {
        key: 'drumBpm',
        label: 'Tempo',
        min: 10,
        max: 3000,
        step: 1,
        unit: 'bpm',
        curve: 'log',
        help: 'Sequencer clock. Musical at the bottom; drag it far past the panel legend and the pattern smears into a buzz.',
      },
      {
        key: 'drumSwing',
        label: 'Swing',
        min: 0,
        max: 0.9,
        step: 0.01,
        unit: '',
        help: 'Holds every offbeat step back and takes the time off the step after, so the pattern shuffles without the tempo moving.',
      },
      {
        key: 'drumTune',
        label: 'Tune',
        min: 0.125,
        max: 8,
        step: 0.01,
        unit: '×',
        curve: 'log',
        help: 'The pitch trimmer inside the kit: every struck voice moves together. It rides on the supply, so starving the toy drags it down again. At the bottom of the travel the kick is under hearing and arrives as the thump of its own envelope; at the top the whole kit is a handful of tick marks.',
      },
      {
        key: 'drumDecay',
        label: 'Decay',
        min: 0.25,
        max: 16,
        step: 0.01,
        unit: '×',
        curve: 'log',
        help: 'Stretches or chokes every envelope at once. Short is a click track; long lets the kick and toms run into each other. Past about eight the kick stops being a hit and becomes a note held under the pattern — and it leans on the supply for as long as it rings.',
      },
      {
        key: 'drumBits',
        part: 'the converter',
        label: 'Bit depth',
        min: 2,
        max: 16,
        // A DAC has a whole number of bits. The crusher's own word length is
        // fractional on purpose — it is a knob sweeping a step size — but this
        // one is a part the kit was built with.
        step: 1,
        unit: 'bit',
        help: 'Word length of the one cheap DAC the whole kit shares. Stock is 7 — wind it down and the tails turn to gravel before the hits do.',
      },
      {
        key: 'drumLadder',
        part: 'the converter',
        label: 'Ladder',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How much of that converter’s error you are hearing. A ladder halves its weight at every rung down the word, and a kit like this got its rungs off a reel nobody measured, so the steps come out uneven — and unevenly, because the error scales with the rung: half the tolerance of the top resistor is an enormous number of counts. That is why a cheap converter is not hiss. It is one lurch, at the code where every bit changes at once, and for a signal that code is the zero crossing — so it lands hardest on whatever is quietest, and a tail on its way out is nothing but zero crossings. Bit depth moves where the word is tapped off the ladder, so it changes the character of the error as well as the size.',
      },
      {
        key: 'drumLadderTol',
        part: 'the converter',
        label: 'Part grade',
        min: 0,
        max: 0.6,
        step: 0.005,
        unit: '',
        help: 'What the reel those resistors came off was sold as — 15% is the bin this kit was built out of. Which rungs are long and which are short is soldered in and does not move; this is how far out they are, so the whole lurch scales without changing where on the signal it lands. Ladder is how much of it reaches the output; this is how bad the parts were to begin with.',
      },
      {
        key: 'drumOverflow',
        part: 'the converter',
        label: 'Overflow',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['off', 'wrap'],
        help: 'What the converter does with a sum that will not fit its word. The accumulator behind the ladder is as wide as the word and no wider, and a cheap one rolls over rather than stopping at the top: a step stacking four voices under an accent comes out inside-out, while the quiet steps either side of it are untouched. The fold is the pattern’s own dynamics rather than a setting, so it moves when Level, Decay or the accent row moves, and a kit that wraps can never leave the box past full scale. Off, the sum does, and the limiter at the end of the chain is what deals with it.',
      },
      {
        key: 'drumRetrigHz',
        part: 'triggers and cross-patch',
        label: 'Retrigger',
        min: 0,
        max: 4000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'Retriggers the current step at this rate. Slow is a machine-gun roll; past ~40 Hz the retrigger period becomes the pitch and the drum screams.',
      },
      {
        key: 'drumTrigFloor',
        part: 'triggers and cross-patch',
        label: 'Trigger floor',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far a voice has to have drained before the one-shot behind it will answer the trigger line again. At nothing every pulse strikes, which is what a retrigger at audio rate has always been. Wind it up and a line hammered faster than a voice can empty comes out divided: the kit answers a 300 Hz hammer with a rattle of its own, at a rate *Decay* sets rather than *Retrigger* — and one that slows as the supply sags, because the envelope is counted off the same oscillator the tempo is. All the way up, a voice will not strike again until it has stopped sounding. It sits on the trigger line rather than in the bend, so the sequencer, the pads, the mic and the keyboard queue behind it too.',
      },
      {
        key: 'drumCross',
        part: 'triggers and cross-patch',
        label: 'Cross-patch',
        min: 0,
        max: 5,
        step: 1,
        unit: '',
        choices: [
          'off',
          'kick/snare',
          'snare/hat',
          'kick/hat',
          'rotate',
          'whole kit',
        ],
        help: 'Bridges two voices’ envelope pins so each amplifier hears the wrong envelope. Rotate passes the original three around the ring; whole kit passes all six, so the cowbell rings on a kick and the clap answers a tom.',
      },
      {
        key: 'drumCrossAmt',
        needs: c => c.drumCross > 0,
        part: 'triggers and cross-patch',
        label: 'Cross bleed',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far each amplifier leans across. All the way over is a full swap — the kick fires on snare steps, the noise swells on kicks, and a hat tick puts a pitch blip through the kick.',
      },
      {
        key: 'drumAddrLine',
        part: 'knife on the bus',
        label: 'Address line',
        min: 0,
        max: ADDR_LINES,
        step: 1,
        unit: '',
        choices: lineNames('A', ADDR_LINES),
        shy: true,
        help: 'Which of the four wires carrying a step number from the counter to the pattern memory the knife found. Nothing malfunctions: the counter still counts, the playhead on the grid still chases the step it always did, and a different cell of memory answers. A0 held low plays every step twice; A3 held high hands you the back half of the bar and never the front. A row’s length is the counter’s business rather than the memory’s, so a faulted address reaches cells a five-step row would never have played.',
      },
      {
        key: 'drumAddrFault',
        needs: c => c.drumAddrLine > 0,
        part: 'knife on the bus',
        label: 'Address fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'The same four things a knife does to any trace, on the side that chooses the step. Cut leaves the wire floating and the bit goes stale, carrying whatever the fetch before left on it, so the pattern flickers between two versions of itself. Bridged solders it to its neighbour and the steps collapse onto a lattice.',
      },
      {
        key: 'drumDataLine',
        part: 'knife on the bus',
        label: 'Data line',
        min: 0,
        max: N_DRUM_VOICES,
        step: 1,
        unit: '',
        choices: lineNames('D', N_DRUM_VOICES),
        shy: true,
        help: 'Which of the six wires carrying the word back the knife found — one wire a voice, in the order of the rows. To +V is that voice on every step the machine fetches, which is the machine-gun; to ground is a row you can see and cannot hear. This is the trigger line rather than an amplifier, so a bit forced high strikes the voice for real: it lights the row, stamps the trigger bus, and reaches everything soldered onto it — the sampler, the keyboard, the FM chip. The cross-patch beside it only ever lent an envelope.',
      },
      {
        key: 'drumDataFault',
        needs: c => c.drumDataLine > 0,
        part: 'knife on the bus',
        label: 'Data fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'The same four, on the side carrying the word. Bridged is the one worth knowing here: two voices soldered to each other come out only where both rows agree, so a busy pattern thins to what the pair have in common.',
      },
      {
        key: 'drumBusCut',
        needs: drumCutSomewhere,
        part: 'knife on the bus',
        label: 'Cut depth',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far through the trace the knife went — the cut fault is the only one that reads it. All the way and the wire holds whatever was last on it. Back it off and it still conducts sometimes: most fetches land, the occasional one does not, and the pattern comes apart a step at a time rather than all at once.',
      },
    ],
  },
  {
    name: 'FM chip',
    place: 'Sources',
    folded: ['inside the patch', 'knife on the bus'],
    sliders: [
      {
        key: 'fmLevel',
        label: 'Level',
        role: 'level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the FM chip is in the source mix. It has no keyboard and no sequencer of its own — somebody soldered its key input onto the toy’s gate line, so it plays whatever strikes a note over there: the demo song, your hands, a controller, or a drum hit that came back round. It runs off the same rail too, so starving the toy dives its pitch and drags its envelopes out.',
      },
      {
        key: 'fmVoice',
        label: 'Voice',
        min: 0,
        max: FM_VOICE_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FM_VOICE_NAMES,
        help: 'Which of the eight patches under the voice buttons the processor sends the chip. A patch is eight bytes written into the register file, not a mode the chip is put into — so pressing a voice button is a moment where a cut data line can land, and the patch you get is the one the wires let through.',
      },
      {
        key: 'fmBright',
        label: 'Brightness',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the modulator is into the carrier, which on a two-operator chip is the whole of the tone control: down is a sine, up is the harmonics piling on. It rides out with the patch as one of those eight bytes, so moving it is another write for a fault to catch.',
      },
      {
        key: 'fmFeedback',
        label: 'Feedback',
        min: 0,
        max: 7,
        step: 1,
        unit: '',
        help: 'How much of the modulator goes back into itself, three bits of it as the part had. Past about five the operator stops making harmonics and starts making noise, which is where the chip’s own drum sounds came from.',
      },
      {
        key: 'fmLength',
        label: 'Note length',
        min: 0.02,
        max: 4,
        step: 0.01,
        unit: 's',
        curve: 'log',
        help: 'How long the processor waits before writing the key back up, for a note nothing is holding: the demo song, a drum hit through the trigger patch, a kit line clipped on below. Those arrive as an edge and nothing else, so the length is a decision something has to make and this is where it is made. Your own hands are the exception — the gate says the key is still down, so the processor holds the note and writes it up when you let go, however long that is. What a held note does meanwhile is the patch’s business: four of the eight wait for the key, and the struck ones decay whatever your finger is doing. A cut data line overrides the lot, by making sure the write never lands.',
      },
      {
        key: 'fmStruck',
        label: 'Struck by',
        min: 0,
        max: N_DRUM_VOICES + 1,
        step: 1,
        unit: '',
        choices: ['off', ...VOICE_LABELS, 'any hit'],
        help: 'The kit’s trigger lines, clipped onto this chip’s key input alongside the keyboard’s. A drum machine has no notes to send — a trigger line carries a strike and nothing else — so the note is decided at this end: one per voice, in the kit’s own row order, a pentatonic apart, which is what turns a pattern written for drums into a riff. Every voice you clip on takes a channel while it rings, and there are four, so a busy grid steals its own notes. Accents come across as well, in the only place the register file has for them: an accented step is written at a different attenuation. Whatever the grid is doing, the FM chip is now playing it.',
      },
      {
        key: 'fmEffect',
        label: 'Effect',
        min: 0,
        max: FM_EFFECT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FM_EFFECT_NAMES,
        shy: true,
        help: 'The effect ROM: a bird, surf, wind, a siren or crickets, none of which is a sample — there is no sample memory on the board. Each is a little program in the processor firing register writes at the synthesiser, hundreds a second on the weather, which makes an effect far and away the busiest thing the bus ever carries. A note is four writes; a bird call never stops, so a cut line lands on every one of them and the corruption never lets up while the gesture keeps its own time. It borrows the fourth channel and the patch registers to do it, so the keyboard is down to three voices and plays in the effect’s voice — until you let the button go and the processor sends the voice again. Which is also why *Voice*, *Bright* and *Feedback* sit still while a script runs: the driver has one instrument to select and the effect is holding it, so those knobs only land once the button comes up.',
      },
      {
        key: 'fmModRatio',
        part: 'inside the patch',
        label: 'Mod ratio',
        min: 0,
        max: RATIO_CHOICES.length - 1,
        step: 1,
        unit: '',
        choices: RATIO_CHOICES,
        help: 'What the modulator runs at against the note, as a multiple of it. This and *Brightness* are the whole of two-operator FM: the ratio picks which harmonics the modulator can put there and brightness decides how many of them arrive. Whole numbers stay in tune with the note and land on its own harmonics — 1 for a fuller version of the same tone, 2 and 3 for reed and brass, 7 upward for bells and metal. The table is the part’s own, so it stops being a scale near the top and repeats: there is no 11 or 13 on this chip, and nothing between the steps, because a ratio here is four bits of a flags byte and nothing finer exists. Left at *as patched*, the voice keeps whatever it shipped with.',
      },
      {
        key: 'fmCarRatio',
        part: 'inside the patch',
        label: 'Car ratio',
        min: 0,
        max: RATIO_CHOICES.length - 1,
        step: 1,
        unit: '',
        choices: RATIO_CHOICES,
        help: 'The same table on the carrier, which moves the note itself rather than its colour — the operator you hear is the one running at this multiple, so 2 is the same patch an octave up. Set both ratios and what matters is the interval between them: 1 against 2 is a hollow octave, 2 against 3 a fifth, and anything where the modulator is not a whole multiple of the carrier makes sidebands that are not harmonics of anything, which is the clangorous end of the chip.',
      },
      {
        key: 'fmModDecay',
        part: 'inside the patch',
        label: 'Mod decay',
        min: 0,
        max: DECAY_CHOICES.length - 1,
        step: 1,
        unit: '',
        choices: DECAY_CHOICES,
        help: 'How long the modulator takes to fall away, which is what makes an FM note a bell or an organ: a bright attack that collapses to a sine in eighty milliseconds is a struck thing, and one that never collapses is a blown one. Sixteen rates, because the register holds four bits of it, and they are counted off the same divider as the tempo and the pitch — so starving the rail stretches this along with everything else and the times printed here are the times on a board with its supply intact.',
      },
      {
        key: 'fmDataLine',
        part: 'knife on the bus',
        label: 'Data line',
        min: 0,
        max: 8,
        step: 1,
        unit: '',
        choices: lineNames('D', 8),
        shy: true,
        help: 'Which of the eight wires carrying bytes to the register file the knife found. This is the bend the FM keyboards are known for, and it is not a malfunction: the chip receives a byte with one bit wrong and executes it perfectly, then goes on executing it, because a register holds what it was last told. So a fault here does not pass — it accumulates. Patches come out wrong and stay wrong, a channel sits at the wrong volume, pitches land on a lattice, and if the bit carrying the key going up cannot go low, the note never ends.',
      },
      {
        key: 'fmDataFault',
        part: 'knife on the bus',
        needs: c => c.fmDataLine > 0,
        label: 'Data fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'What happened to the wire — the same four things a knife does to any trace. Cut leaves the pin floating and the bit goes stale, carrying whatever the byte before had in it, which on a bus this busy is a different wrong answer every write. To ground and to +V nail the bit for every byte the processor sends.',
      },
      {
        key: 'fmAddrLine',
        part: 'knife on the bus',
        label: 'Address line',
        min: 0,
        max: 6,
        step: 1,
        unit: '',
        choices: lineNames('A', 6),
        shy: true,
        help: 'Which of the six wires choosing the register the knife found. The byte arrives intact and is filed in the wrong place, which is the more violent of the two: a frequency written into an envelope register, a key-on written into a waveform. It also means whatever should have gone there never did, so the chip goes on playing the last thing it was told about that register. Some of these lines do nothing while an effect runs, and that is the part rather than the control: a script only ever writes the fourth channel and the eight patch bytes, so the wires that only matter to the registers it never names have nothing to carry.',
      },
      {
        key: 'fmAddrFault',
        part: 'knife on the bus',
        needs: c => c.fmAddrLine > 0,
        label: 'Address fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        choices: FAULT_NAMES,
        help: 'The same four things, on the address side. A0 held low files every odd register on top of the even one below it, so the four channels stop having frequencies of their own; the higher lines throw whole banks on top of each other.',
      },
      {
        key: 'fmWaveLine',
        part: 'knife on the bus',
        label: 'Wave line',
        min: 0,
        max: 10,
        step: 1,
        unit: '',
        choices: lineNames('W', 10),
        shy: true,
        help: 'Which of the ten wires addressing the sine table the knife found. Nothing on this chip computes a sine — it looks one up, a quarter of a wave with two more bits of phase to build the rest — so the waveform is an address and an address can be cut. It is the opposite bend to the data lines: the processor never touches this bus, the operators read it eight times a sample, and nothing accumulates. The wires are weighted, so where you cut is the whole of it. W8 mirrors the quarter back on itself, and held, the quarter simply runs twice: the chip is still playing the note it was told and what comes out is an octave up with a cliff in it. W9 is the sign, and a sine with no sign is a rectified one — all octave, no fundamental. Below those the wires only move the phase a fraction of a step each, so the bottom of the bus is a wire you can cut and hear almost nothing, which is what a binary bus is.',
      },
      {
        key: 'fmWaveFault',
        part: 'knife on the bus',
        needs: c => c.fmWaveLine > 0,
        label: 'Wave fault',
        min: 0,
        max: FAULT_NAMES.length - 1,
        step: 1,
        unit: '',
        shy: true,
        choices: FAULT_NAMES,
        help: 'The same four things, on the wave ROM’s address. Cut is the strange one: a severed trace is a pin nothing drives again, so it holds the last phase bit that reached it and every read after that comes back with that bit stale — the line stops being part of the wave at all. Back the cut depth off and the trace still conducts sometimes, so the bit is right on some reads and stale on others and the wave flickers between two shapes at the rate the operators come round. To ground and to +V nail it for every read, which is a waveform rather than a fault.',
      },
      {
        key: 'fmBusCut',
        part: 'knife on the bus',
        needs: fmCutSomewhere,
        label: 'Cut depth',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far through the trace the knife went — the cut fault is the only one that reads it. All the way and the bit holds whatever was last on it. Back it off and the line still carries some of the time, so most writes land and the occasional one does not: a patch that is nearly right, a note in ten that hangs.',
      },
      {
        key: 'fmStrobe',
        part: 'knife on the bus',
        label: 'Strobe slip',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        shy: true,
        help: 'The pulse that tells the address latch to take what is on the wires, and how often it comes out too narrow to be caught. Nothing is corrupted here — both bytes arrive intact and the latch simply does not clock, so a perfectly good value commits to whichever register the last pulse that landed had named. Which is a fault no cut wire can imitate: every byte involved is right, and they are only paired one write late. Turn it up and the latch slips further, because a latch that misses holds rather than skips — two misses running is two writes of lag, and a strobe that never lands is the whole run piling into one register. It bites hardest on the effects, where the processor writes the same short run of registers hundreds of times a second: shift that by one and every frequency byte lands in the register carrying the key.',
      },
    ],
  },
  {
    name: 'Chaos osc',
    place: 'Sources',
    sliders: [
      {
        key: 'oscLevel',
        label: 'Level',
        role: 'level',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How loud the oscillator pair is in the source mix.',
      },
      {
        key: 'oscAHz',
        label: 'Osc A',
        min: 20,
        max: 12000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'The audible oscillator.',
      },
      {
        key: 'oscBHz',
        label: 'Osc B',
        min: 0.1,
        max: 12000,
        step: 0.1,
        unit: 'Hz',
        curve: 'log',
        help: 'The modulator. Sub-audio rates warble and siren; audio rates tear A into sidebands.',
      },
      {
        key: 'oscXmod',
        label: 'Cross-mod',
        min: 0,
        max: 8000,
        step: 1,
        unit: 'Hz',
        curve: 'log',
        help: 'How many Hz of deviation B drags A through. Turn it up and the pair stops being two pitches. Past a few thousand the deviation is wider than the carrier, so what comes out is sidebands with nothing in the middle.',
      },
      {
        key: 'oscShape',
        label: 'Shape',
        min: 0,
        max: 2,
        step: 1,
        unit: '',
        choices: ['square', 'saw', 'pulse'],
        help: 'Waveform of both oscillators.',
      },
      {
        key: 'oscStarve',
        label: 'Starve',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Sags the oscillator supply. Loud output drags pitch and amplitude down until it stalls, recovers, and stalls again — motorboating for free.',
      },
    ],
  },
  {
    name: 'Noise & crackle',
    place: 'Sources',
    sliders: [
      {
        key: 'noiseLevel',
        label: 'Noise',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'White noise level into the chain.',
      },
      {
        key: 'noiseColor',
        label: 'Color',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Tilts the noise dark (rumble) or bright (hiss).',
      },
      {
        key: 'crackleAmp',
        label: 'Crackle',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        shy: true,
        help: 'Dirty-pot contact crackle: random spikes rung through a resonant filter.',
      },
      {
        key: 'crackleRate',
        label: 'Crackle rate',
        min: 0,
        max: 2000,
        step: 1,
        unit: '/s',
        help: 'How often the contact sparks. Sparse is a bad joint; wound right up the sparks stop arriving one at a time and the resonance behind them becomes a tone.',
      },
    ],
  },
  {
    name: 'Sampler',
    place: 'Sources',
    sliders: [
      {
        key: 'sampleLevel',
        label: 'Level',
        role: 'level',
        min: 0,
        max: 2,
        step: 0.01,
        unit: '',
        help: 'Level of the dropped audio file, looping through the chain.',
      },
      {
        key: 'sampleSpeed',
        label: 'Speed',
        min: -4,
        max: 4,
        step: 0.01,
        unit: '×',
        help: 'Playback speed. Negative runs backwards; zero freezes on the current spot.',
      },
      {
        key: 'sampleTrig',
        label: 'Struck by',
        min: 0,
        max: VOICE_LABELS.length + 3,
        step: 1,
        unit: '',
        choices: ['off', ...VOICE_LABELS, 'any hit', 'key', 'mic'],
        help: 'Which trigger line drops the needle back at the top of the file: one of the kit’s voices, any hit at all, a note off the keyboard, or a shout in the mic. With one-shot beside it, the file becomes a seventh drum voice — whatever you dropped, played from the start on every hit. Off, it loops the way it always did.',
      },
      {
        key: 'sampleMode',
        label: 'Ending',
        min: 0,
        max: 1,
        step: 1,
        unit: '',
        choices: ['loop', 'one-shot'],
        help: 'What happens at the end of the file: round again, or stop there and wait to be struck. Backwards, the end is the top of the file.',
      },
    ],
  },
  // Not a channel. On one of its seven settings the mic reaches the mix, and on
  // the other six it is soldered into the middle of the board — so it gets a
  // group of its own, and the map draws it as the patch wire it actually is.
  {
    name: 'Mic',
    place: 'Sources',
    sliders: [
      {
        key: 'micLevel',
        label: 'Mic',
        role: 'level',
        min: 0,
        max: 2,
        step: 0.01,
        unit: '',
        help: 'Microphone gain into the patch point. Watch speaker feedback — or use it.',
      },
      {
        key: 'micPatch',
        label: 'Mic patch',
        min: 0,
        max: 6,
        step: 1,
        unit: '',
        choices: [
          'mix',
          'chip rail',
          'osc FM',
          'delay fb',
          'ring car',
          'drum trig',
          'glitch trig',
        ],
        help: 'Where the mic wire is soldered: the mix bus, the toy supply rail (yell to brown it out), oscillator A’s FM input, the delay feedback path, the ring mod carrier, or the trigger line of the drum machine or glitch buffer — clap at it and the circuit fires.',
      },
    ],
  },
]
