import type { Group } from './types'

export const TAPE_GROUPS: Group[] = [
  {
    name: 'Tape machine',
    place: 'Tape',
    sliders: [
      {
        key: 'tapeMix',
        label: 'To tape',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How much of the board you hear through the machine rather than straight off the bus. The dry side runs down the same nominal head delay, so this only combs once the transport wobbles.',
      },
      {
        key: 'tapeSpeed',
        label: 'Speed',
        min: 0,
        max: 2,
        step: 1,
        unit: '',
        choices: ['3¾ ips', '7½ ips', '15 ips'],
        help: 'Moves the whole machine at once: head-gap loss, the replay bump, hiss level, wow rate and how long a spool wrap takes to come back round. Slow is dark, noisy and unsteady.',
      },
      {
        key: 'tapeDrive',
        label: 'Level',
        role: 'level',
        min: -12,
        max: 15,
        step: 0.5,
        unit: 'dB',
        help: 'Record level. Highs hit the oxide through a pre-emphasis curve and come back through its inverse, so they saturate first — transients round off before anything sounds distorted.',
      },
      {
        key: 'tapeBias',
        label: 'Bias',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Underbiased is bright and crunchy; overbiased is dull and squashed. Distortion and top end move against each other.',
      },
      {
        key: 'tapeHyst',
        label: 'Hysteresis',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How far the field the medium is already carrying sits the record curve off centre. A clipper on its own is symmetrical: both halves of a wave meet the same shape, so it makes a third harmonic and never a second, which is the sound of something breaking up rather than of something warm. Tape is not symmetrical — it arrives at the gap magnetised, by more of it the harder it has been driven, and the two halves saturate against different amounts of that. The difference is the second harmonic, and because the offset rides the level rather than the note, it blooms up as you play into it and lets go when you back off. Under-bias leaves more of the field behind, so this and the bias multiply.',
      },
      {
        key: 'tapeBump',
        label: 'Head bump',
        min: 0,
        max: 1.5,
        step: 0.01,
        unit: '',
        help: 'The lift where the wavelength going past the replay head is the size of the head — a resonance a head has by being a head, down at the bottom of the band, and the low end every tape machine adds without being asked. Speed moves where it sits, because a wavelength is a distance and a faster tape lays it out longer; this is how much of it comes back. Stock is the machine as it was built, and winding it up is the tape’s own bottom octave rather than a tone control.',
      },
      {
        key: 'tapeHiss',
        label: 'Hiss',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Noise laid on the medium, not on the mix — the playback head colours it, the speed sets how loud it is, and it breathes a little with the signal.',
      },
      {
        key: 'tapeWow',
        label: 'Wow',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Capstan eccentricity plus slow drift, so the pitch never sits quite still.',
      },
      {
        key: 'tapeFlutter',
        label: 'Flutter',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The fast wobble, plus scrape flutter — the grain that comes off tape dragging past the head.',
      },
      {
        key: 'tapeDrop',
        label: 'Dropouts',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Shed oxide. Highs go before level does, which is what makes these sound like tape rather than like the power cutting.',
      },
      {
        key: 'tapePrint',
        label: 'Print-through',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The layer wound underneath bleeding into this one — a dull ghost of the signal, one spool wrap behind.',
      },
      {
        key: 'tapeAzimuth',
        label: 'Azimuth',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Head misalignment: the right channel lags and loses top end. Collapses to mono badly, on purpose.',
      },
    ],
  },
]
