import type { Group } from './types'

export const TAPE_GROUPS: Group[] = [
  {
    name: 'Tape machine',
    place: 'Tape',
    sliders: [
      {
        key: 'tapeMix',
        label: 'To tape',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How much of the board you hear through the machine rather than straight off the bus. The dry side runs down the same nominal head delay, so this only combs once the transport wobbles.',
      },
      {
        key: 'tapeSpeed',
        label: 'Speed',
        min: 0,
        max: 2,
        step: 1,
        unit: '',
        choices: ['3¾ ips', '7½ ips', '15 ips'],
        help: 'Moves the whole machine at once: head-gap loss, the replay bump, hiss level, wow rate and how long a spool wrap takes to come back round. Slow is dark, noisy and unsteady.',
      },
      {
        key: 'tapeDrive',
        label: 'Level',
        min: -12,
        max: 15,
        step: 0.5,
        unit: 'dB',
        help: 'Record level. Highs hit the oxide through a pre-emphasis curve and come back through its inverse, so they saturate first — transients round off before anything sounds distorted.',
      },
      {
        key: 'tapeBias',
        label: 'Bias',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Underbiased is bright and crunchy; overbiased is dull and squashed. Distortion and top end move against each other.',
      },
      {
        key: 'tapeHiss',
        label: 'Hiss',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Noise laid on the medium, not on the mix — the playback head colours it, the speed sets how loud it is, and it breathes a little with the signal.',
      },
      {
        key: 'tapeWow',
        label: 'Wow',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Capstan eccentricity plus slow drift, so the pitch never sits quite still.',
      },
      {
        key: 'tapeFlutter',
        label: 'Flutter',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The fast wobble, plus scrape flutter — the grain that comes off tape dragging past the head.',
      },
      {
        key: 'tapeDrop',
        label: 'Dropouts',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Shed oxide. Highs go before level does, which is what makes these sound like tape rather than like the power cutting.',
      },
      {
        key: 'tapePrint',
        label: 'Print-through',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The layer wound underneath bleeding into this one — a dull ghost of the signal, one spool wrap behind.',
      },
      {
        key: 'tapeAzimuth',
        label: 'Azimuth',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Head misalignment: the right channel lags and loses top end. Collapses to mono badly, on purpose.',
      },
    ],
  },
]
