import type { Group } from './types'

export const TAPE_GROUPS: Group[] = [
  {
    name: 'Tape machine',
    place: 'Tape',
    sliders: [
      {
        key: 'tapeMix',
        label: 'To tape',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'How much of the board you hear through the machine rather than straight off the bus. The dry side runs down the same nominal head delay, so this only combs once the transport wobbles.',
      },
      {
        key: 'tapeSpeed',
        label: 'Speed',
        min: 0,
        max: 2,
        step: 1,
        unit: '',
        choices: ['3¾ ips', '7½ ips', '15 ips'],
        help: 'Moves the whole machine at once: head-gap loss, the replay bump, hiss level, wow rate and how long a spool wrap takes to come back round. Slow is dark, noisy and unsteady.',
      },
      {
        key: 'tapeDrive',
        label: 'Level',
        role: 'level',
        min: -12,
        max: 15,
        step: 0.5,
        unit: 'dB',
        help: 'Record level. Highs hit the oxide through a pre-emphasis curve and come back through its inverse, so they saturate first — transients round off before anything sounds distorted.',
      },
      {
        key: 'tapeBias',
        label: 'Bias',
        min: -1,
        max: 1,
        step: 0.01,
        unit: '',
        split: { at: 0 },
        reads: v =>
          v === 0
            ? 'centred'
            : `${Math.abs(v).toFixed(2)} ${v < 0 ? 'under' : 'over'}`,
        help: 'Underbiased is bright and crunchy; overbiased is dull and squashed. Distortion and top end move against each other.',
      },
      {
        key: 'tapeHyst',
        label: 'Hysteresis',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Tape reaches the gap already magnetised, so a wave’s two halves saturate differently. That asymmetry is the second harmonic — warmth, not breakup — and it blooms as you play in and fades as you back off.',
      },
      {
        key: 'tapeBump',
        label: 'Head bump',
        min: 0,
        max: 1.5,
        step: 0.01,
        unit: '',
        help: 'The lift where the wavelength past the replay head is the size of the head — the low end every tape machine adds unasked, paid for by a scoop above it. Speed moves where both sit; this is how much comes back.',
      },
      {
        key: 'tapeSqueal',
        label: 'Squeal',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Sticky shed: the tape grabs the head, slips and grabs again, taking off on its own into a squeal. Speed sets the note, tension how hard. You hear it twice — the scream, and everything on the tape wobbling with it.',
      },
      {
        key: 'tapeHiss',
        label: 'Hiss',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Noise laid on the medium, not on the mix — the playback head colours it, the speed sets how loud it is, and it breathes a little with the signal.',
      },
      {
        key: 'tapeWow',
        label: 'Wow',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Capstan eccentricity plus slow drift, so the pitch never sits quite still.',
      },
      {
        key: 'tapeFlutter',
        label: 'Flutter',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The fast wobble, plus the scrape grain of tape dragging past the head. Same span and friction the Squeal knob takes over the edge — this is under the line, where it only rattles.',
      },
      {
        key: 'tapeDrop',
        label: 'Dropouts',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Shed oxide. Highs go before level does, which is what makes these sound like tape rather than like the power cutting — and a patch of it sits on one track, so a dropout takes a channel with it rather than the whole record.',
      },
      {
        key: 'tapePrint',
        label: 'Print-through',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'The layer wound underneath bleeding into this one — a dull ghost of the signal, one spool wrap behind.',
      },
      {
        key: 'tapeAzimuth',
        label: 'Azimuth',
        min: 0,
        max: 1,
        step: 0.01,
        unit: '',
        help: 'Head misalignment: the right channel lags and loses top end. Collapses to mono badly, on purpose.',
      },
    ],
  },
]
