// The shared vocabulary: one flat record of physical-unit numbers, used by the
// UI, presets, randomize and the DSP engine alike. Imports nothing.

export const DEFAULT_CONTROLS = {
  chipLevel: 0.6,
  chipTune: 0,
  chipTone: 0,
  chipAccomp: 0,
  chipClockX: 1,
  chipStarve: 0,
  chipBattery: 0,
  chipCap: 0,
  chipClipHz: 0,
  chipClipClock: 0,
  chipDataLine: 0,
  chipDataFault: 0,
  chipAddrLine: 0,
  chipAddrFault: 0,
  chipBusCut: 1,
  chipBendSpot: 0,
  chipBendPot: 0,
  chipDrift: 0,
  chipLatch: 0,

  // The parts on the toy board, as opposed to what you are doing to it. Every
  // default here is the number that used to be compiled in, so a board nobody
  // has touched them on is the board that shipped.
  chipLeadR: 0,
  chipDecouple: 120,
  chipWatchdog: 0.21,
  chipLatchHold: 0.06,
  chipClipBite: 1.2,
  chipClipHold: 110,
  chipClipCharge: 40,
  chipClipRelease: 400,
  chipDragOct: 4,
  chipSpread: 1,
  chipMixDrive: 0.35,

  // The melody memory: sixteen steps of what you played, filed the way the demo
  // songs are so the chip plays yours off the same counter. -128 is a step with
  // nothing on it, -127 one that holds whatever the step before struck; anything
  // else is a semitone above the chip's bottom A. See tune.ts.
  tuneStep0: -128,
  tuneStep1: -128,
  tuneStep2: -128,
  tuneStep3: -128,
  tuneStep4: -128,
  tuneStep5: -128,
  tuneStep6: -128,
  tuneStep7: -128,
  tuneStep8: -128,
  tuneStep9: -128,
  tuneStep10: -128,
  tuneStep11: -128,
  tuneStep12: -128,
  tuneStep13: -128,
  tuneStep14: -128,
  tuneStep15: -128,
  tuneLen: 16,
  tuneRate: 3.2,

  drumLevel: 0.7,
  drumBpm: 118,
  drumSwing: 0,
  drumTune: 1,
  drumDecay: 1,
  drumBits: 7,
  drumLadder: 0,
  drumLadderTol: 0.15,
  drumOverflow: 0,
  drumRetrigHz: 0,
  drumTrigFloor: 0,
  drumCross: 0,
  drumCrossAmt: 0.5,
  drumAddrLine: 0,
  drumAddrFault: 0,
  drumDataLine: 0,
  drumDataFault: 0,
  drumBusCut: 1,

  // The pattern: one sixteen-bit mask per voice, step 1 in the high bit so the
  // literal reads left to right like the grid. This is the 'rock' ROM.
  drumKick: 0b1000_0000_1001_0000,
  drumSnare: 0b0000_1000_0000_1000,
  drumHat: 0b0010_0010_0010_0010,
  drumClap: 0,
  drumTom: 0,
  drumBell: 0,
  drumAccent: 0,

  // How many of those steps each row plays before it comes round again. All
  // sixteen is the machine as it left the factory; anything else is polymeter —
  // five on the hat against sixteen on the kick takes a minute to line back up.
  drumKickLen: 16,
  drumSnareLen: 16,
  drumHatLen: 16,
  drumClapLen: 16,
  drumTomLen: 16,
  drumBellLen: 16,
  drumAccentLen: 16,

  fmLevel: 0,
  fmVoice: 0,
  fmBright: 0.5,
  fmFeedback: 0,
  fmModRatio: 0,
  fmCarRatio: 0,
  fmModDecay: 0,
  fmLength: 0.4,
  fmStruck: 0,
  fmEffect: 0,
  fmDataLine: 0,
  fmDataFault: 0,
  fmAddrLine: 0,
  fmAddrFault: 0,
  fmBusCut: 1,
  fmStrobe: 0,
  fmWaveLine: 0,
  fmWaveFault: 0,

  oscLevel: 0,
  oscAHz: 220,
  oscBHz: 55,
  oscXmod: 0,
  oscShape: 0,
  oscStarve: 0,

  noiseLevel: 0,
  noiseColor: 0,
  crackleAmp: 0,
  crackleRate: 20,

  micLevel: 0,
  micPatch: 0,
  sampleLevel: 0,
  sampleSpeed: 1,
  sampleTrig: 0,
  sampleMode: 0,
  loopRec: 0,
  loopErase: 1,
  loopSecs: 4,

  // The bus the six of them sum onto, and the one thing about it that is not
  // one of their faders.
  mixDrive: 0,

  bendSlot0: 1,
  bendSlot1: 2,
  bendSlot2: 3,
  bendSlot3: 6,
  bendSlot4: 4,
  bendSlot5: 5,

  ringHz: 300,
  ringShape: 0,
  ringMix: 0,

  bits: 16,
  srHz: 48000,
  srJitter: 0,
  crushMix: 0,

  driveDb: 12,
  distBias: 0,
  distMode: 0,
  distToneHz: 8000,
  subLevel: 0,
  distMix: 0,

  filtHz: 800,
  filtRes: 0.7,
  filtMode: 0,
  filtDriveDb: 0,
  filtMix: 0,

  combHz: 110,
  combFb: 0.7,
  combDampHz: 6000,
  combMix: 0,

  glitchProb: 0.3,
  glitchSliceMs: 120,
  glitchRepeat: 3,
  glitchRevProb: 0.3,
  glitchPitch: 0,
  glitchFreeze: 0,
  glitchMix: 0,

  shiftHz: 200,
  shiftDir: 0,
  shiftFb: 0,
  shiftMix: 0,

  stompCircuit: 0,
  stompDrive: 18,
  stompTone: 0.5,
  stompBias: 0,
  stompSag: 0,
  stompLevel: 0,
  stompMix: 0,

  delayMs: 350,
  dlyFb: 0.35,
  wowDepthMs: 0,
  wowHz: 0.8,
  flutter: 0,
  dlyToneHz: 6000,
  tapeBrake: 0,
  tapeMotorRail: 0,
  dlyMix: 0,

  echoMode: 0,
  echoMs: 350,
  echoFb: 0.35,
  echoToneHz: 8000,
  echoMod: 0.3,
  echoLevel: 0,

  revDecayS: 2,
  revToneHz: 4000,
  revBoing: 0.5,
  revMix: 0,
  revDryCut: 0,

  modLfoHz: 1,
  modLfoShape: 0,
  mod0Src: 0,
  mod0Dest: 0,
  mod0Depth: 0.5,
  mod1Src: 0,
  mod1Dest: 1,
  mod1Depth: 0.5,
  mod2Src: 0,
  mod2Dest: 2,
  mod2Depth: 0.5,
  mod3Src: 0,
  mod3Dest: 4,
  mod3Depth: 0.5,
  bodyX: 0,
  bodyY: 0,

  trigToKeys: 0,
  trigKeysNote: 0,
  trigToDrum: 0,

  fbAmt: 0,
  fbDelayMs: 5,
  fbTone: 0,
  fbDest: 0,
  fb2Amt: 0,
  fb2Ms: 37,
  fb2Tone: 0,
  fb3Amt: 0,
  fb3Ms: 121,
  fb3Tone: 0,
  fbCross: 0,
  fbRails: 0,
  fbAsym: 0,
  fbSlew: 0,
  fbBlock: 0,
  fbSag: 0,

  brownAmt: 0,
  brownRate: 6,
  brownCrackle: 0,
  humLevel: 0,
  humHz: 0,

  tapeMix: 0,
  tapeSpeed: 1,
  tapeDrive: 6,
  tapeBias: 0,
  tapeHiss: 0.35,
  tapeWow: 0.25,
  tapeFlutter: 0.25,
  tapeDrop: 0,
  tapePrint: 0,
  tapeAzimuth: 0,
  tapeHyst: 0.3,
  tapeBump: 0.5,
  tapeSqueal: 0,

  heatAmt: 0,
  faultCluster: 0,
  jointChatter: 0,
  relayRate: 0,
  couple: 0,

  outGain: 0,
}

export type Controls = typeof DEFAULT_CONTROLS
export type ControlKey = keyof Controls
export const CONTROL_KEYS = Object.keys(DEFAULT_CONTROLS) as ControlKey[]

export const sameControls = (a: Controls, b: Controls) =>
  CONTROL_KEYS.every(k => a[k] === b[k])
